### ISSUE TITLE
Error to install diesel_cli

### ISSUE THREAD

**Issue by WELDISSON** [diesel-rs/diesel#2279] opened 2020-01-24 16:00 UTC
### Versions

- **Rust:1.40.0
- **Operating System: ** Mac Os X Mojave

## Problem Description

When installing diesel_cli I get an error

`$ cargo install diesel_cli`
 
error[E0275]: overflow evaluating the requirement `<Self as query_dsl::limit_dsl::LimitDsl>::Output`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0275`.
error: could not compile `diesel`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `diesel_cli v1.4.0`, intermediate artifacts can be found at `/tmp/cargo-install3RaoRw`

Caused by:
  build failed

**Comment by weiznich** [comment] 2020-01-24 20:05
Duplicate of #2270

**Closed by weiznich** 2020-01-24 20:05 UTC
