### ISSUE TITLE
Remove the need to extern crate

### ISSUE THREAD

**Issue by krojew** [diesel-rs/diesel#2155] opened 2019-08-28 05:24 UTC
### Versions

- **Rust:** 1.39.0-nightly (bea0372a1 2019-08-20)
- **Diesel:** 1.4.0
- **Database:** all
- **Operating System** all

### Feature Flags

- **diesel:** mysql

## Problem Description

Currently diesel requires the use of `#[macro_use] extern crate diesel;` in order to work due to autogenerated schema.rs with macros. Since extern crate is unidiomatic, it would be nice if diesel explicitly imported all required dependencies to schema.rs.

### What are you trying to accomplish?

Remove the need for extern crate diesel.

### What is the expected output?

All dependencies explicitly `use`d;

## Checklist

- [x ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2019-08-28 08:24
Duplicate of #1764

**Closed by weiznich** 2019-08-28 08:24 UTC
