### ISSUE TITLE
cargo install diesel_cli --no-default-features --features mysql occurs LNK2019

### ISSUE THREAD

**Issue by llxxbb** [diesel-rs/diesel#2366] opened 2020-04-17 04:27 UTC
## Setup

cargo install diesel_cli --no-default-features --features mysql

### Versions
- **Rust:** 1.44
- **Diesel:** 1.4.4 
- **Diesel_Cli:** 1.4.0
- **Database:** mysql
- **Operating System** win10_64

### Feature Flags

- **diesel:**

## Problem Description

I have download https://cdn.mysql.com/archives/mysql-connector-c/mysql-connector-c-6.1.11-winx64.zip
unzipped and set env variable MYSQLCLIENT_LIB_DIR to unzipped\lib\vs14
and run cargo install diesel_cli --no-default-features --features mysql
then got :

  = note: diesel-461b1ec22ae44d35.diesel.3wni0jih-cgu.9.rcgu.o : error LNK2019: unresolved external symbol _mysql_stmt_bind_param referenced in function __ZN6diesel5mysql10connection4bind5Binds16with_mysql_binds17h629b182545f44d6eE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.4.rcgu.o) : error LNK2019: unresolved external symbol _mysql_free_result referenced in function __ZN4core3ptr13drop_in_place17hb3f20606f2c3537cE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.7.rcgu.o) : error LNK2001: unresolved external symbol _mysql_free_result
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2001: unresolved external symbol _mysql_free_result
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.4.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_execute referenced in function __ZN6diesel5mysql10connection4stmt8iterator17StatementIterator3new17h31758a750c73e6b5E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _mysql_stmt_execute
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.4.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_store_result referenced in function __ZN6diesel5mysql10connection4stmt8iterator17StatementIterator3new17h31758a750c73e6b5E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _mysql_stmt_store_result
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.4.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_fetch referenced in function __ZN6diesel5mysql10connection4stmt8iterator17StatementIterator4next17h84c2274aac29d40dE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.4.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_result_metadata referenced in function __ZN6diesel5mysql10connection4stmt8iterator22NamedStatementIterator3new17h47b6ac3f04e29e92E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _mysql_stmt_result_metadata
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.4.rcgu.o) : error LNK2019: unresolved external symbol _mysql_num_fields referenced in function __ZN6diesel5mysql10connection4stmt8iterator22NamedStatementIterator3new17h47b6ac3f04e29e92E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.7.rcgu.o) : error LNK2001: unresolved external symbol _mysql_num_fields
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.4.rcgu.o) : error LNK2019: unresolved external symbol _mysql_fetch_fields referenced in function __ZN6diesel5mysql10connection4stmt8iterator22NamedStatementIterator3new17h47b6ac3f04e29e92E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.7.rcgu.o) : error LNK2001: unresolved external symbol _mysql_fetch_fields
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_bind_result referenced in function __ZN6diesel5mysql10connection4bind5Binds16with_mysql_binds17h60be92c04f8b373eE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _mysql_stmt_bind_result
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_fetch_column referenced in function __ZN6diesel5mysql10connection4bind5Binds24populate_dynamic_buffers17h2591120618803387E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _mysql_stmt_fetch_column
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.7.rcgu.o) : error LNK2019: unresolved external symbol _mysql_server_init referenced in function __ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17hb975bff869272900E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_close referenced in function __ZN4core3ptr13drop_in_place17h9c41ca8c0fc47da0E.llvm.8675839193871638686
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _mysql_close
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_close referenced in function __ZN4core3ptr13drop_in_place17hf27833d717c43882E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _mysql_stmt_close
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.0.rcgu.o) : error LNK2001: unresolved external symbol _mysql_stmt_close
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_init referenced in function __ZN6diesel5mysql10connection3raw13RawConnection3new17h353e50f163866e3bE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_options referenced in function __ZN6diesel5mysql10connection3raw13RawConnection3new17h353e50f163866e3bE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_real_connect referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7connect17h47f01ce05a2c96e3E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_error referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7connect17h47f01ce05a2c96e3E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_real_query referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7execute17hf759fefe2924ff5bE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_store_result referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7execute17hf759fefe2924ff5bE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_more_results referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7execute17hf759fefe2924ff5bE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_next_result referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7execute17hf759fefe2924ff5bE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_set_server_option referenced in function __ZN6diesel5mysql10connection3raw13RawConnection23enable_multi_statements17h289a70ea2a179f63E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_affected_rows referenced in function __ZN6diesel5mysql10connection3raw13RawConnection13affected_rows17h69154fa242bcf59cE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _mysql_affected_rows
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_init referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7prepare17h535a1113cec55a96E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.6.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_prepare referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7prepare17h535a1113cec55a96E
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _mysql_stmt_prepare
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_affected_rows referenced in function __ZN6diesel5mysql10connection4stmt9Statement13affected_rows17heb7335c4ae4200ceE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_error referenced in function __ZN6diesel5mysql10connection4stmt9Statement18did_an_error_occur17h9057c19f94d8e82bE
          libdiesel-383fbc541feb9f85.rlib(diesel-383fbc541feb9f85.diesel.dh14ife0-cgu.10.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_errno referenced in function __ZN6diesel5mysql10connection4stmt9Statement18did_an_error_occur17h9057c19f94d8e82bE
          C:\Users\llxxb\AppData\Local\Temp\cargo-installKonlDU\release\deps\diesel-461b1ec22ae44d35.exe : fatal error LNK1120: 28 unresolved externals

error: aborting due to previous error

error: failed to compile `diesel_cli v1.4.0`, intermediate artifacts can be found at `C:\Users\llxxb\AppData\Local\Temp\cargo-installKonlDU`

Caused by:
  could not compile `diesel_cli`

**Comment by weiznich** [comment] 2020-04-17 08:13
Duplicate of #2262

**Closed by weiznich** 2020-04-17 08:13 UTC

**Comment by llxxbb** [comment] 2020-04-17 13:36
@weiznich I‘m not under window sub linux, and installed mysqlclient.lib, the mysqlclient-sys already passed complied. and crashed at the last package that is diesel_cli

**Comment by weiznich** [comment] 2020-04-17 14:24
Please don't ping me directly with such [issues anymore](https://github.com/diesel-rs/diesel/issues/487#issuecomment-614650034). As already stated: It's a problem with your environment so we cannot fix that for you.

**Comment by godbrain** [comment] 2020-04-17 15:21
@llxxbb, can you try these instructions but replace posgres paths with MySQL paths on your system? It's probably about the same.
[dieselinstallonwin10.pdf](https://github.com/diesel-rs/diesel/files/4493756/dieselinstallonwin10.pdf)

**Comment by llxxbb** [comment] 2020-04-18 12:08
@godbrain thanks, I tried but faild.

**Comment by llxxbb** [comment] 2020-04-19 02:27
@weiznich sorry for ping you again, but this time is a good news, I resolved it! The `rustup install` gave me a wrong default target-triple: i686, and I changed it to x86_64, then it works. @godbrain thanks again.
