### ISSUE TITLE
Caching fails because of invalid RefCell borrow

### ISSUE THREAD

**Issue by aggalex** [diesel-rs/diesel#2840] opened 2021-08-03 15:24 UTC
### Versions

- **Rust:** 1.56.0-nightly (docker)
- **Diesel:** 1.4.7
- **Database:** Postgres
- **Operating System** Debian (docker)

## Problem Description

I'm using diesel with Rocket. After some time of caching, diesel seems to try and borrow stuff from a RefCell that is already borrowed, and that makes threads panic:

    Thread '<unnamed>' panicked at 'already mutably borrowed: BorrowError', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.6/src/connection/statement_cache.rs:126:20

### What are you trying to accomplish?

Communicate with the database

### What is the expected output?

Diesel should get or find a query that is equivalent to my code, send it to the database and return the results

### What is the actual output?

Diesel crashes my thread because it's trying to borrow a cache store that is already mutably borrowed

### Steps to reproduce

I'm not really sure how to reproduce the problem. Here's how I found it:
1. launch the server
2. wait for it to communicate with the database a bit (a day or so)
3. find the error in the server's logs

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [?] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [?] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-08-03 15:37
As the issue is currently written this is not actionable at all. Please include at least the following information:
* The code that causes the crash
* Clarify the exact diesel version you used. You mentioned 1.4.7 in the issue template, while the panic message indicates 1.4.6
* Check if that issue is reproducible at rusts stable release channel, otherwise this is a nightly regression and should be reported in the rustc issue tracker. 
* Check if you can reproduce the issue without any third party crate (especially without rocket)

At least the first three points are mandatory as otherwise this issue is not actionable for anyone and will be closed as cannot reproduce.

**Comment by weiznich** [comment] 2021-08-04 12:32
So I've done a bit of research how this could happen:

That's the location](https://github.com/diesel-rs/diesel/blob/bcaec2752266351aa3d341d2428e1f4752e6ca2e/diesel/src/connection/statement_cache.rs#L126) the panic message mentions.
Unfortunately the OP did not include an Backtrace, but there is only a single location inside of `PgConnection` where this is called from: [PgConnection::prepare_query](https://github.com/diesel-rs/diesel/blob/bcaec2752266351aa3d341d2428e1f4752e6ca2e/diesel/src/pg/connection/mod.rs#L149)

The second part here is that we would need a concurrent mutable borrow. The only location where this happens is [here](https://github.com/diesel-rs/diesel/blob/1.4.x/diesel/src/connection/statement_cache.rs#L148), which is only called from [here in `PgConnection::prepare_query`](https://github.com/diesel-rs/diesel/blob/bcaec2752266351aa3d341d2428e1f4752e6ca2e/diesel/src/pg/connection/mod.rs#L152).

That means both calls are in the same function, so you cannot trigger the described behaviour without calling the function twice at the same time. In my understanding that would require having at least two threads that have access to the same connection at the same time. Now does `PgConnection` implement `Send` but not `Sync`, which explicitly communicates that it is safe to move a connection into another thread, but it is not safe to access the connection from more than one thread at the same time. This implies that this must be an issue caused by other code, likely outside of diesel. 

Closed as cannot reproduce due to missing information.

**Closed by weiznich** 2021-08-04 12:32 UTC
Labels: bug
