### ISSUE TITLE
Unable to compile on x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by aknarts** [diesel-rs/diesel#2943] opened 2021-11-03 07:52 UTC
## Setup
I have GUI app that I am trying to cross compile to Windows, sadly this fails.

### Versions

- **Rust: 1.56.1**
- **Diesel: 1.4**
- **Diesel Migrations: diesel_migrations**
- **Database: sqlite**
- **Operating System Fedora 35**

### Feature Flags

- **diesel: sqlite, r2d2**
- **diesel_migrations: sqlite, r2d2**

## Problem Description
Everything else seems to compile fine but `migrations_macros` seems to want to link against pthread which seems to cause linker issues.
Full log available here: https://gist.github.com/aknarts/4d550f3465b50a2c01eebd6308272790

### What are you trying to accomplish?
Cross compile the application

### What is the actual output?
```
 Compiling migrations_macros v1.4.2
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.0.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.1.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.10.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.11.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.12.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.13.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.14.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.15.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.2.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.3.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.4.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.5.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.6.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.7.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.8.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.9.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.2fdu83vmv38u1gwi.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.42ocdi0ht37im4v5.rcgu.o" "-Wl,--as-needed" "-L" "/mnt/_build/target/debug/deps" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/mnt/_build/target/debug/deps/libsyn-1daadaba09222e9e.rlib" "/mnt/_build/target/debug/deps/libquote-c87cdc3ba9323ebc.rlib" "/mnt/_build/target/debug/deps/libproc_macro2-1426ea250741ca11.rlib" "/mnt/_build/target/debug/deps/libunicode_xid-aaec5e16cc5b4e79.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-b9da74e69e83457f.rlib" "/mnt/_build/target/debug/deps/libmigrations_internals-e4de5b6c89481a00.rlib" "/mnt/_build/target/debug/deps/libdiesel-323fe1f4774c3b2a.rlib" "/mnt/_build/target/debug/deps/liblibsqlite3_sys-35f32a98d0663d44.rlib" "/mnt/_build/target/debug/deps/libr2d2-8b16a78821db181f.rlib" "/mnt/_build/target/debug/deps/libscheduled_thread_pool-7c0e8b6db2650e24.rlib" "/mnt/_build/target/debug/deps/libparking_lot-fe8739b02289dc99.rlib" "/mnt/_build/target/debug/deps/libparking_lot_core-2549fdee841ce8a7.rlib" "/mnt/_build/target/debug/deps/liblibc-b5ac3bcc1e9f525b.rlib" "/mnt/_build/target/debug/deps/libsmallvec-625b889d3db5168f.rlib" "/mnt/_build/target/debug/deps/liblock_api-a82c14b263ee1440.rlib" "/mnt/_build/target/debug/deps/libscopeguard-e4ce1e91fe43df34.rlib" "/mnt/_build/target/debug/deps/libinstant-24f006b0a019c4f1.rlib" "/mnt/_build/target/debug/deps/liblog-e174dda31b8d58a4.rlib" "/mnt/_build/target/debug/deps/libcfg_if-0c646b04edbea3dc.rlib" "/mnt/_build/target/debug/deps/libbyteorder-0b2ee968145e4464.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-65a28bf1738424c0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-ba99c63b775f734c.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-2c795be2d1f43514.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-4225fa5bc39268de.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-a6e9f64eae6e45dd.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-b1c963add6e8b853.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-541ca82647a7fb7c.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-b93187d0f71da706.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-12352e7b2d1a318e.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-3787a903f1bee791.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-fdd9bd7e7b7760b0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-4274f5e0121314fe.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-496757222b2a1fa7.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-e68feee69f5a82d8.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-5d6d15fab36665ef.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-10916d3506f78066.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-f6aebf5fbe06d09a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-4e1b16fc9c111ada.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-02203e01b7df4fdd.rlib" "-Wl,-Bdynamic" "-lsqlite3" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/mnt/_build/target/debug/deps/libmigrations_macros-9f1be90d5346d304.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x1a): undefined reference to `__imp_EnterCriticalSection'
          /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x48): undefined reference to `__imp_ReleaseSemaphore'
          /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x55): undefined reference to `__imp_LeaveCriticalSection'
          /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x75): undefined reference to `__imp_LeaveCriticalSection'
          /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x9a): undefined reference to `__imp_LeaveCriticalSection'
           Compiling migrations_macros v1.4.2
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.0.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.1.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.10.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.11.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.12.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.13.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.14.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.15.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.2.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.3.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.4.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.5.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.6.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.7.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.8.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.migrations_macros.97d87d59-cgu.9.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.2fdu83vmv38u1gwi.rcgu.o" "/mnt/_build/target/debug/deps/migrations_macros-9f1be90d5346d304.42ocdi0ht37im4v5.rcgu.o" "-Wl,--as-needed" "-L" "/mnt/_build/target/debug/deps" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/mnt/_build/target/debug/deps/libsyn-1daadaba09222e9e.rlib" "/mnt/_build/target/debug/deps/libquote-c87cdc3ba9323ebc.rlib" "/mnt/_build/target/debug/deps/libproc_macro2-1426ea250741ca11.rlib" "/mnt/_build/target/debug/deps/libunicode_xid-aaec5e16cc5b4e79.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-b9da74e69e83457f.rlib" "/mnt/_build/target/debug/deps/libmigrations_internals-e4de5b6c89481a00.rlib" "/mnt/_build/target/debug/deps/libdiesel-323fe1f4774c3b2a.rlib" "/mnt/_build/target/debug/deps/liblibsqlite3_sys-35f32a98d0663d44.rlib" "/mnt/_build/target/debug/deps/libr2d2-8b16a78821db181f.rlib" "/mnt/_build/target/debug/deps/libscheduled_thread_pool-7c0e8b6db2650e24.rlib" "/mnt/_build/target/debug/deps/libparking_lot-fe8739b02289dc99.rlib" "/mnt/_build/target/debug/deps/libparking_lot_core-2549fdee841ce8a7.rlib" "/mnt/_build/target/debug/deps/liblibc-b5ac3bcc1e9f525b.rlib" "/mnt/_build/target/debug/deps/libsmallvec-625b889d3db5168f.rlib" "/mnt/_build/target/debug/deps/liblock_api-a82c14b263ee1440.rlib" "/mnt/_build/target/debug/deps/libscopeguard-e4ce1e91fe43df34.rlib" "/mnt/_build/target/debug/deps/libinstant-24f006b0a019c4f1.rlib" "/mnt/_build/target/debug/deps/liblog-e174dda31b8d58a4.rlib" "/mnt/_build/target/debug/deps/libcfg_if-0c646b04edbea3dc.rlib" "/mnt/_build/target/debug/deps/libbyteorder-0b2ee968145e4464.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-65a28bf1738424c0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-ba99c63b775f734c.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-2c795be2d1f43514.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-4225fa5bc39268de.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-a6e9f64eae6e45dd.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-b1c963add6e8b853.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-541ca82647a7fb7c.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-b93187d0f71da706.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-12352e7b2d1a318e.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-3787a903f1bee791.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-fdd9bd7e7b7760b0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-4274f5e0121314fe.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-496757222b2a1fa7.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-e68feee69f5a82d8.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-5d6d15fab36665ef.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-10916d3506f78066.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-f6aebf5fbe06d09a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-4e1b16fc9c111ada.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-02203e01b7df4fdd.rlib" "-Wl,-Bdynamic" "-lsqlite3" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/mnt/_build/target/debug/deps/libmigrations_macros-9f1be90d5346d304.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x1a): undefined reference to `__imp_EnterCriticalSection'
          /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x48): undefined reference to `__imp_ReleaseSemaphore'
          /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x55): undefined reference to `__imp_LeaveCriticalSection'
          /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x75): undefined reference to `__imp_LeaveCriticalSection'
          /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-cond.o):(.text+0x9a): undefined reference to `__imp_LeaveCriticalSection'
          .
          .
          .
          /usr/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-nanosleep.o):(.text+0x124): undefined reference to `__imp__errno'
          /usr/bin/ld: BFD version 2.37-10.fc35 assertion fail reloc.c:8489
          /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpthread.a(libwinpthread_la-thread.o):(.xdata+0xa0): dangerous relocation: collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
          compilation terminated.
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```
https://gist.github.com/aknarts/4d550f3465b50a2c01eebd6308272790

### Are you seeing any additional errors?
The strangest thing is that in the command in the log it says stable-x86_64-unknown-linux-gnu while my cargo command is 
```
cargo build --target=x86_64-pc-windows-gnu 
```

**Comment by weiznich** [comment] 2021-11-03 08:23
Sounds like a duplicate of https://github.com/diesel-rs/diesel/issues/2650.
Generally if you cross compile something using the sqlite backend I would just enable the `libsqlite3-sys/bundled` feature, so that a matching libsqlite3 version in cross compiled and statically linked with your binary.
Closed as a linker error always indicates a missing library in your environment and that's something diesel cannot fix + our issue tracker is no support forum.

**Closed by weiznich** 2021-11-03 08:23 UTC
Labels: bug
