### ISSUE TITLE
Need diesel + sqlite example

### ISSUE THREAD

**Issue by Boiethios** [diesel-rs/diesel#708] opened 2017-02-15 14:28 UTC
Hi, I am currently creating a little wep app in Rust, and I need a tiny database. SQLite is the best choice since it is light and do not need a running server. But I am pretty new to databases and the example with postgresql is too complicated for me. I tried to adapt it to SQLite but I have still some errors.

Is it possible to add an example with SQLite?

**Comment by sgrif** [comment] 2017-02-15 14:38
Duplicate of #376

**Closed by sgrif** 2017-02-15 14:38 UTC
