### ISSUE TITLE
How to prevent with/without primary key redundant model structs?

### ISSUE THREAD

**Issue by dctremblay** [diesel-rs/diesel#2474] opened 2020-08-01 17:37 UTC
### versions

- **Rust:** 1.44.1
- **Diesel:** 1.4.4
- **Database:** PostgreSQL
- **Operating System** Kubuntu 20.04

### problem

The only way I have found seems to be redundant and it would like a way that prevent duplicated code like this :

```rust
#[derive(Queryable)]
pub struct Post {
    pub id: i32,
    pub title: String,
    pub body: String,
    pub published: bool,
}

#[derive(Insertable)]
#[table_name="posts"]
pub struct NewPost {
    pub title: String,
    pub body: String,
    pub published: bool,
} // I know that &str would be better for this purpose
```

### expected output

I guess that there is a way to achieve this kind of stuff :

```rust
#[derive(Queryable, Insertable)]
#[table_name="posts"]
pub struct Post {
    pub id: Option<i32>,
    pub title: String,
    pub body: String,
    pub published: bool,
}
```

or else :

```rust
#[derive(Queryable)]
pub struct Post {
    pub title: String,
    pub body: String,
    pub published: bool,
}

#[derive(Insertable)]
#[table_name="posts"]
pub struct NewPost<'a> {
    pub id: i32,
    pub post: &'a Post,
}
```

Thank you very much

**Comment by weiznich** [comment] 2020-08-01 20:50
Basically a duplicate of https://github.com/diesel-rs/diesel/issues/1440.
See [this reddit thread](https://old.reddit.com/r/programming/comments/hpzqvt/rust_is_surprisingly_good_as_a_server_language/fxv3rfl/) for more details on the reasoning.

**Closed by weiznich** 2020-08-01 20:50 UTC
