### ISSUE TITLE
`table!` macros triggers host of deprecation warnings

### ISSUE THREAD

**Issue by sebasv** [diesel-rs/diesel#1928] opened 2018-12-01 08:54 UTC
### Versions

- **Rust:1.30.1**
- **Diesel:1.3.3**
- **Database:MySQL**
- **Operating System: Ubuntu 18.04**

### Feature Flags

- **diesel: `mysql`**

## Problem Description

`table!` macro triggers a host of "names from parent modules are not accessible without an explicit import" warnings.

### Steps to reproduce

models.rs
```rust
#[derive(Queryable)]
pub struct Foo {
    bar1: i32,
    bar2: Option<String>,
}
```
schema.rs
```rust
table! {
    foo (bar1) {
        bar1 -> Integer,
        bar2 -> Nullable<Text>,
    }
}
```
main.rs
```rust
#[macro_use]
extern crate diesel;
mod models;
mod schema;

fn main() {
    println!("Hello, world!");
}
```

### Output:

```rust

warning: cannot find type `Foo` in this scope
 --> src/models.rs:1:10
  |
1 | #[derive(Queryable)]
  |          ^^^^^^^^^ names from parent modules are not accessible without an explicit import
  |
  = note: #[warn(proc_macro_derive_resolution_fallback)] on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #50504 <https://github.com/rust-lang/rust/issues/50504>

warning: cannot find type `table` in this scope
   --> <::diesel::macros::table_body macros>:165:33
    |
165 | derive ( Debug , Clone , Copy , QueryId ) ] /// The actual table struct
    |                                 ^^^^^^^ names from parent modules are not accessible without an explicit import
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #50504 <https://github.com/rust-lang/rust/issues/50504>

warning: cannot find type `bar1` in this scope
 --> <::diesel::macros::__diesel_column macros>:5:33
  |
5 | derive ( Debug , Clone , Copy , QueryId , Default ) ] pub struct $ column_name
  |                                 ^^^^^^^ names from parent modules are not accessible without an explicit import
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #50504 <https://github.com/rust-lang/rust/issues/50504>

warning: cannot find type `bar2` in this scope
 --> <::diesel::macros::__diesel_column macros>:5:33
  |
5 | derive ( Debug , Clone , Copy , QueryId , Default ) ] pub struct $ column_name
  |                                 ^^^^^^^ names from parent modules are not accessible without an explicit import
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #50504 <https://github.com/rust-lang/rust/issues/50504>

```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2018-12-01 09:58
Duplicate of #1787.
And already fixed on master

**Closed** 2018-12-01 09:58 UTC
