### ISSUE TITLE
Diesel does not build

### ISSUE THREAD

**Issue by pie-flavor** [diesel-rs/diesel#1711] opened 2018-05-21 09:11 UTC
## Setup

```
cargo build
```

### Versions

- **Rust:** rustc 1.28.0-nightly (a1d4a9503 2018-05-20)
- **Diesel:** 1.2.2
- **Database:** MySQL
- **Operating System** Windows 10 1803

### Feature Flags

- **diesel:** `["mysql", "r2d2", "chrono"]`

## Problem Description

Diesel does not compile.

### What are you trying to accomplish?

Compile a program that depends on Diesel.

### What is the expected output?

```
   Compiling diesel v1.2.2
```

### What is the actual output?

```
   Compiling diesel v1.2.2
error[E0053]: method `metadata` has an incompatible type for trait
   --> C:\Users\Adam\.cargo\registry\src\github.com-1ecc6299db9ec823\diesel-1.2.2\src\mysql\types\mod.rs:88:25
    |
88  |     fn metadata(lookup: &()) -> MysqlType {
    |                         ^^^ expected associated type, found ()
    |
   ::: C:\Users\Adam\.cargo\registry\src\github.com-1ecc6299db9ec823\diesel-1.2.2\src\sql_types\mod.rs:402:25
    |
402 |     fn metadata(lookup: &Self::MetadataLookup) -> Self::TypeMetadata;
    |                         --------------------- type in trait
    |
    = note: expected type `fn(&<mysql::backend::Mysql as sql_types::TypeMetadata>::MetadataLookup) -> <mysql::backend::Mysql as sql_types::TypeMetadata>::TypeMetadata`
               found type `fn(&()) -> mysql::backend::MysqlType`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0053`.
error: Could not compile `diesel`.
```

### Are you seeing any additional errors?

Nope.

### Steps to reproduce

```
[dependencies.diesel]
version = "1.2.2"
default-features = false
features = ["mysql", "r2d2", "chrono"]
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by weiznich** [comment] 2018-05-21 09:13
Duplicate of #1700

**Closed** 2018-05-21 09:13 UTC

**Comment by weiznich** [comment] 2018-05-21 09:26
@iamcharleschege Look at the original issue for a workaround.(just use a older nightly from before 15/5/18) Otherwise there is nothing we could do beside waiting for rustc to fix that issue.
