### ISSUE TITLE
fix: `sql_query` error "`Untyped: CompatibleType<std::string::String, Pg>` is not satisfied"

### ISSUE THREAD

**Issue by jjangga0214** [diesel-rs/diesel#3832] opened 2023-10-17 08:13 UTC
### Versions

- **Rust:** 1.70.0 (90c541806 2023-05-31)
- **Diesel:** 2.1.3
- **Database:** Postgres 15 (Version is not important because I do not use either diesel migration or ddl compile check.)
- **Operating System**: macOS Ventura 13.5.2(22G91)

### Feature Flags

- **diesel:** None

## Problem Description

Hi!

An error happens with `sql_query`.

```rs
let _ = sql_query("SELECT foo FROM bar")
    .load::<String>(conn)
    .await?;
```

```rs
error[E0277]: the trait bound `Untyped: CompatibleType<std::string::String, Pg>` is not satisfied
  --> path/to/file.rs:44:10
   |
44 |         .load::<String>(conn)
   |          ^^^^ the trait `CompatibleType<std::string::String, Pg>` is not implemented for `Untyped`
   |
   = help: the trait `CompatibleType<U, DB>` is implemented for `Untyped`
   = note: required for `SqlQuery` to implement `diesel_async::methods::LoadQuery<'_, _, std::string::String>`
```

I think `String` is a leaf scalar, not a struct for a table, so `#derive[QueryableByName]` is unnecessary.
I hope It's *just* supported without any care. 

I `.await`ed because of using `diesel-async`, by the way.

```toml
[dependencies]
diesel = "2.1.3"
diesel-async = { version = "0.4.1", features = ["postgres"] }
dsync = { version = "0.0.16", features = ["async"] }
```

Thanks.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-10-17 10:42
This is expected documented behavior:

> This function exists for cases where a query needs to be written that is not supported by the query builder. Unlike most queries in Diesel, sql_query will deserialize its data by name, not by index. That means that you cannot deserialize into a tuple, and structs which you deserialize from this function will need to have #[derive(QueryableByName)].

[Source](https://docs.diesel.rs/2.1.x/diesel/fn.sql_query.html)

Our issue tracker is a place to report bugs. It's not the right place for feature requests or other support questions. Please use the forum for that.

Closed as this is not a bug.

**Closed by weiznich** 2023-10-17 10:42 UTC
Labels: bug
