### ISSUE TITLE
Runtime Error Causes Hard Crash When Performing Inserts With Bad Schema

### ISSUE THREAD

**Issue by Beamed** [diesel-rs/diesel#1825] opened 2018-08-23 02:04 UTC
## Setup
Have a Postgres instance available to use.
### Versions

- **Rust:** 1.28 Stable
- **Diesel:** 1.3.2
- **Database:** Postgres 9.6
- **Operating System** Windows 10

### Feature Flags

- **diesel:** postgres, r2d2

## Problem Description
When attempting to run an insert, the program fails (crashes without panicking or runtime errors). See below output as an example. An error should definitely be returned by the Result type, rather than perform a hard crash immediately.

### What are you trying to accomplish?
Inserting a row into the database and getting meaningful error handling.

### What is the expected output?
**Error: Unable to perform insert into database**(or some message)
Hello world!

### What is the actual output?
error: process didn't exit successfully: `target\debug\DieselTest.exe` (exit code: 3221225477)

### Are you seeing any additional errors?
error: process didn't exit successfully: `target\debug\DieselTest.exe` (exit code: 3221225477)

### Steps to reproduce
Run the attached code with the "author" field in SQL set as a BIT instead of a BOOLEAN for a postgres backend.

[main.zip](https://github.com/diesel-rs/diesel/files/2312592/main.zip)

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by Beamed** [comment] 2018-08-23 05:11
This is apparently an issue with the schema of the database; I was using a bit when I should have been using a boolean (too much time in MSSQL land). However, I think the error handling here could be improved. I've updated the title to reflect that. Is there anything I can do to assist with that?

**Comment by sgrif** [comment] 2018-08-31 00:15
I've attempted to reproduce your issue with the steps provided, and was unable to. As written, the code prints `Hello, world!`. If I add a `.unwrap` to your insert to view any runtime errors, I receive this error:

> "column \"author\" is of type bit but expression is of type boolean"

A cursory googling shows that the error code you provided is a generic access error on Windows (e.g. their version of a segfault). There is no unsafe code involved in the serialization of booleans, so I suspect this is caused by a misconfiguration in your system, likely in the version of libpq.dll you are linking against.

Since there appears to be no actionable bug in Diesel here, I'm going to close this issue. Feel free to continue to ask questions here, but I can't guarantee we will be able to help with specific configuration issues

**Closed by sgrif** 2018-08-31 00:15 UTC
