### ISSUE TITLE
SQLite primary key columns are Option<i32> for some reason unless explicitly expressed non-null

### ISSUE THREAD

**Issue by erikh** [diesel-rs/diesel#2854] opened 2021-08-15 23:10 UTC
### Versions

- **Rust: 1.54.0**
- **Diesel: 1.4.7**
- **Database: SQLite 3.34.1**
- **Operating System: Linux 5.x**

### Feature Flags

- **diesel: sqlite**

## Problem Description

SQLite does something different with integer primary keys that I'm not fully understanding (log below) but I also notice that if you don't specify the column as not null for primary keys, that it sets the serialization through `derive(Queryable)` as `Option<i32>`. I believe this is incorrect as primary keys are usually not allowed to be null in the first place. I hope I am not misunderstanding something and wasting your time.

To work around, provide `not null` in the column definition for the primary key:

```sql
id integer not null primary key
```

Which will strip the `Option` and make it less dodgy to use in code after a fetch.

I've erased the other questions as I think I've described it all here. I hope it was enough detail. I did not test on other databases and am new to diesel.

### Steps to reproduce

```sql

create table optiony (
  id integer primary key autoincrement
);

create table notoptiony (
  id integer not null primary key autoincrement
);
```

Then

```rust
#[derive(Queryable)]
pub struct Optiony {
  pub id: Option<i32>,
}

#[derive(Queryable)]
pub struct NotOptiony {
  pub id: i32,
}

```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

Oops. The log of the sqlite3 transaction I tested with. It won't actually matter on SQLite because integer primary keys are special and are automatically incremented it seems no matter what you pass it.

```
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> create table foo (test integer primary key autoincrement);
sqlite> insert into foo (test) values (NULL);
sqlite> insert into foo (test) values (NULL);
sqlite> insert into foo (test) values (NULL);
sqlite> insert into foo (test) values (NULL);
sqlite> select * from foo;
1
2
3
4
sqlite> create table bar (test integer not null primary key autoincrement);
sqlite> insert into bar (test) values (NULL);
sqlite> select * from bar;
1
sqlite>
sqlite> create table foo2 (test integer primary key);
sqlite> insert into foo2 (test) values (NULL);
sqlite> select * from foo2;
1
sqlite> create table bar2 (test integer not null primary key);
sqlite> insert into bar2 (test) values (NULL);
sqlite> select * from bar2;
1
```

**Comment by weiznich** [comment] 2021-08-16 07:28
Duplicate of https://github.com/diesel-rs/diesel/issues/1984

**Closed by weiznich** 2021-08-16 07:28 UTC
Labels: bug
