### ISSUE TITLE
Struct implementing Insertable trait has fields number limit

### ISSUE THREAD

**Issue by Azel-ytof** [diesel-rs/diesel#3225] opened 2022-07-10 17:44 UTC
Hi,

I encounter this error, I have maybe done something in the wrong way, or is it a crate problem ?

Thank you in advice for yours answers :)

### Versions

- **Rust:**
- Rustup : 1.24.3
- Cargo: 1.62.0
- **Diesel:**
- diesel: 1.4.8
- diesel_codegen: 0.16.1
- rocket_sync_db_pools: 0.1.0-rc.1
- r2d2: 0.8.9
- r2d2-diesel: 1.0.0
- **Database:**
- postgresql
- **Operating System**
- WSL ubuntu

### Feature Flags

- **diesel:**
- Insertable trait

## Problem Description

Hi,
I've have a struct implement the Insertable trait that have more than 32 fields (Yeah that's a lot)
I encounter the error `the trait bound ... is not satisfied`.
When i comment some fields, the error disapear (32 fields max to not encounter the error)

### Details of errors

`the trait bound `(std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::id, diesel::expression::bound::Bound<diesel::sql_types::Integer, i32>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::position, diesel::expression::bound::Bound<SmallInt, i16>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::duration, diesel::expression::bound::Bound<SmallInt, i16>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::template, diesel::expression::bound::Bound<Text, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::main_color, diesel::expression::bound::Bound<Text, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::secondary_color, diesel::expression::bound::Bound<Text, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::active, diesel::expression::bound::Bound<diesel::sql_types::Bool, bool>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::reference, diesel::expression::bound::Bound<Text, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::title, diesel::expression::bound::Bound<Text, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::description, diesel::expression::bound::Bound<Text, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::city, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::uri, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::is_sale, diesel::expression::bound::Bound<diesel::sql_types::Bool, bool>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::is_rent, diesel::expression::bound::Bound<diesel::sql_types::Bool, bool>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::sale_net_selling_price, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::sale_percentage_fee, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::sale_buyer_price, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::sale_solded, diesel::expression::bound::Bound<diesel::sql_types::Nullable<diesel::sql_types::Bool>, bool>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::rent_net_rental_price, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::rent_with_included_charges, diesel::expression::bound::Bound<diesel::sql_types::Nullable<diesel::sql_types::Bool>, bool>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::rent_charges_amount, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::rent_inventory, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::rent_tenant_charges_terms, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::rent_security_deposit, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::property_acquisition_type, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::property_habitation_type, diesel::expression::bound::Bound<diesel::sql_types::Nullable<Text>, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::epc_score, diesel::expression::bound::Bound<Text, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::epc_value, diesel::expression::bound::Bound<SmallInt, i16>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::gge_score, diesel::expression::bound::Bound<Text, std::string::String>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::gge_value, diesel::expression::bound::Bound<SmallInt, i16>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::screens_id, diesel::expression::bound::Bound<diesel::sql_types::Integer, i32>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::created_at, diesel::expression::bound::Bound<diesel::sql_types::Timestamptz, NaiveDateTime>>>, std::option::Option<diesel::expression::operators::Eq<schema::estate_templates::columns::updated_at, diesel::expression::bound::Bound<diesel::sql_types::Timestamptz, NaiveDateTime>>>): diesel::Insertable<schema::estate_templates::table>` is not satisfied
the following other types implement trait `diesel::Insertable<T>`:
  &'a (A, B)
  &'a (A, B, C)
  &'a (A, B, C, D)
  &'a (A, B, C, D, E)
  &'a (A, B, C, D, E, F)
  &'a (A, B, C, D, E, F, G)
  &'a (A, B, C, D, E, F, G, H)
  &'a (A, B, C, D, E, F, G, H, I)
and 56 others`

### Steps to reproduce

https://gist.github.com/Azel-ytof/b9d0f3af395e6a24cfdb6b2006040c8d

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2022-07-11 07:22
Support for more than 32 columns is behind a feature flag. Checkout the documentation of the `table!` macro for details. Closed as duplicate of various duplicated issues.

**Closed by weiznich** 2022-07-11 07:22 UTC
Labels: bug

**Comment by Azel-ytof** [comment] 2022-07-11 09:07
Oups sorry, I do not find other issues like that, I have maybe do not use right keyword.
Thanks for your answer, I have missed that line in the documentation...
