### ISSUE TITLE
No intellisense when using query dsl

### ISSUE THREAD

**Issue by ohuu** [diesel-rs/diesel#3876] opened 2023-12-12 17:21 UTC
### Versions

- **Rust: 1.74.0**
- **Diesel: 2.1.0**
- **Database: Sqlite**

### Feature Flags

- **diesel: sqlite**

## Problem Description

When following the `getting started` guide everything works correctly. But, I get no intellisense when using the query dsl. For example: when querying the number of posts in the database, like this

```rust
use self::models::*;
use diesel::prelude::*;
use diesel_demo::*;

fn main() {
    use self::schema::posts::dsl::*;

    let connection = &mut establish_connection();
    let results = posts
        .filter(published.eq(true)) // <-- intellisense breaks after this line. All type info is lost although it compiles just fine!
        .limit(5)
        .select(Post::as_select())
        .load(connection)
        .expect("Error loading posts");

    println!("Displaying {} posts", results.len());
    for post in results {
        println!("{}", post.title);
        println!("-----------\n");
        println!("{}", post.body);
    }
}
```

vscode shows `{unknown}` when hovering over `.limit(5)` and the return type of `results` is also unknown. I'm using vscode version 1.85 with the latest rust-analyzer plugin.

**Comment by weiznich** [comment] 2023-12-12 19:32
Duplicate of https://github.com/rust-lang/rust-analyzer/issues/14607 (It's a rust-analyzer bug, not a diesel issue.)

**Closed by weiznich** 2023-12-12 19:32 UTC
Labels: bug

**Comment by cloud303-cholden** [comment] 2024-01-04 22:47
@weiznich Is there a known workaround for this? Although it's an r-a issue, it's effect on diesel's DX is pretty big. Especially as a new user.

**Comment by weiznich** [comment] 2024-01-05 06:21
@cloud303-cholden There is no known workaround for this but I would be open to accept PR's for fixing this in diesel as long as they do not require a major version bump. But given that even the rust-analyzer developers cannot say which part of diesel is problematic (at least other than "the trait bounds") it's quite unlikely that anyone comes up with something on diesels side.

**Comment by cloud303-cholden** [comment] 2024-01-12 19:30
@weiznich Before I possibly waste a lot of time screwing with my r-a setup, I'm assuming some combination of changing r-a and/or diesel version would resolve the issue, correct?

**Comment by weiznich** [comment] 2024-01-15 08:54
@cloud303-cholden Please don't ping me to ask this kind of questions, especially if that has already been answered before.

**Comment by ohuu** [comment] 2024-01-15 10:07
@cloud303-cholden You can use Rust Rover as a "work around" as long as you don't mind using a different IDE. When it comes to this particular bit of code analysis Rust Rover does a better job than Rust Analyzer (at least for now).
