### ISSUE TITLE
diesel: Shared object "libpq.so.5" not found

### ISSUE THREAD

**Issue by gigavinyl** [diesel-rs/diesel#2252] opened 2019-12-20 09:16 UTC
### Versions

- **Rust:** rustc 1.41.0-nightly (99b89533d 2019-12-16)
- **Diesel:** 1.4.3
- **Database:** N/a yet
- **Operating System** NetBSD 9.0_RC1

### Feature Flags

- **diesel:** posgresql

## Problem Description
When running the diesel-cli with any commands, I get the following error
```
diesel: Shared object "libpq.so.5" not found
```

### What are you trying to accomplish?
Setup diesel in my project

### What is the expected output?
The binary runs and returns a list of available commands.

Do I need the cli binary in order to use this library?

**Comment by weiznich** [comment] 2019-12-20 09:27
That's not a bug in diesel, but a problem with your setup. If you use the postgresql backend you will need libpq.

I'm closing this issue because the bug tracker is used to track bugs for the diesel team. Use our [gitter chatroom](https://gitter.im/diesel-rs/diesel) or our [forum](https://discourse.diesel.rs/) to ask questions.

**Closed by weiznich** 2019-12-20 09:27 UTC
