### ISSUE TITLE
Segmantation fault happend when run "diesel setup" command

### ISSUE THREAD

**Issue by ShintaroOba** [diesel-rs/diesel#3307] opened 2022-09-05 07:54 UTC
### Versions

- **Rust:** 1.63.0
- **Diesel:** 2.0.0
- **Database:** Postgres14 (hosted docker container)
- **Operating System** Windows10

### Feature Flags

- **diesel:**``diesel setup``

## Problem Description
I installed diesel_cli for ``cargo install diesel_cli --no-default-features --features postgres``command. 

I run ``diesel setup``command, got a message below.
````
$ diesel setup
Segmentation fault
````
After the running this command, the ``migrations``folder (include up.sql and down.sql)is generated.

Then, I run command below after the ``diesel migration generate``command, the schema.rs is generated but it is empty. (TBL is created, but schema.rs is empty)
````
$ diesel migration run 
Segmentation fault
````
What makes "segmantation fault" and generate empty "schema.rs" happens? 

### detail about my environment

- init.sql (this sql is executed when postgres container run for docker, and mounted in ``docker-entrypoint-initdb.d``.)
````sql
CREATE ROLE diesel WITH LOGIN PASSWORD 'password';
-- Schema
CREATE SCHEMA diesel AUTHORIZATION diesel;

GRANT CONNECT ON DATABASE diesel TO diesel;
GRANT USAGE ON SCHEMA diesel TO diesel;
GRANT ALL ON ALL TABLES IN SCHEMA diesel TO diesel;

````

- up.sql
````sql
create table diesel.users (
  id bigint not null 
  , user_name character varying(50) not null
  , age smallint not null
  , constraint user_id_primary_key primary key (id)
);

create table diesel.cash_flow(
    id bigint not null 
    , user_id bigint not null
    , item character varying(50) not null
    , cash_flow_type character varying(20) not null
    , amount bigint not null
    , constraint cash_id_primary_key primary key (id)
);

alter table diesel.cash_flow
  add constraint user_foreign_key foreign key (user_id) references diesel.users(id)
  on update cascade;
````

- diesel.toml
````toml
[print_schema]
file = "src/schema.rs"
schema = "diesel"

````

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2022-09-05 11:58
Can you provide details about:
* your libpq version
* a backtrace for the segfault

**Comment by weiznich** [comment] 2022-09-05 14:07
There is a known issue with the libpq version provided by enterprise db. See https://github.com/diesel-rs/diesel/discussions/2947 for details. This is likely the same underlying issue. We as diesel team cannot do anything to fix this, please report this upstream. You can verify that by using a different libpq version

> So, it should be ok for now, but I run diesel migration run command in powershell, the schema.rs is empty yet.
Is there anything wrong my sql and diesel.toml and things like that?

Our issue tracker is not meant for support questions. Please open a separate discussion thread for this including all necessary details. For questions like yours this needs to include a database dump of before you tried your migration, all relevant migration files and a reproductions script. Otherwise there are just too many missing information to reproduce anything.

**Comment by ShintaroOba** [comment] 2022-09-05 14:10
Thank you for your comment. I'll check it out.

**Comment by weiznich** [comment] 2022-09-19 14:31
Closed as this seems to be an issue with this specific libpq setup.

**Closed by weiznich** 2022-09-19 14:31 UTC
Labels: bug
