### ISSUE TITLE
examples/mysql/all_about_inserts - `cargo test` usually fails with BadConnection("Plugin caching_sha2_password could not be loaded: it is already loaded") against MySQL 8.0

### ISSUE THREAD

**Issue by mcronce** [diesel-rs/diesel#2706] opened 2021-04-07 19:27 UTC
## Setup
This is with a default-configured MySQL 8.0 (`caching_sha2_password` is the default in 8.0), e.g:
```sh
docker run --rm -d --name=mysql80 -e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=example mysql:8.0
```

### Versions
- **Rust:** `cargo 1.48.0 (65cbdd2dc 2020-10-14)` and `cargo 1.52.0-nightly (90691f2bf 2021-03-16)`
- **Diesel:** `master`
- **Database:** MySQL 8.0
- **Operating System:** Manjaro

### Feature Flags
- **diesel:** `["mysql", "chrono"]`

## Problem Description
I have yet to encounter a problem in any real-world application, but the example fails.  It's a weird one; with #2705 applied, every test passes very occasionally; the vast majority of the time, either `insert_get_results` or `insert_get_results_batch` will fail with `BadConnection("Plugin caching_sha2_password could not be loaded: it is already loaded")`.  Never both.

`cargo test insert_get_results_batch -- --exact` and `cargo test insert_get_result -- --exact` both succeed 100% of the time.

### What are you trying to accomplish?
Running examples against both MySQL and Vitess and comparing the results, to validate Vitess compatibility with Diesel :)

### What is the expected output?
All tests should pass against vanilla MySQL

### What is the actual output?
This test fails with `BadConnection("Plugin caching_sha2_password could not be loaded: it is already loaded")`

### Are you seeing any additional errors?
Only a few whitespace mismatches in assertions, fixed in #2705, which I'm monkey patching in when I run our test harness

### Steps to reproduce
```sh
git clone https://github.com/diesel-rs/diesel.git
cd diesel/examples/mysql/all_about_inserts
docker run --rm -d --name=mysql80 -e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=example mysql:8.0
export DATABASE_URL="mysql://root:example@$(docker inspect mysql80 | jq -r '.[0].NetworkSettings.IPAddress'):3306/test"
diesel database setup && cargo test
```

**Comment by mcronce** [comment] 2021-04-07 19:29
`cargo test --test-threads 1` also succeeds reliably - I'm going to use that as a workaround in our test harness for the time being

**Comment by weiznich** [comment] 2021-04-08 07:54
I cannot reproduce this problem locally with the steps provided in our issue. As a blind guess I would say this is caused by a incompatible version of the `mysqlclient` library linked to your application.

**Comment by weiznich** [comment] 2021-04-15 19:15
Closed as cannot reproduce. Feel free to add more information that may help to reproduce the problem if you keep hitting this issue.

**Closed by weiznich** 2021-04-15 19:15 UTC
Labels: bug
