### ISSUE TITLE
Compile diesel_cli error. (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by unitsoftrover** [diesel-rs/diesel#2903] opened 2021-09-18 05:15 UTC
### Versions

- **Rust:**1.55
- **Diesel:** master
- **Database:** sqlite
- **Operating System**win10

### Feature Flags

- **diesel_cli:**default = ["sqlite"]

## Problem Description
compile diesel/diesel ok.  diesel/diesel_cli compile fail.
error: could not compile `diesel`

Caused by:
  process didn't exit successfully: `rustc --crate-name diesel --edition=2018 diesel\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg "feature=\"32-column-tables\"" --cfg "feature=\"bigdecimal\"" --cfg "feature=\"bitflags\"" --cfg "feature=\"chrono\"" --cfg "feature=\"default\"" --cfg "feature=\"ipnetwork\"" --cfg "feature=\"libc\"" --cfg "feature=\"libsqlite3-sys\"" --cfg "feature=\"mysql\"" --cfg "feature=\"mysqlclient-sys\"" --cfg "feature=\"network-address\"" --cfg "feature=\"num-bigint\"" --cfg "feature=\"num-integer\"" --cfg "feature=\"num-traits\"" --cfg "feature=\"numeric\"" --cfg "feature=\"percent-encoding\"" --cfg "feature=\"quickcheck\"" --cfg "feature=\"serde_json\"" --cfg "feature=\"sqlite\"" --cfg "feature=\"url\"" --cfg "feature=\"uuid\"" --cfg "feature=\"with-deprecated\"" -C metadata=a29971b34ec106ae -C extra-filename=-a29971b34ec106ae --out-dir D:\Rust\diesel\target\debug\deps -C incremental=D:\Rust\diesel\target\debug\incremental -L dependency=D:\Rust\diesel\target\debug\deps --extern bigdecimal=D:\Rust\diesel\target\debug\deps\libbigdecimal-8c76e12b15276138.rmeta --extern bitflags=D:\Rust\diesel\target\debug\deps\libbitflags-94cc8ea4fd943471.rmeta --extern byteorder=D:\Rust\diesel\target\debug\deps\libbyteorder-a74bc0c0f4b28c24.rmeta --extern chrono=D:\Rust\diesel\target\debug\deps\libchrono-a380ea93bc76ffe7.rmeta --extern diesel_derives=D:\Rust\diesel\target\debug\deps\diesel_derives-2b996ff16e76bb7b.dll --extern ipnetwork=D:\Rust\diesel\target\debug\deps\libipnetwork-a47f0f7fe4b19fa8.rmeta --extern itoa=D:\Rust\diesel\target\debug\deps\libitoa-eca13d6ef08c818b.rmeta --extern libc=D:\Rust\diesel\target\debug\deps\liblibc-a1484c83aa08432c.rmeta --extern libsqlite3_sys=D:\Rust\diesel\target\debug\deps\liblibsqlite3_sys-456b5477f4a6ec5b.rmeta --extern mysqlclient_sys=D:\Rust\diesel\target\debug\deps\libmysqlclient_sys-de15c9cd6484d100.rmeta --extern num_bigint=D:\Rust\diesel\target\debug\deps\libnum_bigint-cb29dbb424ae8f95.rmeta --extern num_integer=D:\Rust\diesel\target\debug\deps\libnum_integer-e38632613ea6654c.rmeta --extern num_traits=D:\Rust\diesel\target\debug\deps\libnum_traits-2c7d323ab20b4330.rmeta --extern percent_encoding=D:\Rust\diesel\target\debug\deps\libpercent_encoding-ff57e3026375fa5f.rmeta --extern quickcheck=D:\Rust\diesel\target\debug\deps\libquickcheck-ff51ed94299aac24.rmeta --extern serde_json=D:\Rust\diesel\target\debug\deps\libserde_json-ddf0e3d9017c4ffa.rmeta --extern url=D:\Rust\diesel\target\debug\deps\liburl-acd51d2c908ba683.rmeta --extern uuid=D:\Rust\diesel\target\debug\deps\libuuid-6e95c449488d6e83.rmeta -L "native=C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14"` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
PS D:\Rust\diesel>

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-09-19 10:11
According to the error message this seems to be a duplicate of #2167 and #2132. Both are linker related issues which indicate that some dependency is missing on your system. Without knowing much more details about your system its impossible to tell what exactly is missing.
Closed as this is an issue with your environment and not an diesel issue.

**Closed** 2021-09-19 10:11 UTC
Labels: bug
