### ISSUE TITLE
`diesel_derives` fails to compile with recent version of `quote`

### ISSUE THREAD

**Issue by msrd0** [diesel-rs/diesel#3546] opened 2023-03-13 13:08 UTC
## Problem Description

With a recent (breaking) change in quote, `diesel_derives` fails to compile. I also reported this issue against quote: https://github.com/dtolnay/quote/issues/245

### Error Message

```
   Compiling diesel_derives v2.0.1
error[E0277]: the trait bound `FieldAttr: ToTokens` is not satisfied
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_derives-2.0.1/src/attrs.rs:143:6
    |
143 | impl Spanned for FieldAttr {
    |      ^^^^^^^ the trait `ToTokens` is not implemented for `FieldAttr`
    |
    = help: the following other types implement trait `ToTokens`:
              &'a T
              &'a mut T
              Abi
              Abstract
              AndAnd
              AndEq
              AngleBracketedGenericArguments
              Arm
            and 313 others
    = note: required because of the requirements on the impl of `quote::spanned::private::Sealed` for `FieldAttr`
note: required by a bound in `quote::spanned::Spanned`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.25/src/spanned.rs:6:20
    |
6   | pub trait Spanned: private::Sealed {
    |                    ^^^^^^^^^^^^^^^ required by this bound in `quote::spanned::Spanned`

error[E0277]: the trait bound `StructAttr: ToTokens` is not satisfied
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_derives-2.0.1/src/attrs.rs:242:6
    |
242 | impl Spanned for StructAttr {
    |      ^^^^^^^ the trait `ToTokens` is not implemented for `StructAttr`
    |
    = help: the following other types implement trait `ToTokens`:
              &'a T
              &'a mut T
              Abi
              Abstract
              AndAnd
              AndEq
              AngleBracketedGenericArguments
              Arm
            and 313 others
    = note: required because of the requirements on the impl of `quote::spanned::private::Sealed` for `StructAttr`
note: required by a bound in `quote::spanned::Spanned`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.25/src/spanned.rs:6:20
    |
6   | pub trait Spanned: private::Sealed {
    |                    ^^^^^^^^^^^^^^^ required by this bound in `quote::spanned::Spanned`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `diesel_derives` due to 2 previous errors
```

### Versions

- **Rust:** `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
- **Diesel:** `diesel_derives v2.0.1`
- **Operating System:** Linux

**Comment by weiznich** [comment] 2023-03-13 13:09
Duplicate of https://github.com/diesel-rs/diesel/issues/3541

**Closed by weiznich** 2023-03-13 13:09 UTC
Labels: bug
