### ISSUE TITLE
diesel cli always return without anything

### ISSUE THREAD

**Issue by huangjj27** [diesel-rs/diesel#2632] opened 2021-01-24 09:44 UTC
## Setup
`cargo install diesel_cli --no-default-features --features postgres -f`

### Versions

- **Rust:** rustc 1.49.0 (e1884a8e3 2020-12-29)
- **Diesel:** 1.4.5
- **Database:** postgres 13.1
- **Operating System: ** Windows 10

### Feature Flags

- **diesel:** --no-default-features --features postgres -f

## Problem Description
any command I typed as follow return directly:
```sh
> diesel setup
> diesel --help
> diesel migration
```

### What are you trying to accomplish?
I was setting up a new database, but when I type `diesel setup`, nothing happened( without new empty `migrations` folder, or new database in my postgres server)

### What is the expected output?
1. a new database created in my postgres server, that specificated in `.env` file, with the name `DATABASE_URL`;
2.  an empty `migrations` folder in my cargo project

### What is the actual output?
**NOTHING HAPPENED AND IT RETURNED!**

### Are you seeing any additional errors?
**NOTHING HAPPENED AND IT RETURNED!**

### Steps to reproduce
1.  cargo install diesel_cli --no-default-features --features postgres -f

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2021-01-24 09:57
Duplicate of #2015

**Closed** 2021-01-24 09:57 UTC

**Comment by yuhangang** [comment] 2021-05-10 03:36
When I run this command following the get started guide:
**diesel migration generate create_posts**
it show nothing, neither error or sucess message.

May we have any precise guidance to resolve this?  #2015 doesn't provide enough detail about the solution.

**Comment by weiznich** [comment] 2021-05-10 06:58
@yuanchenxi95 There is no way to give you "precise guidance" here, as this is, as outlined in #2015 an issue with your environment. Only you and noone else can find out what's wrong there, because no other person has access to that environment. Otherwise: Our issue tracker is not the right place to ask for help, so please don't comment to old closed issues, if you don't have new information to add there.

**Comment by yuanchenxi95** [comment] 2021-05-10 07:01
> @yuanchenxi95 There is no way to give you "precise guidance" here, as this is, as outlined in #2015 an issue with your environment. Only you and noone else can find out what's wrong there, because no other person has access to that environment. Otherwise: Our issue tracker is not the right place to ask for help, so please don't comment to old closed issues, if you don't have new information to add there.

You probably intended to mention @yuhangang instead of me here?
