### ISSUE TITLE
diesel did not compile

### ISSUE THREAD

**Issue by adals** [diesel-rs/diesel#1705] opened 2018-05-18 22:51 UTC
hello everyone
at my cargo.toml
diesel = { version = "1.2.0", features = ["postgres"] }
then compile i got

Win8:erp1 $ cargo run
   Compiling diesel v1.2.2
error[E0053]: method `metadata` has an incompatible type for trait
   --> /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.2.2/src/pg/types/array.rs:14:25
    |
14  |     fn metadata(lookup: &PgMetadataLookup) -> PgTypeMetadata {
    |                         ^^^^^^^^^^^^^^^^^ expected associated type, found struct `pg::metadata_lookup::PgMetadataLookup`
    | 
   ::: /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.2.2/src/sql_types/mod.rs:402:25
    |
402 |     fn metadata(lookup: &Self::MetadataLookup) -> Self::TypeMetadata;
    |                         --------------------- type in trait
    |
    = note: expected type `fn(&<pg::backend::Pg as sql_types::TypeMetadata>::MetadataLookup) -> <pg::backend::Pg as sql_types::TypeMetadata>::TypeMetadata`
               found type `fn(&pg::metadata_lookup::PgMetadataLookup) -> pg::backend::PgTypeMetadata`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0053`.
error: Could not compile `diesel`.

To learn more, run the command again with --verbose.

Win8:~ $ rustc -V
rustc 1.27.0-nightly (2f2a11dfc 2018-05-16)

**Comment by Eijebong** [comment] 2018-05-18 23:06
Dupe of #1700 and #1701 
This is getting fixed there: https://github.com/rust-lang/rust/pull/50876

**Closed by Eijebong** 2018-05-18 23:06 UTC
