### ISSUE TITLE
Unsupported JSONB encoding version

### ISSUE THREAD

**Issue by Pzixel** [diesel-rs/diesel#2388] opened 2020-05-08 11:49 UTC
### Versions

- **Rust:** rustc 1.43.0 (4fb7144ed 2020-04-20)
- **Diesel:** 1.4.4
- **Database:** Postgres
- **Operating System** Windows 10 (but it's unrelated)

### Feature Flags

- **diesel:** ["postgres", "r2d2", "uuidv07", "serde_json"]

## Problem Description

It's not possible to fetch entity with `jsonb` column from the database. I'd like to share more information but error doesn't include data on which it failed (e.g. what version of JSONB it faced). See steps for reproduce.

UPD.

I forked 1.4.x and added some additional logging so I've got

```
DeserializationError("Unsupported JSONB encoding version 123")
```

### What are you trying to accomplish?

Fetch entity with `jsonb` column from the database

### What is the expected output?

fetch entity with `jsonb` column from the database

### What is the actual output?

`DeserializationError("Unsupported JSONB encoding version")`

### Are you seeing any additional errors?

No

### Steps to reproduce

1. Install Postgres 12.0
1. Create a table with `uuid` PK and `jsonb` field.
1. Insert some test data
1. Create table and entity model:
	```rust
	use diesel::prelude::*;
	use uuid::Uuid;
	use serde::{Serialize, Deserialize};
	use serde_json::Value as JsonValue;
	use diesel::table;

	#[derive(Queryable, Serialize, Deserialize, Debug)]
	pub struct CompanySettings {
		pub CompanyId: Uuid,
		pub Preset: JsonValue,
	}

	table! {
		dbo.CompanySettingsView (CompanyId) {
			CompanyId -> Uuid,
			Preset -> Jsonb,
		}
	}
	```
1. Try to fetch some data
	```rust
	use schema::CompanySettingsView::dsl::*;

	CompanySettingsView.limit(100).load::<CompanySettings>(&connection)
	```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues. Related to #1788
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2020-05-08 12:27
I've tried to reproduce that locally using postgres 12.2 on ubuntu and I've failed to reproduce the issue with the following code:

```rust

use diesel::prelude::*;
use diesel::table;
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use serde_json::json;
use uuid::Uuid;

table! {
    CompanySettingsView (CompanyId) {
        CompanyId -> Uuid,
        Preset -> Jsonb,
    }
}

#[derive(Queryable, Serialize, Deserialize, Debug)]
pub struct CompanySettings {
    pub CompanyId: Uuid,
    pub Preset: JsonValue,
}

fn main() {
    let conn = PgConnection::establish("postgres://localhost/diesel_tests").unwrap();

    diesel::sql_query(r#"CREATE TABLE IF NOT EXISTS "CompanySettingsView" ("CompanyId" UUID PRIMARY KEY, "Preset" JSONB NOT NULL)"#)
        .execute(&conn)
        .unwrap();

    diesel::insert_into(CompanySettingsView::table)
        .values((
            CompanySettingsView::CompanyId.eq(Uuid::new_v4()),
            CompanySettingsView::Preset.eq(json!({
                "name": "John Doe",
                "age": 43,
                "phones": [
                    "+44 1234567",
                    "+44 2345678"
                ]
            })),
        ))
        .execute(&conn)
        .unwrap();

    let res = CompanySettingsView::table
        .limit(100)
        .load::<CompanySettings>(&conn);

    dbg!(res);
}

```

Feel free to provide an updated example on how to reproduce this issue otherwise I will close this now as cannot reproduce.

**Closed by weiznich** 2020-05-08 12:27 UTC

**Comment by Pzixel** [comment] 2020-05-08 13:13
The problem was field had `Text` type, not `Jsonb`. Because it's view (not a table) I couldn't get the right macro text from `print-scheme` so I have wrote it manually with typos. 

Choosing proper types for columns fixes the issue.
