### ISSUE TITLE
load::<>() and first::<>() should return easier to understand error messages on compile error.

### ISSUE THREAD

**Issue by genusistimelord** [diesel-rs/diesel#2576] opened 2020-11-24 19:50 UTC
### Versions

- **Rust:1.48
- **Diesel:1.4.5
- **Database:postgresql
- **Operating System**
Windows

## Problem Description
A table schema and a structure mapped to the table schema that does not contain the same order OR the struct is missing something from the table schema. When this Occurs a very unreadable and unhelpful Error message is received from cargo during build.

I was able to solve the error by building a new smaller project to directly test the schema and structure to figure out why the error was occurring on load() and first().

### What is the expected output?
I would have Expected the Error message to maybe say

Struct {name} does not match the Table! Schema {name}. The structure is not in the correct order, Contains to many variables or is missing a variable from the schema. Either change the struct or schema to resolve the issue. 

Struct tuple ({:?}) did not match
Schema tuple ({:?})

### What is the actual output?
the trait bound `(i64, std::string::String, std::string::String, time_ext::date::MyDate, gametypes::rgb::Rgb, gametypes::rgb::Rgb, gametypes::rgb::Rgb, gametypes::rgb::Rgb, i16, i16, gametypes::position::Position, time_ext::instant::MyInstant, std::option::Option<std::string::String>, i16, i64, i64, i16, std::vec::Vec<i64>, gametypes::enums::UserAccess, std::vec::Vec<i16>, std::vec::Vec<i16>, std::vec::Vec<i64>, std::vec::Vec<i16>, std::vec::Vec<i16>, std::vec::Vec<i64>, i16, std::vec::Vec<bool>, gametypes::enums::Gods, std::vec::Vec<i16>, i16, gametypes::position::Position, std::vec::Vec<i32>, time_ext::instant::MyInstant, bool, std::vec::Vec<bool>, std::string::String, std::string::String, std::string::String): diesel::Queryable<(diesel::sql_types::BigInt, diesel::sql_types::Text, diesel::sql_types::Text, diesel::sql_types::Timestamp, diesel::sql_types::Date, gametypes::rgb::RgbType, gametypes::rgb::RgbType, gametypes::rgb::RgbType, gametypes::rgb::RgbType, diesel::sql_types::SmallInt, diesel::sql_types::SmallInt, gametypes::position::PosType, diesel::sql_types::BigInt, diesel::sql_types::SmallInt, diesel::sql_types::BigInt, diesel::sql_types::BigInt, diesel::sql_types::SmallInt, diesel::sql_types::Array<diesel::sql_types::BigInt>, gametypes::enums::db_enum_impl_UserAccess::UserAccessMapping, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::BigInt>, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::BigInt>, diesel::sql_types::Nullable<diesel::sql_types::Text>, diesel::sql_types::SmallInt, diesel::sql_types::Array<diesel::sql_types::Bool>, gametypes::enums::db_enum_impl_Gods::GodsMapping, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::SmallInt, gametypes::position::PosType, diesel::sql_types::Array<diesel::sql_types::Integer>, diesel::sql_types::BigInt, diesel::sql_types::Bool, diesel::sql_types::Bool, diesel::sql_types::Array<diesel::sql_types::Bool>, diesel::sql_types::Text, diesel::sql_types::Text, diesel::sql_types::Text), _>` is not satisfied

the trait `diesel::Queryable<(diesel::sql_types::BigInt, diesel::sql_types::Text, diesel::sql_types::Text, diesel::sql_types::Timestamp, diesel::sql_types::Date, gametypes::rgb::RgbType, gametypes::rgb::RgbType, gametypes::rgb::RgbType, gametypes::rgb::RgbType, diesel::sql_types::SmallInt, diesel::sql_types::SmallInt, gametypes::position::PosType, diesel::sql_types::BigInt, diesel::sql_types::SmallInt, diesel::sql_types::BigInt, diesel::sql_types::BigInt, diesel::sql_types::SmallInt, diesel::sql_types::Array<diesel::sql_types::BigInt>, gametypes::enums::db_enum_impl_UserAccess::UserAccessMapping, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::BigInt>, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::BigInt>, diesel::sql_types::Nullable<diesel::sql_types::Text>, diesel::sql_types::SmallInt, diesel::sql_types::Array<diesel::sql_types::Bool>, gametypes::enums::db_enum_impl_Gods::GodsMapping, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::SmallInt, gametypes::position::PosType, diesel::sql_types::Array<diesel::sql_types::Integer>, diesel::sql_types::BigInt, diesel::sql_types::Bool, diesel::sql_types::Bool, diesel::sql_types::Array<diesel::sql_types::Bool>, diesel::sql_types::Text, diesel::sql_types::Text, diesel::sql_types::Text), _>` is not implemented for `(i64, std::string::String, std::string::String, time_ext::date::MyDate, gametypes::rgb::Rgb, gametypes::rgb::Rgb, gametypes::rgb::Rgb, gametypes::rgb::Rgb, i16, i16, gametypes::position::Position, time_ext::instant::MyInstant, std::option::Option<std::string::String>, i16, i64, i64, i16, std::vec::Vec<i64>, gametypes::enums::UserAccess, std::vec::Vec<i16>, std::vec::Vec<i16>, std::vec::Vec<i64>, std::vec::Vec<i16>, std::vec::Vec<i16>, std::vec::Vec<i64>, i16, std::vec::Vec<bool>, gametypes::enums::Gods, std::vec::Vec<i16>, i16, gametypes::position::Position, std::vec::Vec<i32>, time_ext::instant::MyInstant, bool, std::vec::Vec<bool>, std::string::String, std::string::String, std::string::String)`

help: the following implementations were found:
        <(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, AH, AI, AJ, AK, AL) as diesel::Queryable<(SA, SB, SC, SD, SE, SF, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SP, SQ, SR, SS, ST, SU, SV, SW, SX, SY, SZ, SAA, SAB, SAC, SAD, SAE, SAF, SAG, SAH, SAI, SAJ, SAK, SAL), __DB>>
        <(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, AH, AI, AJ, AK, AL) as diesel::Queryable<diesel::sql_types::Record<(SA, SB, SC, SD, SE, SF, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SP, SQ, SR, SS, ST, SU, SV, SW, SX, SY, SZ, SAA, SAB, SAC, SAD, SAE, SAF, SAG, SAH, SAI, SAJ, SAK, SAL)>, diesel::pg::Pg>>
note: required because of the requirements on the impl of `diesel::Queryable<(diesel::sql_types::BigInt, diesel::sql_types::Text, diesel::sql_types::Text, diesel::sql_types::Timestamp, diesel::sql_types::Date, gametypes::rgb::RgbType, gametypes::rgb::RgbType, gametypes::rgb::RgbType, gametypes::rgb::RgbType, diesel::sql_types::SmallInt, diesel::sql_types::SmallInt, gametypes::position::PosType, diesel::sql_types::BigInt, diesel::sql_types::SmallInt, diesel::sql_types::BigInt, diesel::sql_types::BigInt, diesel::sql_types::SmallInt, diesel::sql_types::Array<diesel::sql_types::BigInt>, gametypes::enums::db_enum_impl_UserAccess::UserAccessMapping, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::BigInt>, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::Array<diesel::sql_types::BigInt>, diesel::sql_types::Nullable<diesel::sql_types::Text>, diesel::sql_types::SmallInt, diesel::sql_types::Array<diesel::sql_types::Bool>, gametypes::enums::db_enum_impl_Gods::GodsMapping, diesel::sql_types::Array<diesel::sql_types::SmallInt>, diesel::sql_types::SmallInt, gametypes::position::PosType, diesel::sql_types::Array<diesel::sql_types::Integer>, diesel::sql_types::BigInt, diesel::sql_types::Bool, diesel::sql_types::Bool, diesel::sql_types::Array<diesel::sql_types::Bool>, diesel::sql_types::Text, diesel::sql_types::Text, diesel::sql_types::Text), _>` for `sql::playerstruct::PGPlayerWithID`
note: required because of the requirements on the impl of `diesel::query_dsl::LoadQuery<_, sql::playerstruct::PGPlayerWithID>` for `diesel::query_builder::SelectStatement<sql::schema::players::table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<sql::schema::players::columns::uid, diesel::expression::bound::Bound<diesel::sql_types::BigInt, i64>>>, diesel::query_builder::order_clause::NoOrderClause, diesel::query_builder::limit_clause::LimitClause<diesel::expression::bound::Bound<diesel::sql_types::BigInt, i64>>>`

## Checklist

- [ x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2020-11-25 08:30
Likely a duplicate of #151 and #573. Unfortunately we cannot do much to improve at that front without support on rust language side for this. It is unfortunately not possible to emit custom error messages if some trait bounds are not satisfied. Working on the required language features to improve the error messages is clearly out of scope for me and additionally not something that should be tracked in diesels issue tracker. 
Closed because I cannot see how this is actionable for anyone without changing the language itself + we already have two issues to track improvements to our error messages. I should probably add that I'm certainly aware that the error messages are not perfect, but I just don't see any way to easily improve them. If someone comes up with an idea how to do this without changing the language or rewriting diesel completely feel free to drop a message here or in one of the linked issues.

**Closed by weiznich** 2020-11-25 08:30 UTC

**Comment by elycruz** [comment] 2022-06-11 05:31
@genusistimelord  Hi, what is the fix for the error you pointed out above (have got a similar error, with multiple versions of diesel and haven't been able to fix them, yet)?

**Comment by weiznich** [comment] 2022-06-11 06:40
@elycruz Our issue tracker is a tool for contributors to organize their work. Its not a discussion forum to ask for help. Please use the discussion part of this repository for such questions and please include the required context (relevant code, complete error message, used diesel version,...) in such questions.
