### ISSUE TITLE
Schema generation results in invalid decorators in 2.1

### ISSUE THREAD

**Issue by thomasmost** [diesel-rs/diesel#3692] opened 2023-07-13 20:05 UTC
### Versions

- **Rust:** 1.7.1
- **Diesel:** 2.1
- **Database:** MySQL
- **Operating System** MacOS

### Feature Flags

- **diesel:** ["mysql", "extras", "chrono", "r2d2"]

## Problem Description

Generating the table definitions for tables with both sql_renames of reserved words and max lengths results in a schema.rs file that won't compile

### What are you trying to accomplish?

generating a table with a migration like so creates an invalid table definition in `schema.rs`

```sql

CREATE TABLE `my_table` (
  `id` char(36) NOT NULL,
  `type` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
);

```

### What is the expected output?

```rust
diesel::table! {
    my_table (id) {
        #[max_length = 36]
        id -> Char,
        #[sql_name = "type"]
        #[max_length = 50]
        type_ -> Varchar,
    }
}
```

### What is the actual output?

```rust
diesel::table! {
    offsets_bill (id) {
        #[max_length = 36]
        id -> Char,
        #[sql_name = "type", max_length = 50]
        type_ -> Varchar,
    }
}
```

### Are you seeing any additional errors?

This causes

`Invalid `table!` syntax. Please see the `table!` macro docs for more info.`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-07-14 05:59
Duplicate of https://github.com/diesel-rs/diesel/pull/3681

**Closed by weiznich** 2023-07-14 05:59 UTC
Labels: bug
