### ISSUE TITLE
Missing -lmysqlclient

### ISSUE THREAD

**Issue by dcz-self** [diesel-rs/diesel#2798] opened 2021-05-31 12:27 UTC
Linking fails after compiling due to looking in the wrong place.

## Setup

Fedora 33. It installs mysqlclient into /usr/lib64/mysql:

```
$ pkg-config --libs mysqlclient
-L/usr/lib64/mysql -lmysqlclient
```

The linker command line as done by Cargo does not have "-L/usr/lib64/mysql", so it only looks in default directories, which seem not to include this path.

Building mysqlclient-sys actually works. Copying libmysqlclient.so into target/build/deps also works.

### Versions

- **Rust:** rust-1.52.1-1.fc33.x86_64
- **Diesel:** master, 1.4.6
- **Database:** community-mysql-devel-8.0.24-1.fc33.x86_64
- **Operating System** Fedora 33

## Problem Description

0. Install Fedora
1. Install deps including `dnf install 'pkgconfig(mysqlclient)'`
2. Check out Diesel v1.4.6
3. `cargo build --no-default-features --features sqlite`

### What is the expected output?

Success.

### What is the actual output?

```
error: could not compile `diesel_demo_step_3_mysql`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
[...]
  = note: /usr/bin/ld: cannot find -lmysqlclient
```

## Checklist

- I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can NOT be reproduced without requiring a third party crate (mysqlclient-sys)

**Comment by weiznich** [comment] 2021-05-31 12:35
Closed as this is a user configuration issue. Please don't use our issue tracker to ask questions about your environment. (Additionally this is a duplicate of quite a lot of existing issues)

**Closed by weiznich** 2021-05-31 12:35 UTC
Labels: bug

**Comment by dcz-self** [comment] 2021-05-31 13:04
I'm not sure what made you think that it's a question about my environment... Please read the following line:

> The linker command line as done by Cargo does not have "-L/usr/lib64/mysql"

This is something that should be resolved by pkgconfig, and indeed it gets resolved by other (Rust but not only) libraries correctly, but not by diesel.

I wasn't able to find another issue with the same problem, so again I'm not sure what you're referring to.

**Comment by weiznich** [comment] 2021-05-31 13:24
> I'm not sure what made you think that it's a question about my environment... Please read the following line:

The issue template is quite clear about this: If you get a linker error complaining about a missing library you should not fill a new issue here. First have a look at existing issue and if that does not help ask for help in the gitter channel or our forum. If it turns out to be a actual issue we can always fill an issue afterwards, but in my experience that's almost never the case. If you really feel that this is a genuine issue I expect that you explain that in detail, with references to existing issues and explanation why this is different. And no: "This happens on distro xyz" is not enough detail.

On top of that your steps to reproduce this problem do not match the error message you've provided. Again that's a minimal requirement for an issue to be valid.

> This is something that should be resolved by pkgconfig, and indeed it gets resolved by other (Rust but not only) libraries correctly, but not by diesel.

It's correct that this should be solved by `pkgconfig`, so mind explaining why you believe that this is a diesel issue and not a broken `pkgconfig` for `libmysqlclient` in your distribution? In fact we test this as part of our CI on ubuntu via `pkgconfig`. It work there, so please provide evidence that this is not a problem with your environment.

> I wasn't able to find another issue with the same problem, so again I'm not sure what you're referring to.

[Here you go](https://github.com/diesel-rs/diesel/issues?q=is%3Aissue+cannot+find+-lmysqlclient). If you believe all that issues are not the same problem you need to explain why this is the case. Again: Just because it's a different operating system it does not mean it's a different issue.

This is my last comment here, at least I see some evidence that this is an actual issue. If you want to get help just use one of the existing support forums listed above.

**Comment by dcz-self** [comment] 2021-05-31 13:50
> The issue template is quite clear about this
> First have a look at existing issue and if that does not help ask for help in the gitter channel or our forum.

Sadly, it's not clear at all. The new issue page has a piece that reminds to look in the issue list:

> Failed to compile diesel? Have a look at existing issues. You've likely miss some required dependency.

However the bug template doesn't mention missing deps or linking at all. Perhaps that needs correction.

> your steps to reproduce this problem do not match the error message you've provided

If you mean that the feature flag specifies that mysql should not be compiled, I'm as puzzled as you are. I assure you that this is the command I used though.

> mind explaining why you believe that this is a diesel issue and not a broken pkgconfig for libmysqlclient in your distribution

The path returned by pkgconfig matches the directory where the .so is found, which is enough for CMake for example. When building an empty program against mysqlclient-sys, there is a difference in `cargo build` output:

```
mysqlclient-sys]$ cargo build -vv
[...]
     Running `CARGO=/usr/bin/cargo [...] LD_LIBRARY_PATH='[...]/mysqlclient-sys/target/debug/deps:/usr/lib'  [...] -L native=/usr/lib64/mysql`
```

```
diesel]$ cargo build -vv
[...]
     Running `CARGO=/usr/bin/cargo [...] LD_LIBRARY_PATH='[...]/diesel/target/debug/deps:/usr/lib' [...]`
```

Note the lack of /usr/lib64/mysql in the second call.

> If you believe all that issues are not the same problem you need to explain why this is the case.

If you believe you made your point by linking to no issue in particular, you have to accept that I'm not going to address any of those in particular. I'm not acting in bad faith here, and I'm not trying to waste anyone's time. I already took the effort to debug this for a project I don't even care about that much.

> the gitter channel or our forum

I'd love to try, but https://diesel.rs doesn't make any mention of them that I could find. Perhaps another thing that could make your life easier.

**Comment by weiznich** [comment] 2021-05-31 14:02
> When building an empty program against mysqlclient-sys, there is a difference in cargo build output:

Diesel does not do any configuration on it's own here, but rather relies on `mysqlclient-sys` for this, so this indicates that something is very wrong for you. Maybe you could provide a complete step by step command list on how to reproduce this, that includes information like in which directory you've executed what command and so on.

> I'd love to try, but https://diesel.rs doesn't make any mention of them that I could find. Perhaps another thing that could make your life easier.

Both are mentioned in issue list. Additionally the gitter channel is mentioned in our API documentation and our readme. The Forum is just there on as part of the github repository. 
That written I'm fine to add this to the web page as well. Mind opening a PR [here](https://github.com/sgrif/diesel.rs-website/)?

**Comment by dcz-self** [comment] 2021-05-31 14:07
> Maybe you could provide a complete step by step command list

Is a Docker container acceptable?

**Comment by weiznich** [comment] 2021-05-31 14:09
> Is a Docker container acceptable?

That would be great

**Comment by dcz-self** [comment] 2021-06-02 20:19
After removing the `target` directory, the issue no longer appears. I think it could be a bug in Cargo instead, maybe related to caching pkg-config results. Thanks for taking the time to reply.

**Comment by weiznich** [comment] 2021-06-03 06:58
@dcz-self Thanks for coming back to add this information :+1:
