### ISSUE TITLE
!table fails for tables with more than 32 columns

### ISSUE THREAD

**Issue by MerlinDE** [diesel-rs/diesel#2387] opened 2020-05-07 17:30 UTC
### Versions

- **Rust:** 1.43.0
- **Diesel:** 1.4.4
- **Database:** Postgres 12.2_1
- **Operating System** macOS 10.15.4 

### Feature Flags

- **diesel:** postgres

## Problem Description
The !table macro is not able to handle tables with more than 32 columns.

### What are you trying to accomplish?
Create and connect to a schema with 32+ columns.

### What is the expected output?
A successful build. ;) 

### What is the actual output?
```
error[E0277]: the trait bound `(schema::posts::columns::id, schema::posts::columns::element02, schema::posts::columns::element03, schema::posts::columns::element04, schema::posts::columns::element05, schema::posts::columns::element06, schema::posts::columns::element07, schema::posts::columns::element08, schema::posts::columns::element09, schema::posts::columns::element10, schema::posts::columns::element11, schema::posts::columns::element12, schema::posts::columns::element13, schema::posts::columns::element14, schema::posts::columns::element15, schema::posts::columns::element16, schema::posts::columns::element17, schema::posts::columns::element18, schema::posts::columns::element19, schema::posts::columns::element20, schema::posts::columns::element21, schema::posts::columns::element22, schema::posts::columns::element23, schema::posts::columns::element24, schema::posts::columns::element25, schema::posts::columns::element26, schema::posts::columns::element27, schema::posts::columns::element28, schema::posts::columns::element29, schema::posts::columns::element30, schema::posts::columns::element31, schema::posts::columns::element32, schema::posts::columns::element33): diesel::Expression` is not satisfied
  --> src/schema.rs:1:1
   |
1  | / table! {
2  | |     posts (id) {
3  | |         id -> Int4,
4  | |         element02 -> Nullable<Varchar>,
...  |
36 | |     }
37 | | }
   | |_^ the trait `diesel::Expression` is not implemented for `(schema::posts::columns::id, schema::posts::columns::element02, schema::posts::columns::element03, schema::posts::columns::element04, schema::posts::columns::element05, schema::posts::columns::element06, schema::posts::columns::element07, schema::posts::columns::element08, schema::posts::columns::element09, schema::posts::columns::element10, schema::posts::columns::element11, schema::posts::columns::element12, schema::posts::columns::element13, schema::posts::columns::element14, schema::posts::columns::element15, schema::posts::columns::element16, schema::posts::columns::element17, schema::posts::columns::element18, schema::posts::columns::element19, schema::posts::columns::element20, schema::posts::columns::element21, schema::posts::columns::element22, schema::posts::columns::element23, schema::posts::columns::element24, schema::posts::columns::element25, schema::posts::columns::element26, schema::posts::columns::element27, schema::posts::columns::element28, schema::posts::columns::element29, schema::posts::columns::element30, schema::posts::columns::element31, schema::posts::columns::element32, schema::posts::columns::element33)`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Are you seeing any additional errors?
./.

### Steps to reproduce

1. Take the example from diesel.rs: http://diesel.rs/guides/getting-started/
2. Alter migrations/up.sql to generate a table with 33 columns:
```sql 
CREATE TABLE posts
(
    id                 SERIAL PRIMARY KEY,
    element02          VARCHAR,
    element03          VARCHAR,
    element04          VARCHAR,
    element05          VARCHAR,
    element06          VARCHAR,
    element07          VARCHAR,
    element08          VARCHAR,
    element09          VARCHAR,
    element10          VARCHAR,
    element11          VARCHAR,
    element12          VARCHAR,
    element13          VARCHAR,
    element14          VARCHAR,
    element15          VARCHAR,
    element16          VARCHAR,
    element17          VARCHAR,
    element18          VARCHAR,
    element19          VARCHAR,
    element20          VARCHAR,
    element21          VARCHAR,
    element22          VARCHAR,
    element23          VARCHAR,
    element24          VARCHAR,
    element25          VARCHAR,
    element26          VARCHAR,
    element27          VARCHAR,
    element28          VARCHAR,
    element29          VARCHAR,
    element30          VARCHAR,
    element31          VARCHAR,
    element32          VARCHAR,
    element33          VARCHAR
)
```
3. Build. Or, if your IDE already builds in the background, have a look at schema.rs, where the !table macro fails.

4. Remove __element33__ from __up.sql__, run ```diesel migration redo```. Error is gone.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2020-05-07 18:44
Duplicate of #2129

**Closed** 2020-05-07 18:44 UTC
