### ISSUE TITLE
Failed with: schema does not exist

### ISSUE THREAD

**Issue by NikosEfthias** [diesel-rs/diesel#2899] opened 2021-09-15 23:28 UTC
## Setup
`cargo create diesel_demo`

### Versions

- **Rust:** `1.55`
- **Diesel:** `1.4.1`
- **Database:** `postgresql`
- **Operating System** `arch linux`

### Feature Flags

- **diesel:**  `postgres`

## Problem Description
According to the getting started guide running the following sequence should work

- `diesel setup`
- `diesel migration generate users`
- fill up and down SQL files
- `diesel run`
at this point I get shema users does not exist error

### What are you trying to accomplish?
create a table

### What is the expected output?
successful creation

### What is the actual output?
Failed with: schema "users" does not exist

### Are you seeing any additional errors?
no

## Checklist

- [ x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-09-16 06:55
The examples in the getting started guide are tested by our CI, so it's really unlikely that the just not work. It's likely a user error on your side. That written given the "details" you listed in your issue it's impossible to tell what went wrong as there is essentially no information in this bug report. 

Closed as cannot reproduce.

As an additional note: Our issue tracker is no support forum, use the discussions forum or the gitter channel to ask questions.

**Closed by weiznich** 2021-09-16 06:55 UTC
Labels: bug
