### ISSUE TITLE
queryable macro not found

### ISSUE THREAD

**Issue by SephVelut** [diesel-rs/diesel#2855] opened 2021-08-16 13:54 UTC
```rust
#[macro_use]
extern crate diesel;

use diesel::prelude::*;
use diesel::Queryable;

#[derive(Queryable)]
struct A {
   q: u32
}
```

`error: cannot find derive macro 'Queryable' in this scope`

```rust
use diesel::deserialize::Queryable;
```
`unresolved import 'diesel::deserialize'`

`rust version 1.56 nightly`
`diesel 0.15.2`

**Comment by weiznich** [comment] 2021-08-16 13:58
Our issue tracker is not a support forum but a tool for contributors to track bugs and issues. Additionally the issue template is mandatory.

Closed as this issue does not follow the template + I really sure that this is not a bug in diesel (It's working on all systems I have access to).

**Closed by weiznich** 2021-08-16 13:58 UTC
Labels: bug
