### ISSUE TITLE
`dyld[...]: missing symbol called` while running `diesel setup` on mac os silicon

### ISSUE THREAD

**Issue by dhruvja** [diesel-rs/diesel#3667] opened 2023-06-27 19:45 UTC
### Versions

- **Rust:** 1.69.0 (84c898d65 2023-04-16)
- **Diesel:** 2.1.0
- **Database:** postgres
- **Operating System** Mac OS Silicon

### Feature Flags

- **diesel:**

## Problem Description

I installed diesel_cli using the command below:
```
cargo install diesel_cli
```
When i try to run `diesel setup` or `diesel migration run` , i get the following error:
```
dyld[40122]: missing symbol called
zsh: abort      diesel setup
```

I also tried switching to arch to i386 ( rosetta ) from arm64 .

I have observed that the diesel package is not able to communicate with the postgresql server.

### What are you trying to accomplish?

I am trying to connect to the local postgresql database and run migrations.

### What is the expected output?

Successfully setup the database ( create table if not created ) run the migrations.

### What is the actual output?
The below is for `diesel setup`
```
dyld[40122]: missing symbol called
zsh: abort      diesel setup
```

The below is for `diesel migration run`
```
dyld[40273]: missing symbol called
zsh: abort      diesel migration run
```

### Are you seeing any additional errors?

No

### Steps to reproduce

- Install diesel cli using `cargo install diesel_cli` or if you dont have mysql you can install using `cargo install diesel_cli --no-default-features --features postgres  `.
- add the database url in env file and run `diesel setup`

It will fail in this step 2

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-07-20 16:13
The error message seems to indicate some issue with some dependency. It's unclear which dependency or how to reproduce that outside your environment. Speaking from my gut feeling: I would probably check if I have a compatible libpq version for my current compilation target and if all dependencies of libpq are installed and configured correctly.

I'm closing this as environment issue, which is not a bug in diesel.

**Closed by weiznich** 2023-07-20 16:13 UTC
Labels: bug
