### ISSUE TITLE
Cannot use multiple table_name for Insertable when also deriving Queryable

### ISSUE THREAD

**Issue by Mossop** [diesel-rs/diesel#3912] opened 2024-01-23 09:30 UTC
### Versions

- **Rust: 1.75.0**
- **Diesel: 2.1.4**
- **Database: N/A**
- **Operating System; macOS**

### Feature Flags

- **diesel: default**

## Problem Description

#3535 added support for multiple `table_name` attributes when deriving `Insertable` but this breaks if you also attempt to derive `Queryable`.

### What are you trying to accomplish?

I have two tables which share a common subset of columns so in my structs I want to split those columns into their own struct as it will allow me to share some behaviours. To do this I make all the structs derive `Insertable` and on the split out struct I set multiple `table_name` attributes and use the `embed` attribute. But I also want to be able to query these by making the structs `Queryable` (I have to manually list the columns rather than using `all_columns` but some macros take care of that) and as soon as I do the code fails to compile.

### What is the expected output?

The code should compile.

### What is the actual output?

`error: expected a single table name attribute`

### Are you seeing any additional errors?

No

### Steps to reproduce

The error reproduces with this simple file:

```rust
use diesel::{Insertable, Queryable};

diesel::table! {
    user1 (id) {
        id -> Varchar,
        name -> Text,
    }
}

diesel::table! {
    user2 (id) {
        id -> Varchar,
        name -> Text,
    }
}

#[derive(Queryable, Insertable)]
#[diesel(table_name = user1, table_name = user2)]
pub struct User {
    id: String,
    name: String,
}
```
## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2024-01-23 11:23
That's a duplicate of https://github.com/diesel-rs/diesel/pull/3782.

**Closed by weiznich** 2024-01-23 11:23 UTC
Labels: bug
