### ISSUE TITLE
Failed with: entity not found

### ISSUE THREAD

**Issue by llxxbb** [diesel-rs/diesel#2053] opened 2019-04-27 02:18 UTC
### Versions

- **Rust:1.36 nightly**
- **Diesel:1.4.2**
- **Database:sqlite**
- **win 10**

### Feature Flags

- **diesel:mysql sqlite**

## Problem Description
I'm using diesel_cil to run "migration run" cmd with "--migration-dir my_dir" argument. but I got : Failed with: entity not found. The "my_dir" was generated by diesel and it is only include it's own name and no parents dir info.
I run diesel under the rust root dir, and other migration subcommand are ok, such redo.

### What is the expected output?
because i use mysql and sqlite together. I want run migration any one of them alternatively.

### What is the actual output?
Failed with: entity not found

### Are you seeing any additional errors?
No

**Comment by sgrif** [comment] 2019-05-03 23:38
Can you provide more steps to reproduce your issue? What is the contents of the `my_dir` directory?

**Comment by llxxbb** [comment] 2019-05-04 06:55
In my project root directory, it has  "migrations" sub directory.
In migrations directory, it has 2019-04-27-024605_mysql sub directory
In 2019-04-27-024605_mysql directory, it has up.sql and down.sql.
"2019-04-27-024605_mysql" is `my_dir`

To reproduce the issue:
1: cd to my project's root directory.
2: run cmd:
    diesel migration run --migration-dir 2019-04-27-024605_mysql 
then got the error: Failed with: entity not found

**Comment by pietroalbini** [comment] 2019-06-23 17:47
@sgrif I have a consistent repro for this issue:

```
$ git clone https://github.com/rust-lang-nursery/discord-mods-bot
$ git checkout diesel-2053-repro
$ docker build -t diesel-2053-repro .
$ docker run -e "DISCORD_TOKEN=" -e "DATABASE_URL=/opt/bot/tags.db" -v "/tmp/bot:/opt/bot" --rm -it diesel-2053-repro
```

cc @technetos

**Comment by pietroalbini** [comment] 2019-06-23 20:59
Well, turns out the migrations dir didn't actually exist inside the container. I'm pretty sure this is just a "directory not found" error.

**Comment by weiznich** [comment] 2021-01-26 17:01
Closed as this seems to be a user error. We could probably try to improve the error message here a bit.

**Closed by weiznich** 2021-01-26 17:01 UTC
