### ISSUE TITLE
impl SupportsReturningClause for Sqlite

### ISSUE THREAD

**Issue by toxeus** [diesel-rs/diesel#2722] opened 2021-04-13 11:31 UTC
## Problem Description

`SupportsReturningClause` is not implemented for `Sqlite` but according to its documentation the returning clause *is* supported:
https://www.sqlite.org/lang_returning.html

### What are you trying to accomplish?

I'd like to use the returning clause with Sqlite.

### What is the expected output?

No compiler errors. 

### What is the actual output?

This: https://github.com/diesel-rs/diesel/blob/master/diesel_compile_tests/tests/fail/delete_statement_does_not_support_returning_methods_on_sqlite.stderr

### Are you seeing any additional errors?

No.

### Steps to reproduce

Run this test: https://github.com/diesel-rs/diesel/blob/master/diesel_compile_tests/tests/fail/delete_statement_does_not_support_returning_methods_on_sqlite.rs

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-04-13 12:15
Duplicate of https://github.com/diesel-rs/diesel/discussions/2684

**Closed by weiznich** 2021-04-13 12:15 UTC
Labels: bug
