### ISSUE TITLE
 Unable to install the diesel cli on windows ,LINK : fatal error LNK1181: cannot open input file 'libpq.lib'

### ISSUE THREAD

**Issue by gmpravin** [diesel-rs/diesel#2343] opened 2020-03-30 04:28 UTC
- **Rust:*cargo 1.44.0-nightly (7019b3ed3 2020-03-17)*
- **Diesel:*1.4.2*
- **Database:*postgres*
- **Operating System*Windows 10*
![Capture](https://user-images.githubusercontent.com/40927922/77875152-db547080-726c-11ea-94a7-c626f52cfa56.PNG)

D:\rust\rocket-restapi>cargo install diesel_cli --no-default-features --features "postgres"
    Updating crates.io index
  Installing diesel_cli v1.4.0
   Compiling proc-macro2 v1.0.9
   Compiling unicode-xid v0.2.0
   Compiling winapi v0.3.8
   Compiling syn v1.0.17
   Compiling libc v0.2.68
   Compiling cfg-if v0.1.10
   Compiling autocfg v1.0.0
   Compiling getrandom v0.1.14
   Compiling cc v1.0.50
   Compiling bitflags v1.2.1
   Compiling vcpkg v0.2.8
   Compiling memchr v2.3.3
   Compiling unicode-xid v0.0.4
   Compiling byteorder v1.3.4
   Compiling rustc-demangle v0.1.16
   Compiling lazy_static v1.4.0
   Compiling serde v1.0.105
   Compiling smallvec v1.2.0
   Compiling matches v0.1.8
   Compiling ppv-lite86 v0.2.6
   Compiling ucd-util v0.1.8
   Compiling regex v0.2.11
   Compiling quote v0.3.15
   Compiling utf8-ranges v1.0.4
   Compiling unicode-width v0.1.7
   Compiling vec_map v0.8.1
   Compiling percent-encoding v1.0.1
   Compiling strsim v0.8.0
   Compiling synom v0.11.3
   Compiling num-traits v0.2.11
   Compiling num-integer v0.1.42
   Compiling thread_local v0.3.6
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.12
   Compiling regex-syntax v0.5.6
   Compiling pq-sys v0.4.6
   Compiling textwrap v0.11.0
   Compiling syn v0.11.11
   Compiling idna v0.1.5
   Compiling backtrace-sys v0.1.35
   Compiling quote v1.0.3
   Compiling rand_core v0.5.1
   Compiling aho-corasick v0.6.10
   Compiling remove_dir_all v0.5.2
   Compiling time v0.1.42
   Compiling atty v0.2.14
   Compiling url v1.7.2
   Compiling rand_chacha v0.2.2
   Compiling clap v2.33.0
   Compiling rand v0.7.3
   Compiling chrono v0.4.11
   Compiling derive-error-chain v0.10.1
   Compiling backtrace v0.3.46
   Compiling tempfile v3.1.0
   Compiling error-chain v0.10.0
   Compiling dotenv v0.10.1
   Compiling serde_derive v1.0.105
   Compiling diesel_derives v1.4.1
   Compiling diesel v1.4.4
   Compiling migrations_internals v1.4.1
   Compiling toml v0.4.10
   Compiling diesel_cli v1.4.0
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "D:\\vs build\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.0.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.1.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.10.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.11.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.12.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.13.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.14.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.15.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.2.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.3.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.4.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.5.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.6.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.7.rcgu.o"
"C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.8.rcgu.o" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.diesel.6m70sz3g-cgu.9.rcgu.o" "/OUT:C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.exe" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\diesel-19a0de9e144fb8f3.2r6gthmwj9awkrpp.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps" "/LIBPATH:C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\liburl-7751ea81756cca33.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libpercent_encoding-299544bff6fcc678.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libidna-0c3da4a6f2cc73f3.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libunicode_normalization-f9014212f5044990.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libsmallvec-456a3245f45f3d1b.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libunicode_bidi-186b2c2e96de4fc7.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libmatches-d9f595751d88fbd9.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libtoml-8dd13def083ff295.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libtempfile-6674f2d3e1692b56.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\librand-e6bf32ed05658c3b.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\librand_chacha-e99fcc8172e7f111.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libppv_lite86-a3be291abbbe5891.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\librand_core-2709b296a54fb7e3.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libgetrandom-561fd8841cf0d424.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libremove_dir_all-8f6928e503e04ce4.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libserde-de3de337b41b1ad6.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libmigrations_internals-5d934790dcff17b0.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libdotenv-61840ca6028ebb27.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libregex-90a73ffb6da0cff8.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libutf8_ranges-6f9fc8cb3ea86764.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libregex_syntax-6d8612b3f6532663.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libucd_util-a1f4befcfe2f8298.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libthread_local-19799ca01b1e76fb.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\liblazy_static-c8e0354ab3ea6508.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libaho_corasick-1f4da092129228c3.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libmemchr-69c189c2afae22a3.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\liberror_chain-9e0d1362bea1c5ca.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libbacktrace-d174e7abf108f699.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libcfg_if-969e7b1b1703414c.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\librustc_demangle-f4219de82b8c4434.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libdiesel-7fd012944bc26d06.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libpq_sys-e9ebfde16f4c2f52.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libbyteorder-b584bcd3fad24b10.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libclap-9135d894f9bbb42d.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libvec_map-47288ef5053c1c52.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libtextwrap-55680f81a29dd1a9.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libunicode_width-31a2b2df8f01a13d.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libstrsim-858e7c268877597d.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libbitflags-4144eb85c84d5762.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libatty-af75d3621c4b73c2.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libchrono-4f37c915ced9ee5c.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libnum_integer-ea3c49943369a662.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libnum_traits-7b3453c6282b874a.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libtime-465a8e533c119b17.rlib" "C:\\Users\\elcot\\AppData\\Local\\Temp\\cargo-installvIobSh\\release\\deps\\libwinapi-f8fd54014298794e.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-fae0adc6a4bf13fc.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-a7b685aa806e9051.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-959d4337805b4823.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-793090c0698ed48d.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libbacktrace-0b2ee9875ceef572.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-512b5012620b8d24.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-fd322e9a5f11a20b.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-ddd2bba294770bdf.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-9eacc70b3ac746bf.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-2605391ad035cd8d.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-e30d182074a5a412.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-83168dc81ba47b29.rlib" "C:\\Users\\elcot\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-2c5b191d679853a8.rlib" "advapi32.lib" "libpq.lib" "advapi32.lib" "cfgmgr32.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "opengl32.lib" "user32.lib" "winspool.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1181: cannot open input file 'libpq.lib'

error: aborting due to previous error

error: failed to compile `diesel_cli v1.4.0`, intermediate artifacts can be found at `C:\Users\elcot\AppData\Local\Temp\cargo-installvIobSh`

Caused by:
  could not compile `diesel_cli`.

To learn more, run the command again with --verbose.

NOTE: Im already installed visual C++ build tools , and rust file correctly compiles

**Comment by weiznich** [comment] 2020-03-30 06:07
Duplicate of #587.

**Closed** 2020-03-30 06:07 UTC

**Comment by gmpravin** [comment] 2020-03-31 12:28
Yesterday I fixed the problem, after restarting my system
Thanks for helping😀
