### ISSUE TITLE
Support user-defined `FromSql` and `ToSql` implementations

### ISSUE THREAD

**Issue by kardeiz** [diesel-rs/diesel#348] opened 2016-06-01 21:42 UTC
It would be nice if it were easier to write one's own `FromSql` and `ToSql` implementations.

In my understanding (I could be wrong), this is actually possible&mdash;all the required traits, etc. are public&mdash;but all of the traits implemented by the `expression_impls` and `queryable_impls` macros have to be written by hand, because these macros are not publicly exposed.

Would it be possible to export these macros as well, or provide some other functionality to facilitate these conversions?

**Comment by jimmycuadra** [comment] 2016-08-17 09:32
I'm also wondering this. In my case, I want to use a custom type in a table struct that Diesel should treat as a String for all intents and purposes. It's not clear to me how to achieve this. I started out by trying to just implement ToSql for my type, but it seems like there is a rabbit hole of traits that need to be satisfied, cause I get errors like "diesel::Expression is not satisfied" and "diesel::Expression:NonAggregate is not satisfied."

**Comment by leoschwarz** [comment] 2017-05-08 19:07
I have the same problem right now, apparently the situation has still not improved by much or I'm not able to find the relevant modules.

(Also I think this and #162 are essentially duplicates.)

**Comment by sgrif** [comment] 2017-12-16 19:43
Closing as a duplicate of #162.

**Closed by sgrif** 2017-12-16 19:43 UTC
