### ISSUE TITLE
Error: prepared statement "__diesel_stmt_0" already exists

### ISSUE THREAD

**Issue by tpkee** [diesel-rs/diesel#3644] opened 2023-05-27 11:00 UTC
### Versions

- **Rust:** 1.69.0
- **Diesel:**2.1.0
- **Database:** Postgresql 15.2
- **Operating System**  Linux 6.3.4

### Feature Flags

- **diesel:** diesel migration run/redo --databse-url

## Problem Description
I get an error about prepared statements whenever I run a migration with `diesel migration run --database-url="blabla"`.
When I executed the command the first time it worked as expected (except for an error on my part), but when I tried to redo the migration(s) it outputted `Error: prepared statement "__diesel_stmt_0" already exists`

### What are you trying to accomplish?
Run and redo migrations

### What is the expected output?
Migrations are executed correctly

### What is the actual output?
Error: prepared statement "__diesel_stmt_0" already exists

### Are you seeing any additional errors?
No

### Steps to reproduce

- Execute `diesel migration run --database-url=""` a first time;
- Execute `diesel migration redo --database-url=""`;

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [X] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-05-28 10:05
Duplicate of https://github.com/diesel-rs/diesel/issues/1028
That's likely caused by using pgbouncer (or a similar tool) which does not support prepared statements correctly. It's not a issue in diesel but a problem with your setup.

**Closed by weiznich** 2023-05-28 10:05 UTC
Labels: bug

**Comment by omarabid** [comment] 2024-08-16 12:28
To downvoters of @weiznich: If you are using Supabase, makes sure to select the Session mode port (5432) instead of the Transaction mode (6543); that will likely solve your problem.

**Comment by manuelarte** [comment] 2024-08-27 21:29
@omarabid thanks!
