### ISSUE TITLE
Impossible to have multiple foreign keys referencing same table from single table

### ISSUE THREAD

**Issue by thecooldrop** [diesel-rs/diesel#2613] opened 2020-12-30 23:16 UTC
### Versions

- Rust version 1.4.8
- Diesel version 1.4.4 with "postgres" feature

## Problem Description
I am trying to create a struct which references the same table twice. The purpose of this is to create a kind of hierarchy of categories. Here is what I am trying to do for following tables:

```sql
create table product_category_rollup(
    id serial primary key,
    upper_category_id integer not null,
    lower_category_id integer not null,
    foreign key (upper_category_id) references product_category(id),
    foreign key (lower_category_id) references product_category(id)
);

create table product_category(
    id serial primary key,
    name varchar unique not null
);
```

I am trying to create the matching structs as in :

```rust
#[derive(Identifiable, Queryable)]
#[table_name = "product_category"]
pub struct ProductCategory {
    id: i32,
    name: String,
}

#[derive(Queryable, Identifiable, Associations)]
#[belongs_to(ProductCategory, foreign_key="upper_category_id")]
#[belongs_to(ProductCategory, foreign_key="lower_category_id")]
#[table_name = "product_category_rollup"]
pub struct ProductCategoryRollup {
    id: i32,
    upper_category_id: i32,
    lower_category_id: i32,
}

```

And I am getting the following error:

```rust
error[E0119]: conflicting implementations of trait `diesel::associations::BelongsTo<entities::ProductCategory>` for type `entities::ProductCategoryRollup`:
  --> src/entities.rs:29:35
   |
29 | #[derive(Queryable, Identifiable, Associations)]
   |                                   ^^^^^^^^^^^^
   |                                   |
   |                                   first implementation here
   |                                   conflicting implementation for `entities::ProductCategoryRollup`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

In short currently it seems impossible to have a table which contains multiple non-composite foreign-keys into some other table. How would one go about achieving such behavior currently?

Related SO Question : https://stackoverflow.com/questions/65514581/multiple-foreign-keys-referencing-same-table-in-diesel

**Comment by thecooldrop** [comment] 2020-12-31 12:39
Hi @TaKO8Ki , this is not necessarily related to postgres, but rather to the way in which foreign keys are handled, thus I find the label "postgres" not quite suitabe, do you happen to have a label like "feature request" or similar?

**Comment by TaKO8Ki** [comment] 2020-12-31 12:51
@thecooldrop 
I'm sorry. I only skimmed through this issue briefly, and I added a wrong label.

**Comment by thecooldrop** [comment] 2021-01-02 20:41
So @TaKO8Ki I have been familiarizing myself with the `BelongsTo<Parent>` trait and the implementations which are generated by derives of this trait. So here is what I have found up to now. The `BelongsTo<Parent>` trait is defined as : 

```rust
pub trait BelongsTo<Parent> {
    type ForeignKey: Hash + ::std::cmp::Eq;
    type ForeignKeyColumn: Column;

    fn foreign_key(&self) -> Option<&Self::ForeignKey>;
    fn foreign_key_column() -> Self::ForeignKeyColumn;
}
```

Now this means that for each type implementing the trait we can have one and only associated foreign key column. Namely the associated type enforces that for `Self` implementing the `BelongsTo<Parent>` trait there exists a one and only type representing the `ForeignKeyColumn` ( this is all wonderfully explained in the accepted answer to SO question [of when to use associated types instead of type parameters](https://stackoverflow.com/questions/32059370/when-is-it-appropriate-to-use-an-associated-type-versus-a-generic-type) ).

Now as we all know relational databases admit table ( say table `A` ) having primary keys `a,b,c...` referencing the primary key of some other table B.

My proposal here would be to adapt the `BelongsTo<Parent>` trait so that it is defined more like following: 

```rust
pub trait BelongsTo<Parent, ForeignKeyColumn: Column> {
    type ForeignKey: Hash + ::std::cmp::Eq;

    fn foreign_key(&self) -> Option<&Self::ForeignKey>;
    fn foreign_key_column() -> ForeignKeyColumn;
}
```


and this would enable us to have multiple foreign keys referencing the same table, and thus potentially unlocking more powers for Diesel.

Now I would hope for all of this to remain invisible to end-users relying on derives, since we could just adapt the derives so that associated type is replaced by type parameters. Still this would be a breaking change for users implementing the trait by hand.

Lastly, a question from me. Would this be something that would be of interest to maintainers, and if yes I would gladly offer myself to implement this.

**Comment by weiznich** [comment] 2021-01-04 09:13
Duplicate of #2142

**Closed by weiznich** 2021-01-04 09:13 UTC

**Comment by thecooldrop** [comment] 2021-01-04 09:22
@weiznich I know that this is closed, but given my understanding of the other issue you have linked I have come to following conclusion. The BelongsTo type of relationship here is not the way it is meant to be used, and such self-referential relationships should not be handled with BelongsTo, but rather with explicit joins?

**Comment by weiznich** [comment] 2021-01-04 09:33
It's totally fine to use `#[derive(Associations)]` with a self referential relation ship. The point is that we don't support having more than one relation ship to the same table (regardless if it's self referential or not) as we cannot know what you would mean by writing `Table1::belonging_to(elements)` afterwards. Introducing another column parameter there is not really meaningful as the query then would be as large as just writing out what is generated by this function.

**Comment by Mohsinsiddi** [comment] 2023-02-04 08:02
I also stuck with this issue. I hope I will find the answer soon

**Comment by weiznich** [comment] 2023-02-04 17:17
@Mohsinsiddi Your issue tracker is no support forum. Please stop posting to old issues if you cannot add something substantial to the discussion.

**Comment by Mohsinsiddi** [comment] 2023-02-07 17:30
Anyone wanted to see how we can do the above task, they can follow my work, I took it few days

https://github.com/Mohsinsiddi/diesel-rocket-rust-backend

I hope I am adding some values here and will help most of the devs out there to make such thing helpful for others @weiznich

**Comment by JonasMS** [comment] 2023-04-16 15:44
> It's totally fine to use `#[derive(Associations)]` with a self referential relation ship. The point is that we don't support having more than one relation ship to the same table (regardless if it's self referential or not) as we cannot know what you would mean by writing `Table1::belonging_to(elements)` afterwards. Introducing another column parameter there is not really meaningful as the query then would be as large as just writing out what is generated by this function.

I think I understand your comment here. Are you saying that in order for `Table::belonging_to(elements)` to know what to do when there's 1+n associations to another table is to specify the column name? And that doing so isn't any simpler than other means that already exist? Those other means being using joins?

**Comment by cloneable** [comment] 2024-01-21 16:20
Hi, first-time user of Diesel here and having a lot of fun with it, but ran into this too. It's not that common to have in the schema, but when trying to define DAGs this can come up quickly, like an edge belongs to two nodes.

I understand Diesel is a well-designed system of generated types and extension traits, so it's not easy to simply add a generic parameter here or there. We now have stable const generics, though, and I wonder if this could be more easily done by making `BelongsTo` additionally generic over some `const N: usize`, so that a type can implement `BelongsTo<Node, 0>` and `BelongsTo<Node, 1>`. Just an idea.
