### ISSUE TITLE
Generated schema contains unrenamed colliding column names

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#2090] opened 2019-06-13 12:48 UTC
I'm using the latest master of diesel and diesel_cli. 
After https://github.com/diesel-rs/diesel/pull/1897 was merged, the generated schema causes compilation errors for me, such as:
```
error: expected identifier, found keyword `type`
    --> database/src/schema/gen.rs:1489:50
     |
1489 |     joinable!(user_tokens -> user_token_types (type));
     |                                                  ^^^^ expected identifier, found keyword
help: you can escape reserved keywords to use them as identifiers
     |
1489 |     joinable!(user_tokens -> user_token_types (r#type));
```
I have to manually change the generated schema to this, to make it compile:
```rust
joinable!(user_tokens -> user_token_types (type_));
```
(In the db, the column is named `type`.)

**Comment by weiznich** [comment] 2021-01-27 09:32
As #1897 contains a [test case for exactly this case](https://github.com/diesel-rs/diesel/pull/1897/files#diff-1cf474c9f3bbf797f3d9d0791f0dd69dcb62a461f563dff7fb97e4cb87b564e6) I would like to see a reproducing example for this otherwise I consider this fixed.

**Comment by weiznich** [comment] 2021-06-16 07:22
Closed as we cannot reproduce that without details + the corresponding PR contains a test case for exactly the mentioned scenario.

**Closed by weiznich** 2021-06-16 07:22 UTC
Labels: cli, missing reproduction steps
