### ISSUE TITLE
Can't use `into_boxed` after union

### ISSUE THREAD

**Issue by maksalees** [diesel-rs/diesel#3871] opened 2023-12-10 12:36 UTC
### Versions

- **Rust:** 1.73.0
- **Diesel:** 2.1.0
- **Database:** PostgreSQL 15
- **Operating System:** NixOS

### Feature Flags

- **diesel:** postgres, url, without-deprecated, serde_json, chrono, nightly-error-messages

## Problem Description
It is not possible to use `into_boxed` if `union` or `union_all` is used before it. However, if I use `into_boxed` before the unions, everything works.

### What are you trying to accomplish?
I trying to use `into_boxed` after using `union_all`.
For example, it doesn't compile:
```rust
let query = posts::table
            .select((sql("'post'"), posts::id, posts::published))
            .union_all(post_boost::table.select((
                sql("'boost'"),
                post_boost::id,
                post_boost::published,
            )))
            .positional_order_by(OrderColumn::from(3).desc()) // The problem persists even if I remove `positional_order_by`
            .into_boxed();
// Code that requires boxed query
```
This compiles:
```rust
let query = posts::table
            .select((sql("'post'"), posts::id, posts::published))
            .into_boxed()
            .union_all(post_boost::table.select((
                sql("'boost'"),
                post_boost::id,
                post_boost::published,
            )))
            .positional_order_by(OrderColumn::from(3).desc());
// Code that requires boxed query
```

### What is the expected output?
The code works.

### What is the actual output?
Compilation error.

### Are you seeing any additional errors?
```
error[E0599]: the method `into_boxed` exists for struct `PositionalOrderClause<CombinationClause<Union, All, SelectStatement<FromClause<table>, SelectClause<(SqlLiteral<_>, id, published)>>, ...>, ...>`, but its trait bounds were not satisfied
    |
157 |           let query = posts::table
    |  _____________________-
158 | |             .select((sql("'post'"), posts::id, posts::published))
159 | |             .union_all(post_boost::table.select((
160 | |                 sql("'boost'"),
...   |
164 | |             .positional_order_by(OrderColumn::from(3).desc())
165 | |             .into_boxed();
    | |             -^^^^^^^^^^ method cannot be called due to unsatisfied trait bounds
    | |_____________|
    | 
    |
   ::: /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-2.1.4/src/query_dsl/positional_order_dsl.rs:24:1
    |
24  |   pub struct PositionalOrderClause<Source, Expr> {
    |   ----------------------------------------------
    |   |
    |   doesn't satisfy `_: QueryDsl`
    |   doesn't satisfy `_: Table`
    |
    = note: the following trait bounds were not satisfied:
            `PositionalOrderClause<query_builder::combination_clause::CombinationClause<query_builder::combination_clause::Union, query_builder::combination_clause::All, SelectStatement<FromClause<posts::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, posts::columns::id, posts::columns::published)>>, SelectStatement<FromClause<schema::post_boost::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, schema::post_boost::columns::id, schema::post_boost::columns::published)>>>, diesel::expression::operators::Desc<OrderColumn>>: Table`
            which is required by `PositionalOrderClause<query_builder::combination_clause::CombinationClause<query_builder::combination_clause::Union, query_builder::combination_clause::All, SelectStatement<FromClause<posts::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, posts::columns::id, posts::columns::published)>>, SelectStatement<FromClause<schema::post_boost::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, schema::post_boost::columns::id, schema::post_boost::columns::published)>>>, diesel::expression::operators::Desc<OrderColumn>>: diesel::QueryDsl`
            `&PositionalOrderClause<query_builder::combination_clause::CombinationClause<query_builder::combination_clause::Union, query_builder::combination_clause::All, SelectStatement<FromClause<posts::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, posts::columns::id, posts::columns::published)>>, SelectStatement<FromClause<schema::post_boost::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, schema::post_boost::columns::id, schema::post_boost::columns::published)>>>, diesel::expression::operators::Desc<OrderColumn>>: Table`
            which is required by `&PositionalOrderClause<query_builder::combination_clause::CombinationClause<query_builder::combination_clause::Union, query_builder::combination_clause::All, SelectStatement<FromClause<posts::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, posts::columns::id, posts::columns::published)>>, SelectStatement<FromClause<schema::post_boost::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, schema::post_boost::columns::id, schema::post_boost::columns::published)>>>, diesel::expression::operators::Desc<OrderColumn>>: diesel::QueryDsl`
            `&mut PositionalOrderClause<query_builder::combination_clause::CombinationClause<query_builder::combination_clause::Union, query_builder::combination_clause::All, SelectStatement<FromClause<posts::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, posts::columns::id, posts::columns::published)>>, SelectStatement<FromClause<schema::post_boost::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, schema::post_boost::columns::id, schema::post_boost::columns::published)>>>, diesel::expression::operators::Desc<OrderColumn>>: Table`
            which is required by `&mut PositionalOrderClause<query_builder::combination_clause::CombinationClause<query_builder::combination_clause::Union, query_builder::combination_clause::All, SelectStatement<FromClause<posts::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, posts::columns::id, posts::columns::published)>>, SelectStatement<FromClause<schema::post_boost::table>, query_builder::select_clause::SelectClause<(SqlLiteral<_>, schema::post_boost::columns::id, schema::post_boost::columns::published)>>>, diesel::expression::operators::Desc<OrderColumn>>: diesel::QueryDsl`

For more information about this error, try `rustc --explain E0599`.
error: could not compile due to previous error
```

### Steps to reproduce
Try to compile the above code.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-12-10 14:49
That's essentially a duplicate of #2620.

**Closed** 2023-12-10 14:49 UTC
Labels: bug
