### ISSUE TITLE
Could not build crate using diesel with #![deny(missing_docs)]

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#845] opened 2017-04-06 08:39 UTC
I would like to build my own crate using diesel with `#![deny(missing_docs)]` to force everyone to write at least documentation for all public items. Even if every public item is documented this will fail because of the diesel generated code.

It seems like there is no way to document the column structs generated by the table macro.

Minimal Example:
```rust
#![deny(missing_docs)]

#[macro_use]
extern crate diesel;


table!{
    some_table {
        id -> BigInt,
        column_a -> Text,
        column_b -> BigInt,
    }
}
```

Error messages: 
```
error: missing documentation for crate
 --> src/lib.rs:1:1
  |
1 |   #![deny(missing_docs)]
  |  _^ starting here...
2 | |
3 | | #[macro_use]
4 | | extern crate diesel;
5 | |
6 | |
7 | | table!{
  | |______^ ...ending here
  |
note: lint level defined here
 --> src/lib.rs:1:9
  |
1 | #![deny(missing_docs)]
  |         ^^^^^^^^^^^^

error: missing documentation for a module
  --> src/lib.rs:7:1
   |
7  |   table!{
   |  _^ starting here...
8  | |     some_table {
9  | |         id -> BigInt,
10 | |         column_a -> Text,
11 | |         column_b -> BigInt,
12 | |     }
13 | | }
   | |_^ ...ending here
   |
   = note: this error originates in a macro outside of the current crate

error: missing documentation for a struct
  --> src/lib.rs:7:1
   |
7  |   table!{
   |  _^ starting here...
8  | |     some_table {
9  | |         id -> BigInt,
10 | |         column_a -> Text,
11 | |         column_b -> BigInt,
12 | |     }
13 | | }
   | |_^ ...ending here
   |
   = note: this error originates in a macro outside of the current crate

error: missing documentation for a struct
  --> src/lib.rs:7:1
   |
7  |   table!{
   |  _^ starting here...
8  | |     some_table {
9  | |         id -> BigInt,
10 | |         column_a -> Text,
11 | |         column_b -> BigInt,
12 | |     }
13 | | }
   | |_^ ...ending here
   |
   = note: this error originates in a macro outside of the current crate

error: missing documentation for a struct
  --> src/lib.rs:7:1
   |
7  |   table!{
   |  _^ starting here...
8  | |     some_table {
9  | |         id -> BigInt,
10 | |         column_a -> Text,
11 | |         column_b -> BigInt,
12 | |     }
13 | | }
   | |_^ ...ending here
   |
   = note: this error originates in a macro outside of the current crate
```

**Comment by killercup** [comment] 2017-04-06 12:33
Dupe of #378, still very much a valid bug.

Does `#[allow(missing_docs)]` on the mod created by diesel help you.

**Closed by killercup** 2017-04-06 12:33 UTC
