### ISSUE TITLE
Unable to specify more than 3 pool connections.

### ISSUE THREAD

**Issue by Wiper-R** [diesel-rs/diesel#3348] opened 2022-09-28 01:24 UTC
### Versions

- **Rust: 1.64.0 (a55dd71d5 2022-09-19)**
- **Diesel: 2.0.0**
- **Database: postgresql14**
- **Operating System: Windows**

### Feature Flags

- **diesel: "postgres", "uuid", "chrono", "r2d2"**

## Problem Description
Process exits with `error  code 3` when I specify more than 3 connections for the pool.

### What are you trying to accomplish?
I am trying to setup a postgresql connection pool with diesel with 3 or more connection but it only works for 2 or less.

### What is the expected output?
I don't have any running connections so there is no possibility of `max client reached` and it should connect to the database.

### What is the actual output?
```error: process didn't exit successfully: `target\debug\database-server.exe` (exit code: 3)```

### Steps to reproduce
```rs
use diesel::r2d2::ConnectionManager;
use diesel::r2d2;
use diesel::PgConnection;

use dotenvy::dotenv;
use std::env;


pub type DbConnection = r2d2::PooledConnection<ConnectionManager<PgConnection>>;
pub type Pool = r2d2::Pool<ConnectionManager<PgConnection>>;

// Database URL: "postgresql://postgres:postgres@127.0.0.1:5432/mydb"

// Side Node: Specify `min_idle as 0 or 1` works. I think this is something to do with simultaneous connections

pub fn get_connection_pool() -> Pool {
    dotenv().ok();
    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    println!("Database URL: {}", database_url);
    let manager = ConnectionManager::<PgConnection>::new(database_url);
    return Pool::builder().max_size(50).build(manager).unwrap();
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by Wiper-R** [comment] 2022-09-28 01:39
I have already tested using `python asyncpg` to verify that is there something wrong with my system. But apparently that work without any issues.

**Here is what I have tested**

```py
from typing import List
import asyncpg, asyncio


async def main():
    connections: List[asyncpg.Connection] = []
    for _ in range(50):
        conn: asyncpg.Connection = await asyncpg.connect("postgresql://postgres:postgres@127.0.0.1:5432/mydb")
        connections.append(conn)

    # This is to check that all connections are working
    print("Fetching queries from connections")
    fin = 0
    for conn in connections:
        fin += await conn.fetchval("SELECT 1")

    # Dropping all connections
    print("Dropping all connections")
    for conn in connections:
        await conn.close()

    print(fin)


asyncio.run(main())
```

**Comment by weiznich** [comment] 2022-09-28 06:16
Duplicate of https://github.com/diesel-rs/diesel/discussions/2947

(It's an issue with in your libpq version)

**Closed by weiznich** 2022-09-28 06:16 UTC
Labels: bug

**Comment by Wiper-R** [comment] 2022-09-28 06:23
> Duplicate of https://github.com/diesel-rs/diesel/discussions/2947
> 
> (It's an issue with in your libpq version)
> 

Thanks, will see if that works.

**Comment by Wiper-R** [comment] 2022-09-28 13:37
You were right, pasting new libintl
