### ISSUE TITLE
Dies with nightly Rust

### ISSUE THREAD

**Issue by trsh** [diesel-rs/diesel#1701] opened 2018-05-18 07:14 UTC
```
error[E0053]: method `metadata` has an incompatible type for trait
   --> /home/trsh/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.2.2/src/pg/types/array.rs:14:25
    |
14  |     fn metadata(lookup: &PgMetadataLookup) -> PgTypeMetadata {
    |                         ^^^^^^^^^^^^^^^^^ expected associated type, found struct `pg::metadata_lookup::PgMetadataLookup`
    | 
   ::: /home/trsh/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.2.2/src/sql_types/mod.rs:402:25
    |
402 |     fn metadata(lookup: &Self::MetadataLookup) -> Self::TypeMetadata;
    |                         --------------------- type in trait
    |
    = note: expected type `fn(&<pg::backend::Pg as sql_types::TypeMetadata>::MetadataLookup) -> <pg::backend::Pg as sql_types::TypeMetadata>::TypeMetadata`
               found type `fn(&pg::metadata_lookup::PgMetadataLookup) -> pg::backend::PgTypeMetadata`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0053`.
error: Could not compile `diesel`.

```

**Comment by weiznich** [comment] 2018-05-18 07:17
Duplicate of #1700

**Closed** 2018-05-18 07:17 UTC
