### ISSUE TITLE
How to store phone numbers in Postgres?

### ISSUE THREAD

**Issue by spease** [diesel-rs/diesel#1654] opened 2018-04-22 02:13 UTC
This could also be generalized to "How to make a custom type work with diesel?"

Basically, I'd like to be able to load and store phone numbers that I'm storing with the phonenumber crate into a postgres database.

It looks like there's a postges extension for this:
https://github.com/blm768/pg-libphonenumber

But I'd just be happy with being able to do it with a text type for now.

I tried implementing FromSql and ToSql for a wrapper type as seen in this example:
https://github.com/diesel-rs/diesel/blob/master/diesel_tests/tests/custom_types.rs#L42

But this approach gets stuck on "only traits in the current crate can be implemented for arbitrary types".

Thanks.

**Comment by weiznich** [comment] 2018-04-22 10:50
In general it is totally possible to implement custom types outside of diesel. The test case you linked is basically the blue print for implementing such an type.

It is really hard to answer this question without any code to reproduce this. Please add the your current code and the current (exact) error to the issue. 

I will close this issue because it does not contain anything that actionable for us to fix in diesel. 
Feel free to update the issue with more informations. We will continue to answer this questions here. Or ask in our gitter channel.

**Closed by weiznich** 2018-04-22 10:50 UTC
Labels: question
