### ISSUE TITLE
sql_name attribute in table macro result in Invalid `table!` syntax.

### ISSUE THREAD

**Issue by patrikha** [diesel-rs/diesel#3735] opened 2023-08-09 11:01 UTC
## Setup
diesel = { version = "2.1.0", features = ["mysql", "chrono"] }

### Versions

- **Rust:** cargo 1.71.1 edition 2021 rustc 1.71.1
- **Diesel:** 2.1.0
- **Database:** MariaDB (MySQL)
- **Operating System** 6.1.41-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Jul 25 09:17:30 UTC 2023 x86_64 GNU/Linux

### Feature Flags

- **diesel:** mysql, chrono

## Problem Description
Can't use the sql_name attribute without getting a compiler error.
```
diesel::table! {
    sonardefects (id) {
        id -> Integer,
        #[max_length = 32]
        key -> Varchar,
        #[sql_name = "type", max_length = 32]
        type_ -> Nullable<Varchar>,
    }
}
```
### What are you trying to accomplish?
Renaming a table column from type to type_

### What is the expected output?
no compile error

### What is the actual output?
```
error: Invalid `table!` syntax. Please see the `table!` macro docs for more info.
       Docs available at: `https://docs.diesel.rs/master/diesel/macro.table.html`
   --> src/schema.rs:842:1
    |
842 | / diesel::table! {
843 | |     sonardefects (id) {
844 | |         id -> Integer,
845 | |         #[max_length = 32]
...   |
864 | |     }
865 | | }
    | |_^
    |
    = note: this error originates in the macro `diesel::table` (in Nightly builds, run with -Z macro-backtrace for more info)

```

### Are you seeing any additional errors?
No

### Steps to reproduce
Using code block above causes the compiler to fail.

Comment out the attribute makes the code compile!
```
diesel::table! {
    sonardefects (id) {
        id -> Integer,
        #[max_length = 32]
        key -> Varchar,
        #[/*sql_name = "type",*/ max_length = 32]
        type_ -> Nullable<Varchar>,
    }
}
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-08-09 11:11
Duplicate of https://github.com/diesel-rs/diesel/issues/3692

**Closed by weiznich** 2023-08-09 11:11 UTC
Labels: bug
