### ISSUE TITLE
Unsupported type: uuid

### ISSUE THREAD

**Issue by lexer21** [diesel-rs/diesel#3757] opened 2023-08-18 17:35 UTC
Hello,

Im trying to setup tauri + sqlite database. In my migrations im trying create a table like this:

```
CREATE TABLE profile (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    realm VARCHAR(255),
    created_at DATETIME
);
```

When i run `diesel migration run` i get the following output: 

```
Running migration 2023-08-18-161720_profile
Unsupported type: uuid
```
The wierd thing is that my .db file actually gets created with the correct table structure, but my `schema.rs` is empty.

My dependencies:

```
[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
uuid = {version = "1.4.1", features = ["v4", "fast-rng","macro-diagnostics"]}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.4.0", features = [] }
tokio = { version = "1", features = ["full"] }
diesel = { version = "2.0.0", features = ["sqlite", "chrono", "extras"] }
diesel_migrations = "2.0.0"
libsqlite3-sys = { version = ">=0.17.2, <0.26.0", features = ["bundled"] }
chrono = { version = "0.4.24", features = ["serde"] }
dirs = "5.0.0"
dotenv = "0.15"
```

**Comment by weiznich** [comment] 2023-08-18 19:31
Duplicate of https://github.com/diesel-rs/diesel/issues/364. Additionally: The issue template is mandatory. If you feel that it does not fit that is usually a sign that you should use the support forum instead.

**Closed by weiznich** 2023-08-18 19:31 UTC
Labels: bug
