### ISSUE TITLE
JSONB data query does not work using `sql` 

### ISSUE THREAD

**Issue by kushwahashiv** [diesel-rs/diesel#3136] opened 2022-04-19 00:50 UTC
### Versions

- **Rust:** rustc 1.59.0-nightly
- **Diesel:** diesel = { version = "1.3.3", features = ["postgres", "extras"] }
- **Database:** postgres
- **Operating System** macos

### Feature Flags

- **diesel:**

### schema

```rust 
table! {
    sample (id) {
        id -> Int4,
        meta -> Nullable<Jsonb>,
    }
}

```

```rust
#[derive(Deserialize, Debug, Clone, PartialEq)]
pub struct Meta {
  pub s: i32,
}

```

I am trying to query above table in postgres

```rust
fn search_by_meta(&self, meta: Meta) -> Sample {
//...
 let query = sample.filter(sql("meta ->> 's' > ").bind::<Int4, _>(meta.s));

let res = query
      .get_results(self.db_conn)
      .map_err(|e| Error::from(e).into());

res
}
```

### What are you trying to accomplish?
I am trying to use operators in JOSNB field. 

### What is the expected output?
Query should give a result.

### What is the actual output?
Diesel doesn't allow this to query and crashing the service.

**Comment by weiznich** [comment] 2022-04-19 06:23
Please specify what you mean by "Diesel doesn't allow this to query and crashing the service." As currently written this could include anything from diesel returning a valid error to a segfault.

**Comment by weiznich** [comment] 2022-04-20 20:23
Your query returns the following error message: "operator does not exist: text > integer". This indicates an issue with your query and not with diesel itself. 

For reference the following SQL query is generated:

```sql
SELECT "sample"."id", "sample"."meta" FROM "sample" WHERE meta ->> 's' > $1 -- binds: [42]
```

which remains invalid if you replace the bind with an explicit literal and execute it manually. That's because [the `->>` operator returns a text value](https://www.postgresql.org/docs/current/functions-json.html), which just cannot be compared with an integer.

Closed as this is not a bug in diesel.

**Closed by weiznich** 2022-04-20 20:23 UTC
Labels: bug
