### ISSUE TITLE
Runtime schema creation

### ISSUE THREAD

**Issue by CGenie** [diesel-rs/diesel#2165] opened 2019-09-18 08:39 UTC
Hello,

I know that Diesel can infer schema automatically into a `table!` macro and then, after creating proper model with `#[deriving(Queryable)]` I can query it.
Is it possible to make this fully runtime? I basically want to be able to do something similar to Go's `sqlboiler`:
```go
db, err := sql.Open("postgres", "dbname=fun user=abc")
boil.SetDB(db)
users, err := models.Users().AllG(ctx)
```

This would best fit my database-first approach of integrating Rust to a huge Python codebase.

**Comment by weiznich** [comment] 2019-09-18 09:15
It's by design not possible to use at runtime generated `table!` macro, because the macro internally generates a bunch of types used to assert type safety of sql queries.

In general doing something like the go example would require some kind of run time reflection which is not supported by rust.

That said: There is [diesel-dynamic-schema](https://github.com/diesel-rs/diesel-dynamic-schema) for using diesel without having a statically known schema, though it does not generate something from given database connection.

I'm closing this issue because this is not something we plan to implement in diesel itself in the future.

**Closed by weiznich** 2019-09-18 09:15 UTC

**Comment by CGenie** [comment] 2019-09-18 09:24
Ah OK thank you, I'll check the `diesel-dynamic-schema` project.
