### ISSUE TITLE
diesel_cli migration run command in sub module project create wrong path src/schema.rs 

### ISSUE THREAD

**Issue by robatipoor** [diesel-rs/diesel#2320] opened 2020-03-06 19:43 UTC
Why this problem has not been resolved so far ?

**Comment by weiznich** [comment] 2020-03-06 21:17
Duplicate of #2057 

> Why this problem has not been resolved so far ?

Please stop making such requests.That's extremely rude. This is a open source project run by people in their free time. If you want timely support for issue that is important for you, consider paying someone to solve it, but don't expect that to happen magically from people for free.

**Closed by weiznich** 2020-03-06 21:17 UTC

**Comment by robatipoor** [comment] 2020-03-07 18:33
i think fixed this issue
