### ISSUE TITLE
Diesel fails rustfmt

### ISSUE THREAD

**Issue by martinellison** [diesel-rs/diesel#2199] opened 2019-10-11 02:34 UTC
Diesel causes rustfmt to crash.

### Versions

- **Rust:** rustc 1.38.0 (625451e37 2019-09-23)
- **Diesel:** diesel v1.4.2
- **Database:** sqlite
- **Operating System** Linux xiaosan 5.2.17-200.fc30.x86_64 #1 SMP Mon Sep 23 13:42:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

same issue with Ubuntu on aarch64

### Feature Flags

- **diesel:**

### What are you trying to accomplish?

Document my code

`cargo  doc  --document-private-items --all --exclude diesel --open` or `cargo  doc  --all  --open`, same effect

### What is the expected output?

documentation

### What is the actual output?

> error: unknown start of token: \
>  --> <doctest>:3:12
>   |
> 3 | # include!(\"../../doctest_setup.rs\");
>   |            ^
> 
> error: unterminated double quote string
>  --> <doctest>:3:13
>   |
> 3 |   # include!(\"../../doctest_setup.rs\");
>   |  _____________^
> 4 | | # use diesel::dsl::*;
> 5 | | #
> 6 | | # fn main() {
> 7 | | #     let connection = establish_connection();
> 8 | | let today: chrono::NaiveDate = diesel::select(date(now)).first(&connection).unwrap();
> 9 | | # }
>   | |____^
> 
> error: Could not document `diesel`.
> 
> Caused by:
>   process didn't exit successfully: `rustdoc --crate-name diesel /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.2/src/lib.rs --cap-lints allow -o /home/martin/git/fanling10/target/doc --cfg 'feature="32-column-tables"' --cfg 'feature="default"' --cfg 'feature="libsqlite3-sys"' --cfg 'feature="sqlite"' --cfg 'feature="with-deprecated"' --color always -L dependency=/home/martin/git/fanling10/target/debug/deps --extern byteorder=/home/martin/git/fanling10/target/debug/deps/libbyteorder-3891873289ca81d7.rmeta --extern diesel_derives=/home/martin/git/fanling10/target/debug/deps/libdiesel_derives-8435e86f13bb0ff2.so --extern libsqlite3_sys=/home/martin/git/fanling10/target/debug/deps/liblibsqlite3_sys-3fa9f921ac0490ad.rmeta` (exit code: 1)

### Are you seeing any additional errors?

no

### Steps to reproduce

as above

## Checklist

- [ x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2019-10-11 09:34
Duplicate of #2148. Already fixed on master.

**Closed by weiznich** 2019-10-11 09:34 UTC
