### ISSUE TITLE
Allow to skip custom changes in the generated schema

### ISSUE THREAD

**Issue by silvioprog** [diesel-rs/diesel#2296] opened 2020-02-11 14:53 UTC
Hi.

Consider the following table (PostgreSQL):

```sql
CREATE TABLE servicos (
  id BIGSERIAL PRIMARY KEY,
  descricao CHARACTER VARYING(50) NOT NULL UNIQUE
);
```

and the following schema (generated by Diesel CLI):

```rust
table! {
    servicos (id) {
        id -> Int8,
        descricao -> Varchar,
    }
}
```

To use those code above in a Rocket application, we must declare at least two structures:

```rust
#[derive(Debug, Clone, Serialize, Deserialize, Queryable)]
#[table_name = "servicos"]
pub struct Servico {
    pub id: i64,
    pub descricao: String,
}

#[derive(Debug, Clone, Insertable)]
#[table_name = "servicos"]
pub struct Servico2 {
    pub descricao: String,
}
```

The second struct is used only for inserting records, however, for large applications with productivity in mind, it would be nice to avoid it, declaring only something like this (notice the `Option`):

```rust
table! {
    servicos (id) {
        id -> Nullable<Int8>,
        descricao -> Varchar,
    }
}
```
```rust
#[derive(Debug, Clone, Serialize, Deserialize, Queryable, Insertable)]
#[table_name = "servicos"]
pub struct Servico {
    pub id: Option<i64>,
    pub descricao: String,
}
```

It works in current Diesel version, but when we run the `migration run`, it replaces `id -> Nullable<Int8>` by `id -> Int8` again in all declared types, so it would be nice something like this (inspired by [greenDAO](https://greenrobot.org/greendao/documentation)):

```rust
#[derive(Debug, Clone, Serialize, Deserialize, Queryable, Insertable)]
#[table_name = "servicos"]
pub struct Servico {
    // diesel:skip
    pub id: Option<i64>,
    pub descricao: String,
}
```

Notice the `// diesel:skip`, it warns Diesel with _"hey Diesel, please skip this field and preserve it as it is declared"_. So the programmer is free to make a bit customizations if he doesn't agree with the generated schema.

WDYT?

**Comment by weiznich** [comment] 2020-02-11 19:06
It's an explicit design choice of diesel to separate structs for `Insertable` and `Queryable` in that way. 

It is important to note that `Queryable` and `Insertable` are **no** one to one replacement of model structs known from other ORM's. They are not designed that way. If you are using them like that it's fine, but that's not the use case they are designed for. In general diesel constructs map to sql, not to database structure. In detail, as the name implies, `Queryable` describes just the result set of some query. That means this set does not necessarily need to map to a specific table or have to contain all columns of such a table. `Insertable` on the other hand directly maps to a table. It is designed for such cases where you have already an existing struct (like in your example the struct that implements `Deserialize` from the rest api). If no such struct exists it is not required to write such an struct that implements `Insertable`, as it is possible to just write `diesel::insert_into(some_table::table).values((some_table::column_a.eq(foo), some_table::column_b.eq(bar)).execute(conn)?`. (It is even possible to use an struct that implements `Insertable` as tuple element there, so that you can extend the arguments you got over an api with some calculated value).

Anyway if you really want to have the behaviour you described it is possible to implement all that as third party crate, by just providing a custom derive that implements `Insertable` in a different way (or by manually implement `Insertable`). The relevant code for our derive is [here](https://github.com/diesel-rs/diesel/blob/fcf8677048f9b758555c4bdfd520ef998ed0b7f6/diesel_derives/src/insertable.rs). 

Closed because this is a duplicate of #860.

**Closed by weiznich** 2020-02-11 19:06 UTC
