### ISSUE TITLE
SQLite's INTEGER should map to BigInt

### ISSUE THREAD

**Issue by mjodl** [diesel-rs/diesel#2330] opened 2020-03-17 20:48 UTC
### Versions

- **Rust:** rustc 1.43.0-nightly (c9290dcee 2020-02-04)
- **Diesel:** diesel 1.4.3
- **Database:** bundled libssqlite3-sys 0.9.1
- **Operating System** Linux 

## Problem Description

While creating a schema for existing sqlite table 
```
CREATE TABLE t (
  timestamp INTEGER NOT NULL,
  id INTEGER PRIMARY KEY AUTOINCREMENT
);
``` 
diesel_cli created the following schema:
```
table! {
    t (id) {
        timestamp -> Integer,
        id -> Nullable<Integer>,
    }
}
```
Notice that obvious INTEGER → Integer mapping.
The problem is that diesel's [Integer](https://docs.diesel.rs/diesel/sql_types/struct.Integer.html) type implements Rust's [i32](https://doc.rust-lang.org/nightly/std/primitive.i32.html). However, SQLite's [INTEGER](https://www.sqlite.org/datatype3.html) is 
> a signed integer, stored in 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.

This means that INTEGER can store up to 64-bit signed integers. 
Can you consider providing a default mapping to [BigInt](https://docs.diesel.rs/diesel/sql_types/struct.BigInt.html)?

**Comment by weiznich** [comment] 2020-03-17 22:27
Duplicate of #852

**Closed by weiznich** 2020-03-17 22:27 UTC
