### ISSUE TITLE
failed to compile `diesel_cli v1.4.1` : fatal error LNK1181: cannot open input file 'linpq.lib'

### ISSUE THREAD

**Issue by xiayulu** [diesel-rs/diesel#2952] opened 2021-11-10 11:16 UTC
### Versions

- **Rust: rustc 1.56.1 (59eed8a2a 2021-11-01)**
- **Diesel: v1.4.8**
- **Database: PostgreSQL**
- **Operating System: Windows 10**

### Feature Flags

- **diesel: cargo install diesel_cli --no-default-features --features postgres**

## Problem Description

When I install diesel_cli with `cargo install diesel_cli --no-default-features --features postgres` I get the following error:

```shell
s-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: LINK : fatal error LNK1181: cannot open input file 'linpq.lib'


error: failed to compile `diesel_cli v1.4.1`, intermediate artifacts can be found at `C:\Users\hi\AppData\Local\Temp\cargo-installmJ3QMz`

Caused by:
  could not compile `diesel_cli` due to previous error
```
 
### What are you trying to accomplish?
Step 1: I download PostgreSQL from <https://www.enterprisedb.com/download-postgresql-binaries>
Step 2: I set the environment variable : `PQ_LIB_DIR=C:\Program Files\PostgreSQL\13\lib`

It doesn't work.

Howerver When I check the error: I find The link file is **linpq.lib**, Not **libpq**.

Step 3: I rename **libpq.lib** to **linpq.lib**
Then It complied.

👀 Is this a typo?

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-11-10 11:23
Duplicate of https://github.com/diesel-rs/diesel/issues/2519 and any other linker related issue.

Generally speaking we expect a `libpq` to be there, if it's not there it will not work + EnterpriseDB != official postgres release.

Closed as duplicate.

**Closed by weiznich** 2021-11-10 11:23 UTC
Labels: bug

**Comment by NielsDom** [comment] 2021-11-16 04:14
Same issue. Help please

**Comment by weiznich** [comment] 2021-11-16 07:51
@NielsDom Our issue tracker is no help forum. If you are looking for help, please use the forum or the gitter channel.
