### ISSUE TITLE
Sqlite Get Started example fails

### ISSUE THREAD

**Issue by HuakunShen** [diesel-rs/diesel#3620] opened 2023-05-08 06:39 UTC
### Versions

- **Rust:** 1.68.2
- **Diesel:** 2.0.2
- **Database:** sqlite
- **Operating System** MacOS

### Feature Flags

- **diesel:**`["sqlite", "returning_clauses_for_sqlite_3_35"]`

Not sure what `returning_clauses_for_sqlite_3_35` is, but it's in the example.

## Problem Description
The example https://github.com/diesel-rs/diesel/tree/master/examples/sqlite/getting_started_step_3
works within the repo, but doesn't work when I move it out of diesel repo (If I remove the relative path dependency).

I got errors with `check_for_backend` and `Post::as_returning`
- `check_for_backend`: error[E0599]: the function or associated item `as_returning` exists for struct `Post`, but its trait bounds were not satisfied
- `Post::as_returning`: function or associated item cannot be called on `Post` due to unsatisfied trait bounds

### What are you trying to accomplish?

Successfully run the example and get sqlite working.

### What is the expected output?

It should run as it could within diesel repo.

### What is the actual output?

Getting errors with `check_for_backend` and `Post::as_returning` in `lib.rs` and `models.rs`.

<img width="916" alt="image" src="https://user-images.githubusercontent.com/33727687/236751915-c6fc4317-ffba-4d99-bb8d-68b51c986e4a.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/33727687/236752050-ebc53fe3-2762-46b7-9d66-9b482e940cc4.png">

### Steps to reproduce

1. Copy the sqlite example folder from https://github.com/diesel-rs/diesel/tree/master/examples/sqlite/getting_started_step_3
2. Modify `Cargo.toml` to remote diesel dependency path (download from crates instead)
  - Was: `diesel = { version = "2.0.0", path = "../../../diesel", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }`
  - Resulting line: `diesel = { version = "2.0.2", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }`
4. Run
```bash
echo "DATABASE_URL=file:test.db" > .env
diesel migration run
cargo run --bin show_posts
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-05-08 06:49
This is expected behavior as the examples form the master branch explicitly use the diesel version from the master branch. That might include new features that are not available in any released diesel version yet, so modifying the dependencies there will break the example. If you use a diesel version from crates.io you need to use the examples from the corresponding git revision (see the release section for linked commits for each release).

Closed as this is not a bug. Please use the support forum for future questions as our issue tracker is a place to track actual bugs and not support requests.

**Closed by weiznich** 2023-05-08 06:49 UTC
Labels: bug
