### ISSUE TITLE
Geometric Types in Postgresql support

### ISSUE THREAD

**Issue by erihsu** [diesel-rs/diesel#2617] opened 2021-01-07 13:55 UTC
It seems diesel not support Geometric Types in postgresql feature currently. Any plan to support this ?

**Comment by weiznich** [comment] 2021-01-07 13:57
Duplicate of #491

**Closed by weiznich** 2021-01-07 13:57 UTC

**Comment by Gearme** [comment] 2021-02-02 19:11
There are indeed third-party crates supporting the types, but they may not be maintained, add another layer of complexity and often require a number of workarounds. [diesel_geometry](https://docs.rs/diesel_geometry/1.4.0/diesel_geometry/index.html) for example has not seen any commits for three years. So it's understandable to wish for it.
That said, I realize that simply subsuming that functionality in diesel's core is wishful thinking as long as it remains a single dev's unpaid side project.

**Comment by weiznich** [comment] 2021-02-03 08:40
@Gearme I can understand the wish of having support for this in diesel itself, but I just don't have the capacity to do this. Anyway back to something we can probably solve: You've mention that this requires a number of workarounds. Could you give a bit more details about that, as this is probably something we could improve on from diesels side.

**Comment by kushwahashiv** [comment] 2024-07-15 21:02
is this supported in any form in diesel
