### ISSUE TITLE
What happened to diesels embed_migrations! ?

### ISSUE THREAD

**Issue by tema3210** [diesel-rs/diesel#2390] opened 2020-05-08 17:00 UTC
- **Rust: 1.43.1**
- **Diesel: 1.4.0**
- **Database: sqlite in memory**
- **Operating System: Linux 5.3.0**

### Feature Flags

diesel = { version = "1.4.0", features = ["sqlite","mysql","r2d2","chrono"] }

## Problem Description
`EmbedMigrations` derive macro not found, which is called inside on declarative `embed_migrations!` one; function `run` from `embedded_migrations` module is absent.

### What are you trying to accomplish?
Trying to migrate database structure to in-memory sqlite DB for tests.

### What is the expected output?
compile that fine:
```
use diesel_migrations::embed_migrations;
embed_migrations!();
embedded_migrations::run(c)?;
```

### What is the actual output?
cannot find derive macro ...; cannot find function `run` ...

### Are you seeing any additional errors?
No.

### Steps to reproduce
N\A
## Checklist

- [+] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [+] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

## P.S.
I checked actual source of diesel_migrations crate, macro doesn't generate the code

**Comment by weiznich** [comment] 2020-05-08 17:12
Basically a duplicate of #1764.
Importing macros via use statement is not supported on the current releases.

**Closed by weiznich** 2020-05-08 17:12 UTC
