### ISSUE TITLE
How can i create a table without running a migration through the cli tool

### ISSUE THREAD

**Issue by avnerbarr** [diesel-rs/diesel#2591] opened 2020-12-08 14:57 UTC
I'm distributing an application to users, and the database + migrations need to be run from within the application and not the context of the diesel cli tool.

Not aware how to do that.

**Comment by weiznich** [comment] 2020-12-09 09:46
Duplicate of https://github.com/diesel-rs/diesel/issues/1591.

Also this is a issue tracker, not a place to ask questions. Use our forum or our gitter channel for that.

**Closed by weiznich** 2020-12-09 09:46 UTC
