### ISSUE TITLE
[CLI] v2 `error parsing patch: Hunk header does not match hunk` when running migrations

### ISSUE THREAD

**Issue by fenollp** [diesel-rs/diesel#3467] opened 2023-01-04 16:22 UTC
## Setup

* diesel_cli = 2.0.1 features=postgres

### Versions

- **Rust:** 1.66
- **Diesel:** 2.0.2
- **Database:** postgres 14
- **Operating System** alpine

### Feature Flags

- **diesel:** `["postgres", "postgres_backend", "uuid", "chrono", "network-address", "r2d2"]`

## Problem Description

We are moving from diesel 1 to 2 and all compiles and works well with diesel_cli v1. 
We would like to add `diesel migration redo --all --database-url ...` to our CI, to check for bad migrations
but we get an error message applying migrations with diesel_cli v2 (only).

### What are you trying to accomplish?

```shell
DATABASE_URL=postgres://route:route@localhost:5437/route_backend diesel migration run
```

### What is the expected output?

With diesel 1.4.1:
```
Running migration 2022-04-26-081533_uuid-ext
Running migration 2022-05-04-084752_create_routes
```

### What is the actual output?

```
Running migration 2022-04-26-081533_uuid-ext
Running migration 2022-05-04-084752_create_routes
error parsing patch: Hunk header does not match hunk
```

And the generated schema.rs file is empty.

### Are you seeing any additional errors?

None.

### Steps to reproduce

```shell
git clone https://github.com/fenollp/repro3467.git
cd repro3467
make
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-01-05 07:37
Thanks for opening this issue. 

This is in fact as the error message suggests just a case where the patch cannot be applied. This is caused by the fact that the generated `schema.rs` file changed with the major version update. You need to update your `schema.patch` file to interoperate these changes. In this specific case the change is caused by the fact that we added a comment on the top of the generated file, so your patch file fails to provide the necessary context lines.

As an unrelated note: Your patch-file is not even required as you can just put that attribute as outer attribute on the module definition ( `#[allow(unused_imports)] mod schema.rs;`).

Closed as this is not an issue in diesel.

**Closed by weiznich** 2023-01-05 07:37 UTC
Labels: bug
