### ISSUE TITLE
&mut in Call to Establish SqliteConnection Results in Compile Error

### ISSUE THREAD

**Issue by adolph** [diesel-rs/diesel#3293] opened 2022-08-25 22:35 UTC
https://github.com/diesel-rs/diesel/blob/d4113eda1d0d432707c1a731c5df448b300ffa40/examples/sqlite/getting_started_step_3/src/bin/show_posts.rs#L8

Removal of the &mut in the above line resolved error: 

error[E0277]: the trait bound `&mut SqliteConnection: Connection` is not satisfied
    --> src/bin/show_posts.rs:17:10
     |
17   |         .load::<Post>(&connection)
     |          ^^^^ the trait `Connection` is not implemented for `&mut SqliteConnection`
     |
     = help: the trait `Connection` is implemented for `SqliteConnection`
     = note: required because of the requirements on the impl of `LoadQuery<&mut SqliteConnection, diesel_demo::models::Post>` for `SelectStatement<table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<diesel_demo::schema::posts::published, diesel::expression::bound::Bound<Bool, bool>>>, diesel::query_builder::order_clause::NoOrderClause, diesel::query_builder::limit_clause::LimitClause<diesel::expression::bound::Bound<BigInt, i64>>>`
note: required by a bound in `load`

**Comment by weiznich** [comment] 2022-08-26 04:32
Please provide all information requested in the issue template. Otherwise this issue is not actionable and will be closed as incomplete.
Also note that these examples are tested as part of the CI runs, so its unlikely that they are broken. It might therefore be required to provide an minimal reproducible example of your issue.

**Comment by Mingun** [comment] 2022-08-26 04:47
It seems that you should replace `.load(&connection)` with `.load(connection)`, because `connection` is already a reference.

**Comment by weiznich** [comment] 2022-08-26 06:52
Closed as the error message does not even match the linked code. Please use the support forum for such questions in the future.

**Closed by weiznich** 2022-08-26 06:52 UTC
