### ISSUE TITLE
Dynamically add number of OR'ed statements to query

### ISSUE THREAD

**Issue by SorteKanin** [diesel-rs/diesel#2468] opened 2020-07-27 22:06 UTC
I'm trying to dynamically add a series of OR'd conditions to my query, and I have no idea how. I hope the (non-working) code below illustrates what I want to achieve (somewhat explained below):

```
let mut results = items::table
    .inner_join(sources::table)
    .select((items::name, items::price, items::weight, sources::name))
    .into_boxed();

let item_types = // A Vec<String> which is dynamically constructed

let mut filters = Vec<something something>;

if item_types.contains(&String::from("Weapons"))
{
    filters.push(items::id.eq_any(weapons::table.select(weapons::item_id))));
}

if item_types.contains(&String::from("Armor"))
{
    filters.push(items::slot.eq(Slot::Armor));
}

//
// Additional conditions pushed onto the filters vector based on the item_types vector...
// 

let maybe_filter = filters.iter().fold_first(|acc, e| {
    acc.or(e)
});

if let Some(final_filter) = maybe_filter
{
    results.filter(final_filter)
}
```

Basically, I have a number of conditions that I might have to check - if any of the conditions hold, I want the row to be selected, hence I need them all OR'ed together. Problem is, I don't know which conditions might have to be checked (it could be none, it could be all of them).

I can't get the type checker to be happy with anything I've tried. Is there some other way to do this? Is something like this even possible?  Any help greatly appreciated.

**Comment by weiznich** [comment] 2020-07-28 07:49
I think the easiest way is to just apply each filter via `.or_filter` to your boxed query instead of storing them into a vector and applying them later.  So your code could look like:
```rust
let mut results = items::table
    .inner_join(sources::table)
    .select((items::name, items::price, items::weight, sources::name))
    .into_boxed();

let item_types = // A Vec<String> which is dynamically constructed

if item_types.contains(&String::from("Weapons"))
{
    results = results.or_filter(items::id.eq_any(weapons::table.select(weapons::item_id)));
}

if item_types.contains(&String::from("Armor"))
{
    results = results.or_filter(items::slot.eq(Slot::Armor));
}

/// Handle additional filters exactly the same way
```


Otherwise you may want to look at the documentation of [`BoxableExpression`](http://docs.diesel.rs/diesel/expression/trait.BoxableExpression.html) for an unified expression type.

Closed as this is not a bug or feature request. Please use our [gitter channel](https://gitter.im/diesel-rs/diesel) or [our forum](https://discourse.diesel.rs/) for future questions.

**Closed by weiznich** 2020-07-28 07:49 UTC

**Comment by SorteKanin** [comment] 2020-07-28 15:18
Thank a lot! I somehow missed `or_filter` in the docs... doh!
