### ISSUE TITLE
I get a Nullable<Integer> when following sqlite example

### ISSUE THREAD

**Issue by JediMaster25** [diesel-rs/diesel#3184] opened 2022-05-23 01:16 UTC
## Setup
Don't know what this means.

### Versions

- **Rust:** 1.60.0
- **Diesel:** 1.4.8-1
- **Database:** sqlite 3.38.4-1
- **Operating System** Manjaro Linux

### Feature Flags

- **diesel:** sqlite

## Problem Description
```
CREATE TABLE posts (
  id INTEGER NOT NULL PRIMARY KEY,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 0
)
```

When I do `diesel migration run` I get:
```
table! {
    posts (id) {
        id -> Nullable<Integer>,
        title -> Text,
        body -> Text,
        published -> Bool,
    }
}
```
But that's not what I'm supposed to get according to the example.

### What are you trying to accomplish?
I want to get the same schema as in the example.

### What is the expected output?
```
table! {
    posts (id) {
        id -> Integer,
        title -> Text,
        body -> Text,
        published -> Bool,
    }
}
```

### What is the actual output?
```
table! {
    posts (id) {
        id -> Nullable<Integer>,
        title -> Text,
        body -> Text,
        published -> Bool,
    }
}
```

### Are you seeing any additional errors?
```
❯ cargo run --bin write_post
error[E0277]: the trait bound `i32: FromSql<diesel::sql_types::Nullable<diesel::sql_types::Integer>, Pg>` is not satisfied
    --> src/lib.rs:34:10
     |
34   |         .get_result(conn)
     |          ^^^^^^^^^^ the trait `FromSql<diesel::sql_types::Nullable<diesel::sql_types::Integer>, Pg>` is not implemented for `i32`
```

### Steps to reproduce
The same as in the Problem Description

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
https://github.com/diesel-rs/diesel/issues/2988

- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2022-05-23 04:11
Using the issue template is mandatory. Please add the information requested there, otherwise I will close this issue as cannot reproduce. Additionally, please double check for already open issues with similar content.

**Comment by weiznich** [comment] 2022-05-23 12:48
Seems like a duplicate of #2988. Please add relevant details there.

Closed as duplicate.

**Closed by weiznich** 2022-05-23 12:48 UTC
Labels: bug
