### ISSUE TITLE
Error when trying to install diesel_cli with PostgreSQL only

### ISSUE THREAD

**Issue by Voodlaz** [diesel-rs/diesel#2377] opened 2020-04-24 14:40 UTC
When I try to install diesel_cli with PostgreSQL using this command `cargo install diesel_cli --no-default-features --features postgres` I get following Error:

`error: linking with link.exe failed: exit code: 1181
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.0.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.1.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.10.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.11.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.12.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.13.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.14.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.15.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.2.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.3.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.4.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.5.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.6.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.7.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.8.rcgu.o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.diesel.di1vuthq-cgu.9.rcgu.o" "/OUT:C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.exe" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\diesel-993e91542f155a7b.4743wje5p89g2xbn.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps" "/LIBPATH:C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\liburl-4cbac341f3126ec8.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libpercent_encoding-64ba14e657a28c88.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libidna-986ca05cad8371e7.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libunicode_normalization-1e6efcf081615a73.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libsmallvec-a9846d12c79661fb.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libunicode_bidi-a441b5c982f39965.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libmatches-4f6ee790eb92ce41.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libtoml-3d3edfcabcd70f4a.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libtempfile-0ef20b8edc7ee698.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\librand-c909eab234c90073.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\librand_chacha-a7f9acb194ab5d6d.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libppv_lite86-cd89244486ec525c.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\librand_core-25f28b5360026952.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libgetrandom-7ed6030f69ba46ff.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libremove_dir_all-96f313495d3f4e0e.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libserde-f3c03b4cf935e8b5.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libmigrations_internals-4b64ebb69643a84c.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libdotenv-1dcdefeb00a8ff19.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libregex-d479317c292de93b.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libutf8_ranges-128566ec245769ca.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libregex_syntax-b19a51ecebe05d08.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libucd_util-39319187533afa71.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libthread_local-a255ebbcf68084a6.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\liblazy_static-d59cdffd2d25cb21.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libaho_corasick-893f246a85d83dc8.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libmemchr-3b46e73e91cdbe11.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\liberror_chain-475592e81e027b5c.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libbacktrace-871dddaba26db804.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libcfg_if-486d501f012c3f43.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\librustc_demangle-8d5d952ad0d70cf1.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libdiesel-3decdf4d2343e701.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libpq_sys-3685797003bc97c1.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libbyteorder-26f31431c7cf82c0.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libclap-3eab550d10504882.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libvec_map-a74f942376688bf6.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libtextwrap-0675e5dff11a1612.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libunicode_width-fa01063533a1903d.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libstrsim-83c9d729286a3bc1.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libbitflags-aa2ec1b9b107ae39.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libatty-caa55b1f564d9031.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libchrono-46c27311e4c6c129.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libnum_integer-cbe9ab64ae403859.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libnum_traits-fd4da71e190052f3.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libtime-8e1f6f588d6c8949.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install4ZswmD\\release\\deps\\libwinapi-e323d6d0027938ce.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-c74d8e9f6a073a0c.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-e9179d6d957eb129.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-ea86c7569f74f4a9.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-71aed42ad40b4cf9.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libbacktrace-549a4902f45899bd.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-0635f5b63ec4bb26.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-dc454c66bc062953.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-b6bd6a9034b894cb.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-49dee66ddb1079c7.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-2dc0150f0b2ed5d5.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-c07931fabdb4be9b.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-12035d5342030ca6.rlib" "C:\\Users\\user\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-dc984712fabdd518.rlib" "advapi32.lib" "libpq.lib" "advapi32.lib" "cfgmgr32.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "opengl32.lib" "user32.lib" "winspool.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"`

- **Rust: 1.44.0-nightly**
- **Diesel: 1.0.0**
- **Database: PostgreSQL 10**
- **Operating System: Windows 10 **

**Comment by weiznich** [comment] 2020-04-24 20:14
Duplicate of #2343

**Closed** 2020-04-24 20:15 UTC
