### ISSUE TITLE
Compile erros when using Decimal/Numeric types in diesel v2

### ISSUE THREAD

**Issue by sergeken** [diesel-rs/diesel#3311] opened 2022-09-08 09:48 UTC
## Setup
Attempt to isolate in a snippet

[dependencies]
diesel = { version = "*", features = ["postgres"] }
dotenvy = "0.15"
chrono = { version = "*", features = ["serde"] }
rust_decimal = {version = "*", features = ["db-diesel-postgres"] }

### Versions

- **Rust:* 1,63,0
- **Diesel: v2.0
- **Database:* Postgres
- **Operating System: WSL

### Feature Flags

- **diesel:**

## Problem Description
error[E0277]: the trait bound `(BigInt, diesel::sql_types::Numeric, Integer, diesel::sql_types::Text, diesel::sql_types::Nullable<BigInt>): load_dsl::private::CompatibleType<Payment, _>` is not satisfied

### What are you trying to accomplish?
Compile a previously working schema with v1.

### What is the expected output?
No error messages

### What is the actual output?
error[E0277]: the trait bound `(BigInt, diesel::sql_types::Numeric, Integer, diesel::sql_types::Text, diesel::sql_types::Nullable<BigInt>): load_dsl::private::CompatibleType<Payment, _>` is not satisfied
    --> src/models.rs:47:10
     |
47   |     payment.load::<Payment>(connection).expect("Error getting payments")
     |             ^^^^ the trait `load_dsl::private::CompatibleType<Payment, _>` is not implemented for `(BigInt, diesel::sql_types::Numeric, Integer, diesel::sql_types::Text, diesel::sql_types::Nullable<BigInt>)`
     |
     = help: the following other types implement trait `load_dsl::private::CompatibleType<U, DB>`:
               (ST0, ST1)
               (ST0, ST1, ST2)
               (ST0, ST1, ST2, ST3)
               (ST0, ST1, ST2, ST3, ST4)
               (ST0, ST1, ST2, ST3, ST4, ST5)
               (ST0, ST1, ST2, ST3, ST4, ST5, ST6)
               (ST0, ST1, ST2, ST3, ST4, ST5, ST6, ST7)
               (ST0, ST1, ST2, ST3, ST4, ST5, ST6, ST7, ST8)
             and 24 others
     = note: required because of the requirements on the impl of `LoadQuery<'_, _, Payment>` for `schema::payment::table`
note: required by a bound in `diesel::RunQueryDsl::load`
    --> /home/serge/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-2.0.0/src/query_dsl/mod.rs:1499:15
     |
1499 |         Self: LoadQuery<'query, Conn, U>,
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `diesel::RunQueryDsl::load`

error[E0277]: the trait bound `Payment: FromSqlRow<_, _>` is not satisfied
    --> src/models.rs:47:10
     |
47   |     payment.load::<Payment>(connection).expect("Error getting payments")
     |             ^^^^ the trait `FromSqlRow<_, _>` is not implemented for `Payment`
     |
     = help: the following other types implement trait `FromSqlRow<ST, DB>`:
               <(T1, T0) as FromSqlRow<(ST1, Untyped), __DB>>
               <(T1, T2, T0) as FromSqlRow<(ST1, ST2, Untyped), __DB>>
               <(T1, T2, T3, T0) as FromSqlRow<(ST1, ST2, ST3, Untyped), __DB>>
               <(T1, T2, T3, T4, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, Untyped), __DB>>
               <(T1, T2, T3, T4, T5, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, ST5, Untyped), __DB>>
               <(T1, T2, T3, T4, T5, T6, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, Untyped), __DB>>
               <(T1, T2, T3, T4, T5, T6, T7, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, ST7, Untyped), __DB>>
               <(T1, T2, T3, T4, T5, T6, T7, T8, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, ST7, ST8, Untyped), __DB>>
             and 23 others
     = note: required because of the requirements on the impl of `LoadQuery<'_, _, Payment>` for `schema::payment::table`
note: required by a bound in `diesel::RunQueryDsl::load`
    --> /home/serge/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-2.0.0/src/query_dsl/mod.rs:1499:15
     |
1499 |         Self: LoadQuery<'query, Conn, U>,
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `diesel::RunQueryDsl::load`

### Steps to reproduce

diesel::table! {
    payment (id) {
        id -> Int8,
        amount_amount -> Numeric,
        amount_currency -> Int4,
        account -> Text,
        //transaction_date -> Nullable<Date>,
        //posting_date -> Nullable<Date>,
        billing_cycle -> Nullable<Int8>,
    }
}

use crate::schema::payment::dsl as dsl2;
use dsl2::*;
use chrono::NaiveDate;
use rust_decimal::*;

#[derive(Debug, Clone, Default, Queryable)]
#[diesel(table_name = payment)]
pub struct Payment {
    pub id: i64,
    pub amount_amount: Decimal,
    pub amount_currency: i32,
    pub account: String,
    //pub transaction_date: Option<NaiveDate>,
    //pub posting_date: Option<NaiveDate>,
    pub billing_cycle: Option<i64>,
}

pub fn get_payments(connection: &mut PgConnection) -> Vec<Payment> {
    payment.load::<Payment>(connection).expect("Error getting payments")
}
## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by qarmin** [comment] 2022-09-09 08:54
The problem is with nullable, if you remove it 
`id -> Nullable<Integer>` -> `id -> Integer`
then everything should work

**Comment by MysteryCoder456** [comment] 2022-09-11 16:01
I'm facing this issue as well. Is there any workaround or fix?

**Comment by sergeken** [comment] 2022-09-11 19:37
Change the nullable clause is not a fix but a workaround.  As the data element can be null and hence Option<None> in rust this does work.  I consider this bug a showstopper for diesel 2.0 and stay with the 1.* series.

**Comment by weiznich** [comment] 2022-09-17 10:43
Support for using rust_decimal types with diesel is provided by rust_decimal and not by diesel. [crates.io](https://crates.io/crates/rust_decimal/1.26.1/dependencies) shows that the current rust_decimal release depends on diesel 2.0.0-rc.1 and not on diesel 2.0.0, so its expected not to work. Please raise this issue on the rust_decimal issue tracker because that needs to be fixed on their side. 

As for the ”fix" of just removing the nullable wrapper: Please provide a minimal example of that, including your cargo.toml and cargo.lock files. This sounds like a possible bug.

Closed as this is not an diesel issue for the reasons outlined above.

**Closed** 2022-09-17 10:43 UTC
Labels: bug

**Comment by sergeken** [comment] 2022-09-21 16:47
The hint towards rust_decimal solved almost all my issues in my project but it does solve it for the code sample in this PR.  The fix was to use features = ["db-diesel2-postgres"].
As it was the case with this PR, I am battling the compiler errors that reminds me so much the C++ template error messages to understand the root cause of my outstanding compile errors.

**Comment by weiznich** [comment] 2022-09-21 18:17
@sergeken Suggestions on a better error message are welcome. Otherwise we cannot do much here as this specific integration is not maintained by diesel.
