### ISSUE TITLE
Performance regression when getting multiple connections with `r2d2::Pool`

### ISSUE THREAD

**Issue by heyrict** [diesel-rs/diesel#3156] opened 2022-05-01 08:05 UTC
### Versions

- **Rust:** rustc 1.62.0-nightly (e85edd9a8 2022-04-28)
- **Diesel:** v2.0.0-rc0
- **Database:** postgresql
- **Operating System** Linux 5.17.3-arch1-1

### Feature Flags

- **diesel:** ["postgres", "r2d2"]

## Problem Description

As is reported in #3144, performance regression is observed when upgrading `diesel` from `v1.4.8` to `v2.0.0-rc0`. Aggregation queries (e.g. `count(*)` are particularly affected, while the performance hit on normal queries is minimal.

### What is the expected output?

The performance of `v2.0.0-rc0` should be on par with `v1.4.8`.

### What is the actual output?

`cargo bench` output of `table.filter(id.eq(1)).count().get_result()`:

| hash | setup | perf |
|---|---|---|
| [d0bbda8](https://github.com/heyrict/diesel-aggr-sample/tree/d0bbda8a7066cf9b310e3beed2eece6418faeec9) |diesel 1.4 + r2d2| 185,936 ns/iter (+/- 15,282) |
| [599c492](https://github.com/heyrict/diesel-aggr-sample/tree/599c4923f1832fbafaaac33e6df75f6db8815e84) |diesel 2.0 + r2d2| 1,388,410 ns/iter (+/- 158,035) |
| [d3c23ba](https://github.com/heyrict/diesel-aggr-sample/tree/d3c23ba13a3202e59e28e0525a5cc7f0f40f461c) |diesel 1.4 - r2d2| 103,562 ns/iter (+/- 2,997) |
| [58d1210](https://github.com/heyrict/diesel-aggr-sample/tree/58d1210e65ac3ba2dc7e52b5b77853d323c23f9f) |diesel 2.0 - r2d2| 109,238 ns/iter (+/- 5,887) |

### Steps to reproduce

The minimal reproduction sample is [here](https://github.com/heyrict/diesel-aggr-sample).

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2022-05-02 14:42
This is caused by broken `R2D2Connection::is_broken` implementations in diesel. Those result in marking any connection as broken as soon as it is checked into the pool again. In turn that results in not reusing connections at all, so that the "pool" reestablish a new connection every time you checked out an connection from the pool.

https://github.com/diesel-rs/diesel/pull/3159 addresses this. Can you verify that this solves the issue for you?

**Comment by heyrict** [comment] 2022-05-03 01:24
I've changed the title to reflect the actual bug. Can confirm the bug is fixed with your PR. Thank you for debugging this :+1:

**Closed** 2022-05-03 17:20 UTC
Labels: bug
