### ISSUE TITLE
Feature: skip fields when deriving `AsChangeset`

### ISSUE THREAD

**Issue by Diggsey** [diesel-rs/diesel#1944] opened 2019-01-04 15:48 UTC
Its convenient to use the same struct sometimes when fetching and updating data (to avoid having to convert one into another) but sometimes you only want to update some of the fields.

It would be useful to be able to mark some fields as ignored for the purposes of deriving `AsChangeset`.

eg.
```rust
#[derive(Queryable, Identifiable, Debug, Clone, AsChangeset)]
pub struct FooBar {
    pub id: Uuid,
    #[changeset_options(skip = true)]
    pub immutable_field: i32,
    pub mutable_field: i32,
}
```

**Comment by sgrif** [comment] 2019-01-04 17:40
Duplicate of #860

**Closed by sgrif** 2019-01-04 17:40 UTC
