### ISSUE TITLE
Macros not resolved by default when generated by cli

### ISSUE THREAD

**Issue by hasezoey** [diesel-rs/diesel#3065] opened 2022-03-02 14:31 UTC
### Versions

- **Rust:** 1.59
- **Diesel:** 1.4.8
- **Database:** sqlite
- **Operating System** linux
- Edition: 2021

### Feature Flags

- **diesel:** sqlite

## Problem Description

`schema.rs` generated by `diesel-cli` does not resolve macros, error `cannot find macro `table` in this scope`

and when manually adding `use diesel::table` it starts to error about unresolved macros `__diesel_parse_table`

the only way i could currently achieve no errors is by using
```rs
#[macro_use]
extern crate diesel;
```

which should not be required to be done

### What are you trying to accomplish?
basic diesel setup

### What is the expected output?
no errors

### What is the actual output?
mentioned errors

### Are you seeing any additional errors?
as listed above

### Steps to reproduce

1. create a new project (`mkdir test_diesel && cd test_diesel && cargo init --bin .`)
2. verify to use edition 2021 (i dont know if necessary)
3. add diesel as a dependency (like `diesel = { version = "1.4", features = ["sqlite"] }`)
4. create a migration with a table (`diesel setup && diesel migration generate initial`)
5. run `diesel migration run`
6. add `mod schema` to `main.rs`
7. run `cargo build`
8. observe output
9. change from `table!` to `diesel::table!` or add line `use diesel::*` before
10. run `cargo build`
11. observe output again

example table in migrations:
```sql
CREATE TABLE test (
    _id INTEGER NOT NULL PRIMARY KEY,
     title VARCHAR NOT NULL
);
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

kinda similar to #2874, but this is a bug report not a question

**Comment by weiznich** [comment] 2022-03-02 14:34
Duplicate of https://github.com/diesel-rs/diesel/issues/2537 and https://github.com/diesel-rs/diesel/issues/1764 and quite a lot of other reports.

**Closed as completed by weiznich** 2022-03-02 14:34 UTC
Labels: bug

**Comment by hasezoey** [comment] 2022-03-02 14:37
> Duplicate of https://github.com/diesel-rs/diesel/issues/2537 and https://github.com/diesel-rs/diesel/issues/1764 and quite a lot of other reports.

from what i can tell, diesel *can* do steps to prevent this, like:
instead of automatically adding `table!`, instead doing `diesel::table!` and otherwise importing all required things for the macro

**Comment by weiznich** [comment] 2022-03-02 14:41
That's all fine. Nevertheless does the current diesel release require `#[macro_use] extern crate diesel;`. Doing something else was consider a breaking change back than so we postpone that for a future breaking release. Please checkout the linked discussions first.

**Comment by weiznich** [comment] 2022-03-02 16:06
> is there currently a ETA on when that will be released?

We do not give an ETA on when certain features will be released. At least nothing else then: When it's done.

> as a addition: i opened up a new issue, because the old ones were closed and so i though were kinda unrelated issues
> 
> so i would recommend to either tag them with "wont fix" or letting one stay open with a "breaking change" and added to a milestone

Closed issues are closed because either they are fixed or they are not accepted. Opening the same issue again and again will not change anything. So stop doing that. 
In this specific case: The issue was first not accepted as the relevant feature was only available in nightly rust. After it become stable someone submitted a PR to fix this. This means it is implemented on the master branch, but not released yet. But this means there is really no reason to keep the issue open as any open issue should indicate something that people can work on.

> also it seems like your examples (like for sqlite) do not do this, for example this one which i am currently trying to follow along didnt notice that master was already to 2.0.0 and not like the released version 1.4

In addition to the point that the master branch contains breaking changes: Take a look at our webpage. It has guides that explain and link the correct examples for the latest release.

**Comment by hasezoey** [comment] 2022-03-02 16:19
> Closed issues are closed because either they are fixed or they are not accepted. Opening the same issue again and again will not change anything. So stop doing that.

this was not my intention.

i had done it because i had understood it as follows:
- discussions i had found (linked in the issue opening) were *questions* (and also for about a year not responded to), where as this is a *bug report*
- issues i had found were "closed", which should mean that they are "fixed" (if no tags) or "wont fix" (should also have a appropriate tag), and so i though that they were old issues and i just encountered a new instance of this (where it is common practice to open a new issue instead of necro-posting)
- some issues were closed because of not respecting the issue template

> In addition to the point that the master branch contains breaking changes: Take a look at our webpage. It has guides that explain and link the correct examples for the latest release.

i had followed the guide [Getting Started](https://diesel.rs/guides/getting-started) with the link to `https://github.com/diesel-rs/diesel/tree/master/examples/` (which is the first hyper-link in the text, named `examples`), where i tried to follow along with the sqlite example
but after having noticed that the master branch was actually on a different major version, i edited my last comment to mention that

i personally would expect a guide to either be:
- fixed to a specific version
- being updated for the latest *stable* version (which 2.0.0 does not seem to be yet

(note: the guide itself references version `1.4.4` to be used, but links to the master examples for the other non-postgres examples, which were in this case in a different major version)

**Comment by weiznich** [comment] 2022-03-02 19:18
Seems like you just hit a ”broken" link in our guides. Thanks for the report. Mind submitting a fix here: https://github.com/sgrif/diesel.rs-website/blob/master/src/guides/getting-started.md ?
