### ISSUE TITLE
Selectable derive breaks embedded optional fields

### ISSUE THREAD

**Issue by toxeus** [diesel-rs/diesel#3173] opened 2022-05-06 10:51 UTC
### Versions

- **Rust:** 1.60.0
- **Diesel:** latest master
- **Database:** sqlite
- **Operating System**: Linux

### Feature Flags

- **diesel:** sqlite

## Problem Description

For a struct with an embedded optional struct the `Selectable` derive doesn't work correctly and, therefore, the compilation fails.
There is an unit test that tests exactly this scenario but the underlying diesel schema definition mistakenly is lacking the `Nullable` wrapper for the optional field.

### What are you trying to accomplish?

Compile the code without errors.

### What is the expected output?

Successful compilation.

### What is the actual output?

>    Compiling diesel_derives v2.0.0-rc.0 (/home/user/src/diesel/diesel_derives)
error[E0277]: the trait bound `expression::select_by::SelectBy<selectable::embedded_option::A, Sqlite>: load_dsl::private::CompatibleType<_, Sqlite>` is not satisfied
    --> diesel_derives/tests/selectable.rs:95:10
     |
95   |         .get_result(conn);
     |          ^^^^^^^^^^ the trait `load_dsl::private::CompatibleType<_, Sqlite>` is not implemented for `expression::select_by::SelectBy<selectable::embedded_option::A, Sqlite>`
     |
     = help: the following implementations were found:
               <expression::select_by::SelectBy<U, DB> as load_dsl::private::CompatibleType<U, DB>>
     = note: required because of the requirements on the impl of `LoadQuery<'_, _, _>` for `SelectStatement<FromClause<my_structs_nullable::table>, diesel::query_builder::select_clause::SelectClause<expression::select_by::SelectBy<selectable::embedded_option::A, Sqlite>>>`
note: required by a bound in `get_result`
    --> /home/user/src/diesel/diesel/src/query_dsl/mod.rs:1652:15
     |
1652 |         Self: LoadQuery<'query, Conn, U>,
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `get_result`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `diesel_derives` due to previous error

### Are you seeing any additional errors?

No.

### Steps to reproduce

Add the following schema definition

```rust
table! {
    my_structs_nullable (foo) {
        foo -> Integer,
        bar -> Nullable<Integer>,
    }
}
```

and patch [this test](https://github.com/diesel-rs/diesel/blob/99f209f383acbbef36c0ef5888e8dc3a0d115af1/diesel_derives/tests/selectable.rs#L69-L88) to use `my_structs_nullable` instead.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2022-05-20 08:43
Thanks for this bug report. I spend some time to investigate this.
I came to the conclusion that this is expected behaviour. Your inner field is not nullable in this case, while the corresponding field in your schema is nullable. This is a basic type mismatch, which always is considered as incompatible type. I would suggest to either wrap the inner type also in an Option or provide a manual Selectable impl
that does the "right" thing there.

See #3181 for more details.

Closed as not a bug.

**Closed by weiznich** 2022-05-20 08:43 UTC
Labels: bug
