### ISSUE TITLE
[Opinion] Impossible to figure out error messages

### ISSUE THREAD

**Issue by zwhitchcox** [diesel-rs/diesel#2450] opened 2020-07-04 18:05 UTC
### Versions

- **Rust:** rustc 1.46.0-nightly (feb3536eb 2020-06-09)
- **Diesel:** 1.4.4
- **Database:** postgres
- **Operating System** windows

### Feature Flags

- **diesel:**
postgres, r2d2

## Problem Description

Ok, so, I'm just wondering if I'm going down the wrong user path, because I just spent 20 minutes trying to diagnose an error and figured out the code:

```rs
        use schema::scripts::dsl::*;
        let result = diesel::delete(
                scripts
                    .filter(id.eq("1"))
            )
            .execute(session.db())
            .map_err(|e| {
                debug!("{:?}", e);
                format!("Could not delete script.")
            });
```

was bugged because you can't use a string instead of a number when id is a number. That's all well and good, but this is the error message it gave me:

```
the trait bound `diesel::query_builder::SelectStatement<schema::scripts::table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<schema::scripts::columns::id, &str>>>: diesel::query_builder::IntoUpdateTarget` is not satisfied

the trait `diesel::query_builder::IntoUpdateTarget` is not implemented for `diesel::query_builder::SelectStatement<schema::scripts::table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<schema::scripts::columns::id, &str>>>`

help: the following implementations were found:
<diesel::query_builder::SelectStatement<F, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, W> as diesel::query_builder::IntoUpdateTarget>rustc(E0277)
```
And I read through the api docs to try to figure out exactly what I was doing wrong, and there is basically no way to figure out from the docs, I just had to guess. Although to be fair it was the example in the docs that made me guess it needed to be an integer.

But I mean, am I just stupid, or are most users going down a different path where they would already understand this before they run into an error? I mean, I just want to make sure I'm following the standard path, because I don't see how the average person could figure out how to use this library without just reading the source code.

I talked to my friend, and he told me he just read the source code.

Maybe this is just the type of error that will always be a pain, but you only have to learn it once, so it's not a big deal?

### What is the expected output?

It would be nice if it said something like "we expected an integer"

### What is the actual output?

```
the trait bound `diesel::query_builder::SelectStatement<schema::scripts::table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<schema::scripts::columns::id, &str>>>: diesel::query_builder::IntoUpdateTarget` is not satisfied

the trait `diesel::query_builder::IntoUpdateTarget` is not implemented for `diesel::query_builder::SelectStatement<schema::scripts::table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<schema::scripts::columns::id, &str>>>`

help: the following implementations were found:
<diesel::query_builder::SelectStatement<F, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, W> as diesel::query_builder::IntoUpdateTarget>rustc(E0277)
```

**Comment by weiznich** [comment] 2020-07-04 19:22
Unfortunately there is no way to control rustc's error messages, so we cannot just print "we expect an integer" there. Beside of that I do not think that is even possible to give such a concrete error message in this case, the best that can be printed is that `str` does not implement `AsExpression<Integer>` as there are possibly multiple types that are supported in this position. I assume rustc generates this error message, because there can be multiple impls for a given trait and for the general case rustc cannot know which impl should be choosen to generate the error message. If it would randomly guess there, that could lead to situations where it suggests something completely wrong, because it guessed the wrong impl (even that happens from time to time).


Closed as this is not actionable for the diesel team. I agree that the error message could be better, but for the reasons explained above I do not see any way to improve them. If you think rustc could report some better message here you should probably submit an bug report there.

**Closed by weiznich** 2020-07-04 19:22 UTC

**Comment by zwhitchcox** [comment] 2020-07-05 07:07
Ok, thanks for letting me know. I wasn't sure if there was a solution or not, but was just trying to improve the experience for newcomers, as I was almost like, "I guess I just can't use diesel". But ok, thanks anyway

**Comment by weiznich** [comment] 2020-07-05 09:12
I'm not sure how we can improve the situation here for newcomers, as we do not have much control about the error messages. If you have any concrete suggestions feel free to share them.

**Comment by Mingun** [comment] 2020-07-05 09:34
One of possible solutions can be procedural macro where you write SQL code directly and you have full control on error messages

**Comment by weiznich** [comment] 2020-07-05 09:50
@Mingun Feel free to provide such a macro. For me it is clearly out of scope of diesel to implement parsers for all the subtily different SQL dialects out there.

**Comment by zwhitchcox** [comment] 2020-07-06 14:52
I wish I could be of more assistance, but I'm pretty new to Rust in general. I will keep that in mind though as I progress...it does seem to be a trend that error messages pop up that really aren't very helpful, at least to me, and I end up having to just find an example that works and work backward from there trying to integrate it into my codebase. Maybe this is more of an overall larger problem with Rust and very difficult to overcome because of the borrow checker. I do know the Rust team is trying to work on making better error messages, so, I guess we'll just wait and see what they come up with!

**Comment by weiznich** [comment] 2020-07-07 08:26
So I sat down and tried the example to look for variants to improve the error messages here. For reference I've used the following modified code (just made in compile in a minimal reproducible environment):
```rust
#[macro_use]
extern crate diesel;

use diesel::prelude::*;

table! {
    scripts {
        id -> Integer,
        name -> Text,
    }
}

fn test(conn: &PgConnection) {
    let result = diesel::delete(scripts::table.filter(scripts::id.eq("1")))
        .execute(conn)
        .map_err(|e| {
            format!("Could not delete script.")
        });
}

```

While trying to compile this snippet rustc emits the following error messages:
```
    Checking diesel_test v0.1.0 (/tmp/diesel_test)
error[E0277]: the trait bound `str: diesel::Expression` is not satisfied
  --> src/main.rs:14:70
   |
14 |     let result = diesel::delete(scripts::table.filter(scripts::id.eq("1")))
   |                                                                      ^^^ the trait `diesel::Expression` is not implemented for `str`
   |
   = note: required because of the requirements on the impl of `diesel::Expression` for `&str`
   = note: required because of the requirements on the impl of `diesel::expression::AsExpression<diesel::sql_types::Integer>` for `&str`

error[E0277]: the trait bound `str: diesel::Expression` is not satisfied
  --> src/main.rs:14:55
   |
14 |     let result = diesel::delete(scripts::table.filter(scripts::id.eq("1")))
   |                                                       ^^^^^^^^^^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `str`
   |
   = note: required because of the requirements on the impl of `diesel::Expression` for `&str`
   = note: required because of the requirements on the impl of `diesel::Expression` for `diesel::expression::operators::Eq<scripts::columns::id, &str>`
   = note: required because of the requirements on the impl of `diesel::query_dsl::filter_dsl::FilterDsl<diesel::expression::operators::Eq<scripts::columns::id, &str>>` for `diesel::query_builder::SelectStatement<scripts::table>`

error[E0277]: the trait bound `str: diesel::expression::NonAggregate` is not satisfied
  --> src/main.rs:14:55
   |
14 |     let result = diesel::delete(scripts::table.filter(scripts::id.eq("1")))
   |                                                       ^^^^^^^^^^^^^^^^^^^ the trait `diesel::expression::NonAggregate` is not implemented for `str`
   |
   = note: required because of the requirements on the impl of `diesel::expression::NonAggregate` for `&str`
   = note: required because of the requirements on the impl of `diesel::expression::NonAggregate` for `diesel::expression::operators::Eq<scripts::columns::id, &str>`
   = note: required because of the requirements on the impl of `diesel::query_dsl::filter_dsl::FilterDsl<diesel::expression::operators::Eq<scripts::columns::id, &str>>` for `diesel::query_builder::SelectStatement<scripts::table>`

error[E0277]: the trait bound `diesel::query_builder::SelectStatement<scripts::table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<scripts::columns::id, &str>>>: diesel::query_builder::IntoUpdateTarget` is not satisfied
   --> src/main.rs:14:33
    |
14  |     let result = diesel::delete(scripts::table.filter(scripts::id.eq("1")))
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `diesel::query_builder::IntoUpdateTarget` is not implemented for `diesel::query_builder::SelectStatement<scripts::table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<scripts::columns::id, &str>>>`
    | 
   ::: /home/weiznich/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.5/src/query_builder/functions.rs:135:18
    |
135 | pub fn delete<T: IntoUpdateTarget>(source: T) -> DeleteStatement<T::Table, T::WhereClause> {
    |                  ---------------- required by this bound in `diesel::delete`
    |
    = help: the following implementations were found:
              <diesel::query_builder::SelectStatement<F, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, W> as diesel::query_builder::IntoUpdateTarget>

error[E0277]: the trait bound `diesel::query_builder::SelectStatement<scripts::table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<scripts::columns::id, &str>>>: diesel::query_builder::IntoUpdateTarget` is not satisfied
  --> src/main.rs:14:18
   |
14 |     let result = diesel::delete(scripts::table.filter(scripts::id.eq("1")))
   |                  ^^^^^^^^^^^^^^ the trait `diesel::query_builder::IntoUpdateTarget` is not implemented for `diesel::query_builder::SelectStatement<scripts::table, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, diesel::query_builder::where_clause::WhereClause<diesel::expression::operators::Eq<scripts::columns::id, &str>>>`
   |
   = help: the following implementations were found:
             <diesel::query_builder::SelectStatement<F, diesel::query_builder::select_clause::DefaultSelectClause, diesel::query_builder::distinct_clause::NoDistinctClause, W> as diesel::query_builder::IntoUpdateTarget>

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `diesel_test`.

To learn more, run the command again with --verbose.

Cargo-Process exited abnormally with code 101 at Tue Jul  7 10:11:53

```

So instead of getting a single error message like reported in the OP, we are getting 6 errors here. A normal strategy for rustc error messages is starting to read them with the first one first, because later error messages can be based on false assumption from rustc (which is the case here). So for readibility here the first error message again:
```
error[E0277]: the trait bound `str: diesel::Expression` is not satisfied
  --> src/main.rs:14:70
   |
14 |     let result = diesel::delete(scripts::table.filter(scripts::id.eq("1")))
   |                                                                      ^^^ the trait `diesel::Expression` is not implemented for `str`
   |
   = note: required because of the requirements on the impl of `diesel::Expression` for `&str`
   = note: required because of the requirements on the impl of `diesel::expression::AsExpression<diesel::sql_types::Integer>` for `&str`
```
While this error message is not great, it's definitively not bad as it:
* Points to the correct span
* Correctly lists the issue as concrete as possible (the second node explicitly says that there is no impl `AsExpression<Integer> for &str`

The next four error messages are now based on the assumption that `&str` implements `Expression` which is wrong from diesels point of view. From rustc's point of view this makes sense, as there is no concrete impl for `AsExpression<Integer>` for `&str` while there is a generic one for all types that implement `Expression`, so it will suggest that the `Expression` impl is missing and base the following analysis on this assumption. (I assume that generally this is useful behavior from rustc side as I can definitively also see cases where the error messages get more concrete in such cases)

**Comment by zwhitchcox** [comment] 2020-07-07 13:40
This is fantastic!

I do actually believe this is the ideal solution, and I don't think I could possibly suggest anything better.

Of course, it would be better if it said that it expected an integer directly, but I think that would probably cause other problems, kind of like overfitting the data. 

With this solution, it makes much more intuitive sense to me, because I can see that `diesel::Expression` implements the `Integer`. It kind of tells me that although, a string would be a valid `diesel::Expression`, this particular one is expecting an `i32`, which I think is very clear. Great job!
