### ISSUE TITLE
Diesel 1.3.0 fails to build with the recent nightly

### ISSUE THREAD

**Issue by syssecfsu** [diesel-rs/diesel#1729] opened 2018-05-24 01:51 UTC
### Versions

- **Rust:** rustc 1.28.0-nightly (71e87be38 2018-05-22)
- **Diesel:** 1.3.0 from crate.io
- **Database:** Sqlite
- **Operating System** Mac OS X 10.13.4

### Feature Flags

- **diesel:** "sqlite", "32-column-tables"

## Problem Description
Diesel 1.3.0 cannot be built on the recent nightly. The error message is shown as:

```
error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` is not satisfied
  --> /.../.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Add` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable
```

**Comment by Deedasmi** [comment] 2018-05-24 02:54
Duplicate of #1700 , #1701, #1705, #1711, #1722

**Closed** 2018-05-24 03:12 UTC
