### ISSUE TITLE
diesel setup doesn't work in powershell 7

### ISSUE THREAD

**Issue by ZiiMakc** [diesel-rs/diesel#2471] opened 2020-07-29 09:33 UTC
## Setup

### Versions

- **Operating System: windows 10**

## Problem Description

If i run `diesel setup` in powershell 7 nothing happens, but same works fine in command promt. What can be an issue?

## Checklist

- [v] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [v] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2020-07-29 09:43
Duplicate of #2015. 
Please try to search the issue tracker first for duplicated issues before you open a new issue. The check mark is there for an reason.

**Closed by weiznich** 2020-07-29 09:43 UTC
