### ISSUE TITLE
Using Queryable without #[macro_use]

### ISSUE THREAD

**Issue by kdubovikov** [diesel-rs/diesel#2386] opened 2020-05-07 05:43 UTC
Getting started guide suggests using `extern crate` with `#[macro_use]`. This is no longer necessary since Rust 2018, but the documentation is missing the way to set up the library without `#[macro_use]`. Is this intentional? 
I think that I can avoid `#[macro_use]` by using `diesel_derives` crate, but I have not managed to do this correctly. Could someone give me a hint? Should I include it as a dependency, or there is a better way to import derivable macro directly from the `diesel` crate?

The library documentation might be updated with a more idiomatic way to use the macro as a result of this discussion.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2020-05-07 07:41
Duplicate of  #1764

**Closed by weiznich** 2020-05-07 07:41 UTC
