### ISSUE TITLE
Feature: Automatic case conversion of custom SQL types

### ISSUE THREAD

**Issue by Diggsey** [diesel-rs/diesel#2318] opened 2020-03-02 14:30 UTC
It is customary in postgres to name types using snake-case, eg. `my_custom_type`. The default diesel `print-schema` behaviour is to map this to `My_custom_type` which doesn't follow the Rust naming convention for types.

This can be solved using the `patch` feature, but it would be more convenient if `print_schema` could be configured to perform automatic case conversion, similar to serde's `rename_all` attribute.

**Comment by weiznich** [comment] 2020-03-02 15:08
Duplicate of https://github.com/diesel-rs/diesel/issues/2012

**Closed by weiznich** 2020-03-02 15:08 UTC
