### ISSUE TITLE
sqlite `Integer` columns associated with wrong rust data type.

### ISSUE THREAD

**Issue by quickdudley** [diesel-rs/diesel#2467] opened 2020-07-27 01:23 UTC
### Versions

- **Rust:**: 1.43.1
- **Diesel:**: 1.4.1
- **Database:**: sqlite 3.28.0
- **Operating System**: Mac OS X

### Feature Flags

- **diesel:**

## Problem Description

The diesel schema generator associates `Integer` columns with the `diesel::sql_types::Integer` type. The trait implementations for `diesel::deserialize::FromSql` all treat this as representing `i32`, but as per the sqlite documentation this column type can represent up to 64 bits.

Furthermore the `FromSql` instances for `i64` are all for `BigInt`; which is not a valid column type in sqlite.

### What are you trying to accomplish?

Derive `Queryable` instances for a struct which uses the same numeric type as the underlying database.

### Are you seeing any additional errors?

The following compilation error occurs when attempting to use `i64` numbers with the sqlite backend:
```
the trait `diesel::deserialize::FromSql<diesel::sql_types::Integer, diesel::sqlite::Sqlite>` is not implemented for `i64`
```

#### In migration:

```
CREATE TABLE tasks(id INTEGER PRIMARY KEY);
```

### In models.rs

```
#[derive(Queryable)]
pub struct Task {
    pub id: i64,
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2020-07-27 06:35
Duplicate of #852

**Closed by weiznich** 2020-07-27 06:35 UTC
