### ISSUE TITLE
Diesel CLI fails to install on ARM

### ISSUE THREAD

**Issue by humb1t** [diesel-rs/diesel#2211] opened 2019-10-27 09:05 UTC
### Versions

- rustc 1.38.0 (625451e37 2019-09-23)
- diesel_cli v1.4.0
- libpq-dev is already the newest version (11.5-1+deb10u1)
- Linux humb1trpi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux

### Feature Flags

- --no-default-features --features postgres

## Problem Description

Diesel CLI installation fails.

### What are you trying to accomplish?

Install diesel_cli

### What is the expected output?

Diesel CLI installation succeeds.

### What is the actual output?

```bash
    Updating crates.io index
  Installing diesel_cli v1.4.0
  Downloaded syn v1.0.6
   Compiling proc-macro2 v1.0.6
   Compiling libc v0.2.65
   Compiling cc v1.0.46
   Compiling unicode-xid v0.2.0
error: Could not compile `unicode-xid`.

Caused by:
  process didn't exit successfully: `rustc --crate-name unicode_xid /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-xid-0.2.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="default"' -C metadata=7ba4255d362b475e -C extra-filename=-7ba4255d362b475e --out-dir /tmp/cargo-installtt5dU3/release/deps -L dependency=/tmp/cargo-installtt5dU3/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: Could not compile `libc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.65/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=e7a45c6bd9cf2e76 -C extra-filename=-e7a45c6bd9cf2e76 --out-dir /tmp/cargo-installtt5dU3/release/build/libc-e7a45c6bd9cf2e76 -L dependency=/tmp/cargo-installtt5dU3/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: failed to prepare thin LTO module: file doesn't start with bitcode header

thread '<unnamed>' panicked at 'src/librustc_codegen_ssa/back/write.rs:1545: worker thread panicked', src/librustc/util/bug.rs:37:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error

free(): invalid next size (fast)
error: Could not compile `proc-macro2`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name build_script_build /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.6/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=7e8798823c7101b3 -C extra-filename=-7e8798823c7101b3 --out-dir /tmp/cargo-installtt5dU3/release/build/proc-macro2-7e8798823c7101b3 -L dependency=/tmp/cargo-installtt5dU3/release/deps --cap-lints allow` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `diesel_cli v1.4.0`, intermediate artifacts can be found at `/tmp/cargo-installtt5dU3`

Caused by:
  Could not compile `cc`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name cc /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.46/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=fe52e0437cc3b443 -C extra-filename=-fe52e0437cc3b443 --out-dir /tmp/cargo-installtt5dU3/release/deps -L dependency=/tmp/cargo-installtt5dU3/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)

```

### Steps to reproduce

Use Raspberry Pi 4 and run `cargo install diesel_cli --no-default-features --features postgres`

## Checklist

- [ +] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ +] This issue can be reproduced on Rust's stable channel.

**Comment by weiznich** [comment] 2019-10-27 15:47
Probably a duplicate of https://github.com/rust-lang/rust/issues/65649.
Certainly no diesel but a rustc issue because the compiler crashed.

**Closed by weiznich** 2019-10-27 15:47 UTC

**Comment by humb1t** [comment] 2019-10-27 18:19
@weiznich thanks!
