### ISSUE TITLE
CREATE TABLE foo( t text PRIMARY KEY ) fails with Table foo has no primary key

### ISSUE THREAD

**Issue by SamuelMarks** [diesel-rs/diesel#1970] opened 2019-01-29 06:06 UTC
## Setup
```bash
$ cargo new a && cd $_
$ diesel setup
$ diesel migration generate create_foo
```

#### up.sql
```sql
CREATE TABLE foo( t text PRIMARY KEY );
```
#### down.sql
```sql
DROP TABLE foo;
```

### Versions

- **Rust:**
rustc 1.33.0-nightly (bf669d1e3 2019-01-25)
- **Diesel:**
diesel 1.4.0
- **Database:**
PostgreSQL 11.1
- **Operating System**
macOS Mojave 10.14.2 (18C54)
### Feature Flags
None
- **diesel:**
diesel 1.4.0

## Problem Description
```bash
$ diesel migration run
Running migration 2019-01-29-055113_create_foo
Diesel only supports tables with primary keys. Table foo_tbl has no primary key
```

### What are you trying to accomplish?
Create a simple table

### What is the expected output?
Success

### What is the actual output?
> Diesel only supports tables with primary keys. Table foo_tbl has no primary key

### Are you seeing any additional errors?
No

### Steps to reproduce
```bash
$ cargo new a && cd $_
$ diesel setup
$ diesel migration generate create_foo
```

Then edit the `up.sql` and `down.sql` to match above.

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by kamikaz1k** [comment] 2019-11-05 04:40
I see the same issue, even though the migration ran successfully...

**Comment by weiznich** [comment] 2020-03-09 10:09
I cannot reproduce this with the current diesel release and the provided information, therefore I'm closing this issue. Feel free to add more information how this issue occurs.

**Closed by weiznich** 2020-03-09 10:09 UTC

**Comment by SamuelMarks** [comment] 2020-03-12 03:04
Confirmed that it now works. Good to see!
