### ISSUE TITLE
the trait bound `(Unsigned<BigInt>, Text, Text, Bool): load_dsl::private::CompatibleType<diesel_demo::models::Post, Mysql>` is not satisfied

### ISSUE THREAD

**Issue by ipomazkin** [diesel-rs/diesel#3501] opened 2023-02-02 20:29 UTC
## Setup
Here is full setup: https://github.com/ipomazkin/diesel-problem-02-02-2023

### Versions

- **Rust:**  1.67.0
- **Diesel:** 2.0.0
- **Database:** MySQL (8.0.30-macos12-arm64)
- **Operating System** MacOS 12 ARM64

### Feature Flags

- **diesel:**
- "mysql", "r2d2"

## Problem Description
I follow the guide (https://diesel.rs/guides/getting-started.html) and get this error:
```
   Compiling diesel v2.0.0
   Compiling diesel_demo v0.1.0 (/Users/ipomazkin/Projects/utils-cli/diesel-demo)
error[E0277]: the trait bound `(Unsigned<BigInt>, Text, Text, Bool): load_dsl::private::CompatibleType<diesel_demo::models::Post, Mysql>` is not satisfied
    --> src/bin/show_posts.rs:12:23
     |
12   |         .load::<Post>(connection)
     |          ----         ^^^^^^^^^^ the trait `load_dsl::private::CompatibleType<diesel_demo::models::Post, Mysql>` is not implemented for `(Unsigned<BigInt>, Text, Text, Bool)`
     |          |
     |          required by a bound introduced by this call
     |
     = help: the following other types implement trait `load_dsl::private::CompatibleType<U, DB>`:
               (ST0, ST1)
               (ST0, ST1, ST2)
               (ST0, ST1, ST2, ST3)
               (ST0, ST1, ST2, ST3, ST4)
               (ST0, ST1, ST2, ST3, ST4, ST5)
               (ST0, ST1, ST2, ST3, ST4, ST5, ST6)
               (ST0, ST1, ST2, ST3, ST4, ST5, ST6, ST7)
               (ST0, ST1, ST2, ST3, ST4, ST5, ST6, ST7, ST8)
             and 8 others
     = note: required for `SelectStatement<FromClause<table>, query_builder::select_clause::DefaultSelectClause<...>, ..., ..., ..., ...>` to implement `LoadQuery<'_, _, diesel_demo::models::Post>`
     = note: the full type name has been written to '/Users/ipomazkin/Projects/utils-cli/diesel-demo/target/debug/deps/show_posts-47e6ca2c485e3514.long-type-18179761263321942039.txt'
note: required by a bound in `diesel::RunQueryDsl::load`
    --> /Users/ipomazkin/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-2.0.0/src/query_dsl/mod.rs:1499:15
     |
1499 |         Self: LoadQuery<'query, Conn, U>,
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `diesel::RunQueryDsl::load`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `diesel_demo` due to previous error
```

### What are you trying to accomplish?
I'm trying to compile project, I'm following the official guide.

### What is the expected output?
It should compile :)

### What is the actual output?
It's not compiling :)

### Are you seeing any additional errors?
No

### Steps to reproduce
You can just clone my repo and try to compile. Link: https://github.com/ipomazkin/diesel-problem-02-02-2023

## Checklist

- [+] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [+] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-02-03 06:20
Duplicate of any of [these issues](https://github.com/diesel-rs/diesel/issues?q=is%3Aissue+CompatibleType)

(Our issue tracker is no support forum, so please open a question thread in the discussion forum if you need help)

**Closed by weiznich** 2023-02-03 06:20 UTC
Labels: bug
