### ISSUE TITLE
Unexpected null for non-null column - while using postgres hash partitions

### ISSUE THREAD

**Issue by phisk** [diesel-rs/diesel#2817] opened 2021-07-01 05:38 UTC
### Versions

- **Rust: 1.53.0
- **Diesel: 1.47
- **Database: Postgresql 13.3
- **Operating System: Debian 10.10

### Feature Flags

- **diesel: postgres, chrono

## Problem Description
"diesel migrations run" leads to a "Unexpected null for non-null column" - error - while using hash partitions
The error does not occur when the table is NOT split up.

### What are you trying to accomplish?
Split up a table into (many) partitions using postgres hash partition feature

### What is the expected output?
no error

### What is the actual output?
"Unexpected null for non-null column" 

### Are you seeing any additional errors?
no schema.rs is produced. It stays empty.

### Steps to reproduce
(I reduced the number of partitions to 1 (from 100) for readability reasons.
The error stays the same though)

up.sql:

```
-- Your SQL goes here
DROP TABLE IF EXISTS kurse_isin;
DROP TABLE IF EXISTS wertpapiere_isin;


CREATE TABLE IF NOT EXISTS wertpapiere_isin (
  ISIN CHAR(12) NOT NULL PRIMARY KEY,
  WKN CHAR(6),
  Symbol VARCHAR,
  NAME VARCHAR NOT NULL,
  LAND VARCHAR NOT NULL,
  Branche VARCHAR
);


CREATE TABLE IF NOT EXISTS kurse_isin (
  ISIN CHAR(12) NOT NULL,
  KLow NUMERIC,
  KHigh NUMERIC,
  KOpen Numeric,
  KClose Numeric,
  KADJ_CLOSE Numeric,
  KVolumen Numeric,
  Datum Date NOT NULL,
  PRIMARY KEY (isin, datum),
  CONSTRAINT fk_kurse_isin
    FOREIGN KEY(ISIN) 
	  REFERENCES wertpapiere_isin (ISIN)
) PARTITION BY HASH (ISIN);

create table kurse_isin_hash_p0
partition of kurse_isin
for values with (modulus 1, remainder 0);
```

```
down.sql:

-- This file should undo anything in `up.sql`

DROP TABLE IF EXISTS kurse_isin_hash_p0;
DROP TABLE IF EXISTS kurse_isin;
DROP TABLE IF EXISTS wertpapiere_isin;
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-07-01 07:07
I can confirm that this happens for `diesel-cli v1.4.1`, but it appears to be fixed on the master branch. Which makes this likely a duplicate of #1948 which is fixed by https://github.com/diesel-rs/diesel/pull/2073.

**Comment by phisk** [comment] 2021-07-01 08:01
Can confirm that it works with the master version of diesel-cli.
Is it advised to use the master instead of the 1.4.x branch these days. As the diesel-cli of branch 1.4.x seems to be quite "old" (13 month old)

**Comment by weiznich** [comment] 2021-07-01 08:14
> Is it advised to use the master instead of the 1.4.x branch these days. As the diesel-cli of branch 1.4.x seems to be quite "old" (13 months old)

Diesel cli 1.4.1 is the last officially supported release, which means that's the thing we primarily provide support for and guarantee stability. The master branch is a ever changing target till the next feature release. We don't give any stability guarantees there. We are interested in getting some early feedback on the features there, but we do not necessarily provide the same level on support/documentation/guides for that target than for the last release so you may be on your own there.

That written I close this issue now as this is fixed on master. Open issues represent something that isn't fixed there.

**Closed by weiznich** 2021-07-01 08:14 UTC
Labels: bug

**Comment by RocketDerp** [comment] 2023-08-28 23:26
I'm finding very few search engine hits for the quoted phrase "Unexpected null for non-null column" - I'm hours into trying to identify exactly *which column* is the problem non-null column! Anyway, commenting to say that.

**Comment by weiznich** [comment] 2023-08-30 09:37
@RocketDerp Commenting on closed old issues is discouraged. If you look for help please open a new question in the support forum including details about your problem. If you have suggestions for a new feature: Please open a new feature proposal outlining your feature/improvement. If you believe that you've hit an old diesel issue in a newer version: Please always include all necessary information to reproduce that bug.
