### ISSUE TITLE
The diesel 2.1.5 version cannot close the tls connection

### ISSUE THREAD

**Issue by 12Saturn** [diesel-rs/diesel#3996] opened 2024-04-19 08:41 UTC
### Versions

- **Rust:*1.75.0*
- **Diesel:*2.1.5*
- **Database:*mysql 8.0.36*
- **Operating System:*mac*
- **Mysql client:*8.0.22*

## Problem Description
When using diesel to connect to mysql, I do not want to use SSL connection, but adding ‘ssl_mode=disabled’ does not work

conn mysql :
```rust
#[tokio::main]
async fn main() {
              let database_url = "mysql://root:123456@127.0.0.1:3306/test?ssl_mode=disabled";
              let mut tmp_conn = diesel::mysql::MysqlConnection::establish(&database_url)
                  .expect("Failed to connect db");
              tmp_conn.run_pending_migrations(MYSQL_MIGRATIONS).unwrap();
              let manager = AsyncDieselConnectionManager::<AsyncMysqlConnection>::new(database_url);
              let pool = MySqlPool::builder()
                  .build(manager)
                  .await
                  .expect("Failed to create db pool");
}
```

```cargo.toml
tokio = { version = "1.27.0", features = ["sync", "rt", "time", "macros", "rt-multi-thread"] }
diesel = { version = "2.1.5", features = ["mysql", "postgres", "serde_json", "chrono"] }
diesel-async = { version = "0.4.1", features = ["bb8", "postgres", "mysql"] }
diesel_migrations = "2.1.0"
```

 wifeshark Indicates the result of packet capture：

![sc_20240419163931](https://github.com/diesel-rs/diesel/assets/161667945/4221cc33-674c-4242-89b3-fa8aff6b5c6d)

**Comment by weiznich** [comment] 2024-04-19 08:49
Thanks for opening this bug report. Can you please complete the bug template as otherwise this report is not actionable for anyone due to missing details. Additionally you want to provide more details that just stating that "something" does not work. You might want to include additional details like a minimal reproducible example, information about your database system and your client libraries and your environment configuration.

**Comment by 12Saturn** [comment] 2024-04-19 12:12
Thank you very much for your reply. I have added the test examples and test results

**Comment by weiznich** [comment] 2024-04-19 12:18
Thanks for adding the details. I'm sorry but there are still some important points missing until this becomes actionable:

* Your application uses connections from `diesel_async`  and `diesel`. Can you clarify if that problem happens with the connection from `diesel_async` or from `diesel`. In the former case that's the wrong issue tracker here.
* It's still missing important information about the exact version of mysqlclient and mysql you are using, I fear without that it's not possible to do anything

**Comment by weiznich** [comment] 2024-04-19 12:49
Thanks for confirming that this is in fact a diesel and not a diesel-async issue. That still leaves the important question about your libmysqlclient unanswered.

**Comment by 12Saturn** [comment] 2024-04-20 06:33
I'm sorry I forgot to add yesterday, libmysqlclient version is 8.0.22

**Comment by weiznich** [comment] 2024-04-21 12:46
Thanks for adding this information. I think I can explain what's wrong here. Diesel sets `MYSQL_OPT_SSL_MODE` for this option, which refers to the value `42` according to the bundled bindings (generated from mysqlclient 5.7.11 a few years back. It seems that this value changed with the release of mysql 8.0 to `35`. That means it now tries to use an unsupported value there and it seems like this is just ignored.

The fix for this would be to update the bundled bundings in the mysqlclient-sys crate. (Which is not something that is straight forward without breaking compatibility with older libmysqlclient versions). I already started doing that in https://github.com/sgrif/mysqlclient-sys/pull/40, which is just not complete yet. Your contribution is welcome there.

**Closed** 2024-05-21 19:32 UTC
Labels: bug, mysql
