### ISSUE TITLE
Problem with uuid and schema. 

### ISSUE THREAD

**Issue by rodrigodevelms** [diesel-rs/diesel#2540] opened 2020-10-13 12:14 UTC
### Versions

- **Rust:** 1.47.7
- **Diesel:** 1.4.5
- **Database:** PostgreSQL - version 13 alpine docker
- **Operating System** - Linux Solus 4.1

### Feature Flags

- **diesel:**

## Problem Description 

Hello all. 
I am learning to use Diesel, but I found some errors that I am not able to solve.
1 - My database is multi-tenant, based on the scheme, each scheme is a tenant. I don't know how to set up diesel.toml
I did

```
[print_schema]
file = "src / schema.rs"
schema = "tenantone"
```

but that way I can only register one tenant, what would be the correct form?
And in the file, model.rs when I import the schema, it looks like:

```
 use crate :: schema :: tenantone.customers;
```

but then the error occurs by the dot (tenantone **.** customers). How to solve?

2 - I use uuid as the main id, so my scheme is:

```
table! {
        tenantone.costumer (id) {
            id -> Uuid,
            internal_id -> Int8,
            active -> Bool,
            name -> Varchar,
            email -> Varchar,
            document -> Varchar,
            birthdate -> Date,
        }
    }
```

but when using the check post he always accuses error:

```
error[E0412]: cannot find type `Uuid` in this scope
 --> src/schema.rs:3:19
  |
3 |             id -> Uuid,
  |                   ^^^^ not found in this scope
  |
  = note: consider importing one of these items:
          crate::modules::costumer::model::Uuid
          uuid::Uuid
```
I tried to import how the compiler reports, but the error persists.

[Github](https://github.com/rodrigodevelms/learning-rust-with-actix/tree/main/orchestration/web)

ps: I am rewriting some microservices I have with Kotlin, to learn how to use Actix.

**Comment by weiznich** [comment] 2020-10-13 12:22
The first part of the issue is a duplicate of #1728. For the second part of the issue: Have you enabled the `uuid` or `uuidv07` feature? If not this is kind of expected behavior.

I'm closing this issue as this is essentially a duplicated issue + some API missuse, so nothing that really needs to have a separate open issue. For the future: Please use our [gitter channel](https://gitter.im/diesel-rs/diesel) to ask questions.

**Closed by weiznich** 2020-10-13 12:22 UTC
