### ISSUE TITLE
`nodes` is ambiguous

### ISSUE THREAD

**Issue by vcombey** [diesel-rs/diesel#3001] opened 2021-12-25 20:15 UTC
- **Rust:** nightly-2021-03-09
- **Diesel:** 1.4.5
- **Database:** PostgreSQL 12
- **Operating System** linux
- **diesel:** postgres

I just added a migration on my project and made a diesel migration run and the schema.rs doesn't compile. Diesel added some tables which are not present on my migration files. 

error[E0573]: expected type, found module `nodes`
   --> spoke_data/src/schema.rs:415:1
    |
415 | / table! {
416 | |     use crate::prelude::*;
417 | |
418 | |     workflow_entity (id) {
...   |
428 | |     }
429 | | }
    | |_^ not a type
    |
    = note: consider importing this struct instead:
            crate::schema::workflow_entity::columns::nodes
    = note: this error originates in the macro `__diesel_table_impl` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0659]: `nodes` is ambiguous
   --> spoke_data/src/schema.rs:422:9
    |
422 |         nodes -> Json,
    |         ^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `nodes` could refer to the module imported here
   --> spoke_data/src/schema.rs:415:1
    |
415 | / table! {
416 | |     use crate::prelude::*;
417 | |
418 | |     workflow_entity (id) {
...   |
428 | |     }
429 | | }
    | |_^
    = help: consider adding an explicit import of `nodes` to disambiguate
note: `nodes` could also refer to the struct imported here
   --> spoke_data/src/schema.rs:415:1
    |
415 | / table! {
416 | |     use crate::prelude::*;
417 | |
418 | |     workflow_entity (id) {
...   |
428 | |     }
429 | | }
    | |_^
    = help: consider adding an explicit import of `nodes` to disambiguate
    = note: this error originates in the macro `__diesel_table_impl` (in Nightly builds, run with -Z macro-backtrace for more info)

* The exact code where your hit the problem
* Relevant parts your schema, so any `table!` macro calls required for the
* Any other type definitions involved in the code, which produces your problem
-->

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by vcombey** [comment] 2021-12-25 20:22
It is working normal when I remove the tables workflow_entity, migration etc.. from schema.rs

**Comment by weiznich** [comment] 2021-12-25 21:13
Please provide at least the corresponding code to reproduce this issue and verify that this reproduces with a stable rust release.

**Comment by weiznich** [comment] 2022-01-03 08:07
Closed as the bug report misses important information. Feel free to add the required information so that we can reopen the issue.

**Closed by weiznich** 2022-01-03 08:07 UTC
Labels: bug

**Comment by marcusbuffett** [comment] 2022-08-06 20:07
This seems to be an issue with using `nodes` as the column name, I just hit this same issue and had to change the column name.

**Comment by weiznich** [comment] 2022-08-08 06:16
@marcusbuffett Your comment is not helpful as it does not clarify anything. If you wanted to add details to this issue, please add at least these information:
* Your diesel version
* Your rustc version
* A complete minimal example
* The error message as emitted by the compiler.

**Comment by marcusbuffett** [comment] 2022-08-08 08:10
I felt like the issues sharing the `nodes` column name was way too unlikely to be coincidence, so I figured I'd share. I'm past the error now and don't feel like going back to reproduce it.

**Comment by weiznich** [comment] 2022-08-08 08:57
@marcusbuffett Again such comments here are not helpful. Please stop commenting on old issues if you are not willing to add the necessary context later on.
