### ISSUE TITLE
No primary key 

### ISSUE THREAD

**Issue by SpBills** [diesel-rs/diesel#2778] opened 2021-05-13 19:23 UTC
### Versions

- **Rust:** 1.54.0-nightly
- **Diesel:** CLI: 1.4.1 
- **Database:** MySQL 8.0
- **Operating System** Ubuntu Linux 20.04 LTS

### Feature Flags

- **diesel:** mysql

## Problem Description

Whenever running migrations, Diesel CLI says that my table has no primary keys, no matter if I specify or not.

The tables are generated, however the schema.rs is not generated.

### What are you trying to accomplish?

I am trying to use migrations to make a table and generate a schema.rs.

### What is the expected output?

A schema.rs that contains the table.

### What is the actual output?

`Running migration 2021-05-13-190719_testing
Diesel only supports tables with primary keys. Table hello_world has no primary key`

However, the tables *are created.* The schema.rs is not generated.

### Are you seeing any additional errors?

Yes. Whenever attempting to use foreign keys, it seems to issue the same problem. It implies that I have no primary keys on any table.

### Steps to reproduce

Running `diesel migration run`

up.sql
```sql
CREATE TABLE hello_world (
    id int AUTO_INCREMENT PRIMARY KEY,
    title varchar(100)
)
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-05-13 19:29
Can you verify that there is no other table without primary key in your schema?
Also can you verify that the information schema contains the required information about the primary key?

**Comment by weiznich** [comment] 2021-05-16 15:36
Closed as I cannot reproduce this with mysql version 8.0.20. Feel free to add more details that could help reproducing this issue. Otherwise I would guess that there is another table without primary key in your schema. You can use `SHOW TABLES` in your mysql command line client to check for existing tables.

**Closed by weiznich** 2021-05-16 15:36 UTC
Labels: bug
