### ISSUE TITLE
ServerSide wrapper

### ISSUE THREAD

**Issue by hgrecco** [diesel-rs/diesel#1291] opened 2017-11-03 00:48 UTC
Is there a way to implement a (let's call it) `ServerSide` object (similar to Option) to tell diesel that a particular field should be ignored from any insert/update?

The example from the guide would then become:
```rust
#[derive(Queryable, Insertable)]
pub struct Post {
    pub id: ServerSide<i32>,
    pub title: String,
    pub body: String,
    pub published: bool,
}
```

and then use it in insert as:
```
    let new_post = NewPost {
        id: None // Or another special value
        title: title,
        body: body,
        published: false
    };

    diesel::insert(&new_post).into(posts::table)
        .get_result(conn)
        .expect("Error saving new post")
```

The same could be applied to other fields like `created_at` and `updated_at`. 

See also: #860 and this [reddit discussion](https://www.reddit.com/r/rust/comments/6nkuwt/discussion_get_rid_of_id_field_in_diesel_model/)

**Comment by killercup** [comment] 2017-11-03 09:04
What is your reasoning to make this a wrapper struct and not an attribute? Am I missing something or is this a subset of #860 (and thus a dupe of it)?

**Comment by sgrif** [comment] 2018-01-08 21:44
Yeah this seems like a duplicate of #860 to me.

**Closed by sgrif** 2018-01-08 21:44 UTC
