### ISSUE TITLE
Cannot find _PQconnectiondb

### ISSUE THREAD

**Issue by maxwellflitton** [diesel-rs/diesel#2742] opened 2021-04-25 01:01 UTC
### Versions

- **Rust:** rustc 1.51.0 (2fd73fabe 2021-03-23)
- **Diesel:** ```{ version = "1.4.4", features = ["postgres"] }```
- **Database:** postgres
- **Operating System:** MacOs Big Sur 11.2.3 M1 chip

### Feature Flags

- **diesel:**

## Problem Description
I cannot get the diesel cli to connect to the Postgres database due to not finding the ```_PQconnectdb```. I have the 
following file at ```/Users/maxwellflitton/.cargo/config```:

```
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```
Running any command with the ```Diesel``` client gives me the following output:

```
dyld: lazy symbol binding failed: Symbol not found: _PQconnectdb
  Referenced from: /Users/maxwellflitton/.cargo/bin/diesel
  Expected in: flat namespace

dyld: Symbol not found: _PQconnectdb
  Referenced from: /Users/maxwellflitton/.cargo/bin/diesel
  Expected in: flat namespace

zsh: abort 
```

### What are you trying to accomplish?
execute a diesel client command without erroring out

### What is the expected output?
An executed diesel client command without erroring out 

### What is the actual output?

```
dyld: lazy symbol binding failed: Symbol not found: _PQconnectdb
  Referenced from: /Users/maxwellflitton/.cargo/bin/diesel
  Expected in: flat namespace

dyld: Symbol not found: _PQconnectdb
  Referenced from: /Users/maxwellflitton/.cargo/bin/diesel
  Expected in: flat namespace

zsh: abort 
```

### Are you seeing any additional errors?
No

### Steps to reproduce
just running any diesel client command 

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [X] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-04-25 07:42
Conceptually this is a duplicate of all of [these](https://github.com/diesel-rs/diesel/issues?q=is%3Aissue+ld+returned+1+exit+status+) issues.
This means thats no issue in diesel itself, but a problem with your environment. You need to provide all libraries required by diesel.

Closed as duplicate issue.

**Closed by weiznich** 2021-04-25 07:42 UTC
Labels: bug
