### ISSUE TITLE
Diesel cli 1073741515 exit code - missing libpq.dll

### ISSUE THREAD

**Issue by ZiiMakc** [diesel-rs/diesel#2470] opened 2020-07-28 22:25 UTC
### Versions

- **Rust: 1.45**
- **Diesel_cli: 1.4.1**
- **Database: postgresql 12**
- **Operating System: windows 10**

### Feature Flags

- **diesel: postgresql**

## Problem Description
When i run diesel setup i get error in command promt about missing libpq.dll, what can be a problem if file exist and path is ok?

User and System path variables:
`PQ_LIB_DIR: C:\Program Files\PostgreSQL\12\lib`

[Location screenshoot.](https://i.imgur.com/x6DwJiv.png)

localhost postgres database works fine

## Checklist

- [v] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [v] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2020-07-29 06:26
Duplicate of #587

**Closed by weiznich** 2020-07-29 06:26 UTC

**Comment by ZiiMakc** [comment] 2020-07-29 08:54
@weiznich it's didn't help :(

**Comment by ZiiMakc** [comment] 2020-07-29 09:24
Resolver issue, you need to edit environment variables and edit variable Path, adding C:\Program Files\PostgreSQL\12\lib and C:\Program Files\PostgreSQL\12\bin
