### ISSUE TITLE
Compilation fails due to missing libpq.lib

### ISSUE THREAD

**Issue by Yuhanun** [diesel-rs/diesel#2508] opened 2020-09-18 15:58 UTC
### Versions

- **Rust:**
rustup --version
rustup 1.22.1 (b01adbbc3 2020-07-08)
- **Diesel:**
```
[dependencies]
rocket = "0.4.5"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["diesel_postgres_pool"]```
- **Database:** Postgres
- **Operating System** Windows

### Feature Flags

- **diesel:**

## Problem Description
Unable to compile my files because of the postgres libraries.

### What are you trying to accomplish?
Trying to compile my library.


### What is the expected output?
![image](https://user-images.githubusercontent.com/49172424/93619294-a681d480-f9d8-11ea-9fe5-9fe4279a6e03.png)

I have these files.

I'm trying to compile it and am expecting it to compile.

### What is the actual output?
```
C:\prog\concrete-suite\backend>cargo run
   Compiling rest-backend v0.1.0 (C:\prog\concrete-suite\backend\rest-backend)
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.18dirm3v4g9uapdc.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.1cmlmnd1uotxwbkg.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.1du9jyr4ju121t3l.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.1s12eagikfu0wt83.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.1um9975hetxavwwn.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.1yd17zti0d4mjf5n.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.1zjnzbasocx5q2f6.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.2hxtxuxhjvxpvij8.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.2o5pi0fph70ujdlm.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.2rbbuz4uf72f13c3.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.2sua42znfrupv2sr.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.3kf2s3ix7c904ybj.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.3ouy5vkji63q005u.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.4sbeml5vplt575bt.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.4wnxpltltloia1vt.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.4zsrtmczgh1bmn8r.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.57z5a6h7544i78jr.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.5a2vnrby7isbff6i.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.5ch06mfblyzvcf14.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.5dph598g0mf16ik8.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.960kl35g98z6uqw.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.gqmtq3lu5b70khz.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.ilmyuisx4w7nazn.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.jx77n44x5rwxfd7.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.unulxbcfdmhx2lm.rcgu.o" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.wzj94ybc3vd0k00.rcgu.o" "/OUT:C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.exe" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\rest_backend.2axoamc7wchca4k7.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:C:\\prog\\concrete-suite\\backend\\target\\debug\\deps" "/LIBPATH:C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\librocket_contrib-78100864e7bd30b8.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libdiesel-347b3ee0a26d67e4.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libpq_sys-d54bc570c3443f6c.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libbitflags-b3aa381b8c8a158c.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libr2d2-7438f65b385f28c3.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libscheduled_thread_pool-3d2d25c3876fa7fe.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libparking_lot-93d0f7b317954f76.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libparking_lot_core-e46815593cba0ca3.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\liblock_api-026890cf7d4eb395.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libscopeguard-ea9b20b2b0eee2d8.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libinstant-c99d67675d279109.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\librocket-74fdfd1c9abe039e.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libatty-f4414c40b5df1da8.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libmemchr-4920771ce9929d4c.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libtoml-30bc427675ddf5f7.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libserde-75915dcccd740fde.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libyansi-6d86c3d6314451e0.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\librocket_http-902ffd0f1f853e1f.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libhyper-0a8db6f657dbc11e.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libmime-a8af0fc70390b33e.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\liblog-f9a7f3d402ea99e0.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\liblog-20002c3625d2dd40.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\liblanguage_tags-cc12cb86d0178c75.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libtypeable-2dc7c73dbaa35228.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libtraitobject-f42d617083759973.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libnum_cpus-f01fc93a2228c4d5.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libhttparse-a1193d5e251c300f.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libunicase-1190bf55866dc6e9.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\liburl-b3f6b8c9d6cbf7d1.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libidna-625855835a8513b0.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libunicode_normalization-db5485c83fa308dc.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libtinyvec-3b1eac58bd4584a2.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libunicode_bidi-ccecaa982cb8f8e5.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libmatches-028ea65ddfc3aec7.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libbase64-bdf5c6d139b7a472.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libsafemem-3fb8ceca42b32a58.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libunicode_xid-758d9b5f84d97050.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libstate-2de055b77150bfb5.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libindexmap-d541b2a0f8e887b4.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libhashbrown-3da590ca0345a91e.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libcookie-6dbf7c57f30537b9.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libhkdf-bd77a3a4eea36bbb.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libhmac-eceb90e0acf10336.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libcrypto_mac-fdaedc11db746465.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libsubtle-b3d8fe014b11b928.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libsha2-01f0c30dc7d3a9d8.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libdigest-0f76bccbce0e9f80.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libfake_simd-f435c87980f53468.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libblock_buffer-8beff8f6ab224e21.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libblock_padding-3a0bd72662cc900e.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libbyte_tools-f35c80b8d1301064.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libaes_gcm-a65c0fd713bcfe3a.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libzeroize-e06e5f9b57b56001.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libghash-4f83f3b6be6d2cce.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libpolyval-862edfaf5ee0dd90.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libuniversal_hash-2353ad182e4a33e4.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libsubtle-3f24c22a80d460c8.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libaes-f4f0fa73f33c86ff.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libaes_soft-003b47918c08f727.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libopaque_debug-383c83b16c547b4d.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libbyteorder-7d4f56eeba33ca7a.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libaead-72f3fd8b3d94e321.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libblock_cipher_trait-c6a08bd93fdde07c.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libgeneric_array-555f87e41fa31429.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libtypenum-eaea6313adebafe1.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libbase64-0df5fddc3b4dee94.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\librand-8f5dd3298e4e3843.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\librand_chacha-e60a52b87a5d2168.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libppv_lite86-39bbd74e41d08b1f.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\librand_core-1441a7840c890395.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libgetrandom-35fe7807f7d463dc.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libcfg_if-5aca3b9407ea9208.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libtime-8649103769c3bebb.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libwinapi-67cf6d71ed9107d9.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libpercent_encoding-eeefa82d080aef16.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libsmallvec-2e3b2ae492ac2aa9.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libpercent_encoding-715b08436d231c27.rlib" "C:\\prog\\concrete-suite\\backend\\target\\debug\\deps\\libpear-8257e1d6f5661694.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-03343ad782def132.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-2af690f2dad1b9aa.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-b525c65aac6dc224.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-a7a850fac32c6efa.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-d1f456dbe2414d29.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-79dfe6d564d05449.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-303abf30a12df9b4.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-0d21bcb873f4e3cb.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-9a15006a1272f623.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-f7a208faae2fe85f.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-d505519916259fd7.rlib" "C:\\Users\\Yuhanun Citgez\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-f24cb6d5e4a99216.rlib" "libpq.lib" "advapi32.lib" "advapi32.lib" "cfgmgr32.lib" "fwpuclnt.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "ntdll.lib" "opengl32.lib" "synchronization.lib" "user32.lib" "winspool.lib" "ws2_32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1181: cannot open input file 'libpq.lib'

error: aborting due to previous error

error: could not compile `rest-backend`.

To learn more, run the command again with --verbose.
```

### Are you seeing any additional errors?
no 

### Steps to reproduce
Unsure.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

I'm using rocket, so cannot use stable.

**Comment by weiznich** [comment] 2020-09-21 09:25
Duplicate of https://github.com/diesel-rs/diesel/issues/587 + nightly is not a officially supported target.

**Closed by weiznich** 2020-09-21 09:25 UTC
