### ISSUE TITLE
Connection reuse with r2d2 is broken.

### ISSUE THREAD

**Issue by rustonaut** [diesel-rs/diesel#2104] opened 2019-07-02 12:34 UTC
## Setup

Any setup reusing connections over multiple threads through
r2d2's pool is likely affected (except such which use panic=abort, but most
diesel use cases are (web-)servers and shou'd probably be 
resilient against panics).

Also single threaded use-cases sharing connections through
a pool and using `catch_unwind`.

### Versions

- **Rust:** any which works with diesel
- **Diesel:** `1.4.2`
- **Database:** at last postgres, potentially others, too
- **Operating System:** any which works with diesel

### Feature Flags

- **diesel:** `r2d2` (and `postgres`, but likely other db's too)

### What is wrong?

1. There is no form of connection reset or is broken detection in diesels connection manager.
2.  Transactions have no panic handling (at last the postgres ones).

### What does this mean?

This means that if you start a transaction in one thread (e.g. in a endpoint in a multi-threaded server), then in that transaction you
panic the transaction will neither be committed _nor_ will it rollback.
But on drop (in the panic) the connection is put back into the pool.
This means if another thread (e.g. another endpoint) get's that connection it will  **acidentall continue the transaction**.

Also having multiple `BEGIN` statements does _not_ error (just warn)
so  if any endpoint after it run's a transaction it will commit that partial/broken transaction.

Also if the endpoint getting the bad transaction doesn't run a transaction it's changes might never be part of the database as it's still in a transaction which might happen to be committed in the future or might happen to be rolled back .

**So in other words it's one of this horrible really hard to find bugs, causing strange side effects.**

### What are you trying to accomplish?

Using diesel with the r2d2 feature in a multi threaded web server.

### Steps to reproduce

I made an example where it causes  a deletion to be run, which should not as it's transaction failed due to a bug causing a panic.

```sql
create table foos (
    id int primary key,
    name text not null
);
```

```rust
#[macro_use]
extern crate diesel;

use diesel::{
    r2d2::{Pool, ConnectionManager},
    pg::PgConnection
};

use diesel::prelude::*;
use crate::schema::foos;

mod schema;

type PgPool = Pool<ConnectionManager<PgConnection>>;

#[derive(Queryable, Insertable)]
pub struct Foo {
    pub id: i32,
    pub name: String
}

fn main() {
    let database_url = "postgres://user:pswd@localhost/dbname";

    let pool = PgPool::builder()
        .max_size(1)
        .build(ConnectionManager::new(database_url))
        .unwrap();

    {
        use crate::schema::foos::dsl::*;

        let conn = pool.get()
            .unwrap();

        diesel::delete(foos)
            .execute(&conn)
            .unwrap();
    }

    // Assume you have some multi threaded web server
    // and this just happened to be run in the given order.
    println!("> running some endpoint inserting into foos");
    fake_insert_endpoint(&pool, Foo{ id: 1, name: "Tom".into() });
    println!("> running some endpoint which panics in the transaction");
    fake_broken_endpoint(&pool);
    println!("> running some endpoint inserting into foos");
    fake_insert_endpoint(&pool, Foo{ id: 2, name: "TomTom".into() });

    println!();
    fake_list_endpoint(&pool);
    // lists:
    // | 2 | TomTom
    //
    // but should list:
    // | 1 | Tom
    // | 2 | TomTom
}

fn fake_broken_endpoint(pool: &PgPool) {
    use crate::schema::foos::dsl::*;

    let pool2 = pool.clone();
    let _ = std::thread::spawn(move || {
        let conn = pool2.get().unwrap();
        conn.transaction(|| -> Result<(), diesel::result::Error> {
            diesel::delete(foos)
                .execute(&conn)
                .unwrap();

            panic!("somehow the endpoint paniced, clearly a bug but can happen anyway");

            //lets pretend we would have reinserted the deleted data slightly
            // transformed or some other data
        })
    }).join();
}

fn fake_insert_endpoint(pool: &PgPool, foo: Foo) {
    use crate::schema::foos::dsl::*;

    let conn = pool.get().unwrap();
    conn.transaction(|| -> Result<(), diesel::result::Error> {
        diesel::insert_into(foos)
            .values(&foo)
            .execute(&conn)
            .unwrap();
        Ok(())
    }).unwrap();
}


fn fake_list_endpoint(pool: &PgPool) {
    use crate::schema::foos::dsl::*;
    let conn = pool.get()
        .unwrap();

    let results = foos.load::<Foo>(&conn)
        .expect("error listing table");

    println!("| Id |     Name |");
    println!("|----|----------|");
    for foo in results {
        println!("| {:>2} | {:>8} |", foo.id, foo.name);
    }
}
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

## Potential Solutions

Either one of the following would fix my specifc problem but some fix other problems, too:

1. Have some connection reset when placing back connections:
    - more general and also helps with e.g. some broken custom diesel code
   - I don't know of a sql command to do so in postgres and couldn't find one easily when googling...
2.  State a connection is broken when it is returned through a panic caused drop
     - Needs support in r2d2 not diesel as it needs to add some "dropped_in_panic" flag to the place back functionality and then
let the connection manager decide weather or not that is a problem.
3.  Check connections for invariants in `ConnectionManager::has_broken()`
    - E.g. check if the transaction managers internal nesting count is 0, if not drop the connection.
    - Requires a new method on `Connection`, e.g. `fn check_not_in_use_invariants(&self) -> bool`.
       - but can be default impl. to false until next braking release
4. Make sure transactions always roll back on panic
      - Given that the transaction manager doesn't store the connections this is a bit tricky but doable (by adding some drop guard inside of the connections `transaction` function).

Solution 1 would be the best as it also protects from other "bad state", but I'm not sure if it's doable.  Solution 2 needs changes in r2d2 and might be a problem for some use-cases. Solution 3 requires braking change to make sure the fix reaches all users. Solution 4 is slightly slower in the case of a panic then 3 but then panics are the exception not the norm so it likely doesn't really matter.

**Comment by rustonaut** [comment] 2019-07-02 13:40
Be aware that there is a duplication of transaction code between `Connection.transaction()` and pg's `TransactionBuilder.run()`.

**Comment by rustonaut** [comment] 2019-07-02 13:42
PS: I would implement fix 4, but also look for a way to properly reset connections/sessions if possible (e.g. it seems that in the Microsoft sql server there is actually a function for exactly this use case).

**Comment by rustonaut** [comment] 2019-07-02 15:28
Looking a bit more into it following thinks should be considered too:
1. for solution 4 (fixing the transaction function) rolling back on panic has some interesting properties:
    - we can't do anything with the error, so we ignore it
    - if the rollback panics we have a double panic which causes abortion
2. for a (partial) but non braking version of solution 3 we actually can use `Conntection.transaction_manager()` + `TransactionManager.get_transaction_depth()` in `ConnectionManager.has_broken()` if it's not 0 we drop the connection.
    - It fixes the main problem but not e.g. if you want to use a connection in some catch_unwind + retry logic, but then we don't have to support that

**Comment by sgrif** [comment] 2019-07-02 18:23
Please check for existing issues/PRs before opening new ones.

https://github.com/diesel-rs/diesel/pull/2020
https://github.com/sfackler/r2d2/issues/31
https://github.com/sfackler/r2d2/pull/70

**Comment by weiznich** [comment] 2019-07-02 18:23
Basically a duplicate of #2020. We want to to be fixed on r2d2 side.

**Closed by sgrif** 2019-07-02 18:23 UTC
