### ISSUE TITLE
Diesel (r2d2) hangs and aborts upon invalid database URL

### ISSUE THREAD

**Issue by VelvetThePanda** [diesel-rs/diesel#3534] opened 2023-03-07 23:07 UTC
### Versions

- **Rust:** 1.70.0-nightly (f63ccaf25 2023-03-06)
- **Diesel:** 2.0.3
- **Database:** PostgreSQL 15.2
- **Operating System** Win 10 Home, Build 19045

### Feature Flags

- **diesel:** `postgres`, `chrono`, `r2d2`

## Problem Description
Diesel hangs for ~5-10s when trying to connect before aborting the process for seemingly no reason

### What are you trying to accomplish?
Connecting to the database with a connection pool (as provided by r2d2)

### What is the expected output?
In the event that a malformed URL is provided, the method should either panic or return an error immediately

### What is the actual output?
The application hangs for several seconds before aborting without a stack trace, exiting with code 3.

This behavior is wildly inconsistent, however, and sometimes returns an error as expected, *however*, the error is empty (showing `Err(Error(None))` when printed out).

Other times (more rarely), the application will run, but queries will fail.

### Are you seeing any additional errors?
No.

### Steps to reproduce
Here's a minimal repo:
```rs
use diesel::backend::Backend;
use diesel::r2d2::ConnectionManager;
use diesel::{r2d2, PgConnection};

fn main() {
    let db_manager = ConnectionManager::<PgConnection>::new("postgres://postgres:postgres@localhost:5432/some_database");

    let db_pool = r2d2::Pool::builder()
        .build(db_manager)
        .unwrap();
    
    let _ = db_pool.get().unwrap(); // It'll never reach here! Or maybe it will.
    
    panic!("Success!");
}
```

I'd like to make a point that a normal `PgConnection` works as expected, and will return an error immediately.

This code will panic, as expected:

```rs
fn main() {
    let mut pg =
        PgConnection::establish(&"postgres://postgres:postgres@localhost:5432/some_database")
            .unwrap();

    let _ = pg.ping(); // It'll never reach here! Or maybe it will.

    panic!("Success!");
}
```

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case) (~~this is seemingly UB~~ I was informed this is neither unsound nor undefined, ~~I'd say this is an exception to this rule~~)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-03-08 09:37
This is not a diesel bug, but a duplicate of https://github.com/diesel-rs/diesel/discussions/2947
You are in so far correct that this is likely UB, but **not** in diesel but in your libpq version. We have already reported that multiple times to the author of that version but they seem to not care about that.

The "hang" is just the ordinary connection timeout configured by r2d2. You can configure lower times there by changing the `connection_timeout` during the setup of the pool.

Closed as this is not a diesel issue at all. In addition this is a duplicate of an existing discussion that should have shown up as soon as you search for `exit code 3`

**Closed by weiznich** 2023-03-08 09:37 UTC
Labels: bug
