### ISSUE TITLE
How to properly implement HasSqlType::metadata for a custom type?

### ISSUE THREAD

**Issue by frol** [diesel-rs/diesel#2469] opened 2020-07-28 12:12 UTC
## Setup

diesel with diesel-derive-enum (it just helped to uncover the issue)

### Versions

- **Rust**: nightly-2020-05-15 (irrelevant)
- **Diesel**: 1.4.5
- **Database**: PostgreSQL
- **Operating System**: Arch Linux

### Feature Flags

- **diesel**: "postgres", "numeric", "serde_json"

## Problem Description

Working on a project using [`diesel-derive-enum`](https://github.com/adwhit/diesel-derive-enum) I discovered that diesel queries take too long to execute. [After some digging](https://github.com/adwhit/diesel-derive-enum/issues/52) I learned that diesel-derive-enum does runtime lookups for the enum types on PostgreSQL, and it does that for every single entry, so a single INSERT statement with 20 records produces 20 pre-flight lookups before a single query. 

### What are you trying to accomplish?

Should diesel-derive-enum implement caching or what is the proposed solution to this issue? Replacing the runtime lookup with a constant value where `oid` and `array_oid` are zeros did not bring any issues for SELECT, UPDATE, and INSERT statements, so I wonder if diesel needs that information at all for such types of queries.

### What is the expected output?

I expect a single `insert_into` execution to produce a single `INSERT INTO` statement.

### What is the actual output?

A single `insert_into` execution may lead to N pre-flight lookup queries from custom types implementing HasSqlType::metadata.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be closed if this is not the case)

**Comment by weiznich** [comment] 2020-07-28 12:21
Duplicate of #2071. 
The dynamic lookup of the OID is required as OID's of custom types are not stable across different postgres instances. Just using 0 there will cause issues as soon as the exact type is required to be known by postgres. That's the case for example if you try to insert an array of values of your custom type.

**Closed by weiznich** 2020-07-28 12:21 UTC
