### ISSUE TITLE
No BLOB types

### ISSUE THREAD

**Issue by walksanatora** [diesel-rs/diesel#3665] opened 2023-06-24 22:52 UTC
### Versions

- **Rust:**
- rustc 1.71.0-nightly (ce5919fce 2023-05-15)
- **Diesel:**
- diesel 
 Version: 2.1.0
 Supported Backends: mysql
- **Database:**
- mysql  Ver 15.1 Distrib 10.11.4-MariaDB, for Linux (x86_64) using readline 5.1
- **Operating System**
- arch linux

### Feature Flags

- **diesel:**
- mysql

## Problem Description

I cannot find TINY/MEDIUMBLOB types which means I cant bring them into rust

### What are you trying to accomplish?

I need to store some binary blob information in MariaDB but diesel (apperently) has no support
## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues. 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-06-25 14:12
I'm not sure I can really follow that bug report. What exactly did you do to come to the conclusion that these types are not supported? Additionally, for the case that these are really not supported (which I do not believe to be the case) this would be a feature request and not a bug report, so it would not belong to the issue tracker.

**Comment by walksanatora** [comment] 2023-06-25 20:21
in the `diesel::sql_types` I tried to search for any `BLOB` type (pressed Ctrl+f and searched `blob`)
and there is no type for TINY/MEDIUM/LARGEBLOB types  (also yeah should probally set this as a feature request)

**Comment by weiznich** [comment] 2023-06-28 15:41
Closed in favour of #3666

**Closed** 2023-06-28 15:41 UTC
Labels: bug
