### ISSUE TITLE
Getting Started Guide: no instructions on troubleshooting diesel-cli install.

### ISSUE THREAD

**Issue by LeoTindall** [diesel-rs/diesel#963] opened 2017-06-22 15:43 UTC
In the getting started guide, the user is instructed to `cargo install diesel_cli`. However, this requires headers for `libpq`, `libsqlite3`, and `libmysqlclient`. It would be awesome if there was documentation of this. I'd submit a PR, but I don't know where the repo is for that web page.

**Comment by Eijebong** [comment] 2017-06-22 15:45
The repo is here https://github.com/sgrif/diesel.rs-website

**Comment by hobofan** [comment] 2017-08-14 15:24
Duplicate of https://github.com/diesel-rs/diesel/issues/588

**Comment by killercup** [comment] 2017-08-15 14:37
Indeed. Resolved by sgrif/diesel.rs-website#29.

**Closed** 2017-08-15 14:37 UTC
