### ISSUE TITLE
Specifying a database port in DATABASE_URL does not work for connections on localhost

### ISSUE THREAD

**Issue by cars10** [diesel-rs/diesel#2424] opened 2020-06-07 14:26 UTC
### Versions

- **Rust:** rustc 1.44
- **Diesel:** 1.4.4
- **Database:** mysql  Ver 15.1 Distrib 10.4.13-MariaDB, for Linux (x86_64) using readline 5.1
- **Operating System:** Arch

### Feature Flags

- **diesel:** features = ["mysql", "chrono"]

## Problem Description

Specifying the database port in `DATABASE_URL` does not work for `localhost`.

### What are you trying to accomplish?

Connect to a mysql database that does not run on the default port (`13306` instead of `3306`).

```
DATABASE_URL=mysql://root:test@localhost:13306 diesel database reset
```

### What is the expected output?

Connecting to a different port should work.

### What is the actual output?

Diesel still tries to connect to `3306`.

### Are you seeing any additional errors?

Nope

### Steps to reproduce

Start a database on a non-default port, for example:

```
docker run -e MYSQL_ROOT_PASSWORD=test --name test-db -p 13306:3306 mariadb:10.4
```

Then run any diesel command, for example

```
DATABASE_URL=mysql://root:test@localhost:13306 diesel database reset
```

This does not work, diesel still tries to connect to `3306`. If you replace `localhost` with `127.0.0.1` it works as expected.

**Comment by weiznich** [comment] 2020-06-08 08:10
We are passing the port correctly to the lower level native [`mysql_real_connect` connection function here](https://github.com/diesel-rs/diesel/blob/84c240f379895780662e569aa5080c8a831b4f8f/diesel/src/mysql/connection/raw.rs#L42-L73). Therefore this seems to be caused by libmysqlclient itself as it tries to be helpful. According the [libmysqlclient documentation here](https://dev.mysql.com/doc/refman/8.0/en/mysql-real-connect.html), the function does try to use a unix socket on linux if the host name is `localhost`, therefore the port number does not have any there.


Closed as this is not a bug in diesel itself.

**Closed by weiznich** 2020-06-08 08:10 UTC
