### ISSUE TITLE
AsChangeset and Insertable produce unhelpful error messages

### ISSUE THREAD

**Issue by msrd0** [diesel-rs/diesel#2793] opened 2021-05-23 20:35 UTC
Consider the following code (using `AsChangeset` instead / in addition to `Insertable` produces the same error message):

```rust
#[derive(Insertable)]
struct Foo {
        #[column_name = "type"]
        ty: String
}
```

This code is wrong because eventhough the table has a column called _type_, the auto-generated `schema.rs` file renames that to *type_* to avoid using a keyword as an identifier, and that's the column name that has to be used. Unfortunately, the error message produced by the macro has an unhelpful message and an incorrect span:

```
error: proc-macro derive panicked
 --> src/main.rs:3:10
  |
3 | #[derive(Insertable)]
  |          ^^^^^^^^^^
  |
  = help: message: expected identifier
```

Ideally, the error message would look similar to this:

```
error[E0560]: struct `Foo` has no field named `type`
 --> src/main.rs:7:9
  |
5 |        #[column_name = "type"]
  |                        ^^^^^^ help: a field with a similar name exists: `type_`
```

This error message does not only help when trying to use a name that is an invalid identifier in rust, but also when there is a typo in the column name.

Related: https://github.com/diesel-rs/diesel/issues/2792#issuecomment-846581411

**Comment by weiznich** [comment] 2021-05-25 14:38
That's for opening this issue. After having spend some time to dig into this I fear there is no much we can do here. From a technical point of view there are two possibilities to generate this "nicer" error message":

1. The proc macro itself generates the diagnostic. Unfortunately this is nothing that is possible yet using stable rust. See https://github.com/rust-lang/rust/issues/54140. Even with that API implemented it wouldn't be possible to emit the additional `help` line, as again there is no API to query if such a similar named field exists. Having both API's would be really nice, but that's unfortunately nothing that can be fixed on diesels side only. Consider working on the compiler side of things here, if you want work on improvements.
2. The proc macro itself can generate "valid" rust code, where the compiler itself emits the corresponding error message, as this would be done for any other rust code. Unfortunately this is not possible here, as `type` is never a valid identifier. Technically speaking we could likely emit code containing `type` as field name, but this will generate an error message just stating that `type` is no valid identifier which would at least point to the correct span. Unfortunately this comes with an really large cost: We couldn't use `syn` anymore, which would mean we need to implement support for parsing and generating rust code all on our own. That is not something I consider to do, at least not without much larger gains.

The only thing that could actually be done is to improve [this error message](https://github.com/diesel-rs/diesel/blob/e78ae2311f087d56b7c371b0a203f00bb04583be/diesel_derives/src/meta.rs#L79) to say something more meaningful. We are happy to receive a PR doing that.

**Comment by msrd0** [comment] 2021-05-25 15:07
I think there is a 3rd option: Make the proc-macro return something like

```rust
syn::Error::new(self.meta.span(), format!(
    "Expected valid identifier, found `{name}`. Diesel automatically renames invalid identifiers, perhaps you meant to write `{name}_`?",
    name = self.name().segments.first().unwrap().ident.clone()
)).into_compile_error()
```

This will produce an error message like

```
error: Expected valid identifier, found `type`. Diesel automatically renames invalid identifiers, perhaps you meant to write `type_`?"
 --> src/main.rs:7:9
  |
5 |        #[column_name = "type"]
  |                        ^^^^^^
```

This is much better than using `panic!`, as rust can point to the exact code location instead of the `#[derive(Insertable)]` statement, and we can provide a help message inside the error message (we can't output help messages on stable rust afaik).

**Comment by davidbrizo52** [comment] 2021-07-05 14:51
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.

**Comment by Pyzyryab** [comment] 2021-07-30 22:29
> 
> 
> I think there is a 3rd option: Make the proc-macro return something like
> 
> ```rust
> syn::Error::new(self.meta.span(), format!(
>     "Expected valid identifier, found `{name}`. Diesel automatically renames invalid identifiers, perhaps you meant to write `{name}_`?",
>     name = self.name().segments.first().unwrap().ident.clone()
> )).into_compile_error()
> ```
> 
> This will produce an error message like
> 
> ```
> error: Expected valid identifier, found `type`. Diesel automatically renames invalid identifiers, perhaps you meant to write `type_`?"
>  --> src/main.rs:7:9
>   |
> 5 |        #[column_name = "type"]
>   |                        ^^^^^^
> ```
> 
> This is much better than using `panic!`, as rust can point to the exact code location instead of the `#[derive(Insertable)]` statement, and we can provide a help message inside the error message (we can't output help messages on stable rust afaik).

Why doesn't anyone give him some credit? It's a nice solution!

**Comment by weiznich** [comment] 2021-07-31 06:56
@Pyzyryab Feel free to submit a PR implementing this strategy + adding some tests to show that it works via tests. Otherwise our issue tracker is for our contributors to track bugs and regressions. It's not a place for general discussion.

**Comment by pksunkara** [comment] 2023-02-18 20:24
@msrd0 Is this still an issue? We released diesel 2.0 after this.

**Comment by pksunkara** [comment] 2023-02-20 11:07
Yeah, it looks like it's a different error we are getting now. But I thought we already had a deprecated test for this.

**Comment by weiznich** [comment] 2023-02-20 11:35
@pksunkara At least for me exactly the same error message is generated:

```rust
use diesel::prelude::*;

table! {
    foos {
        id -> Integer,
    }
}

#[derive(Insertable)]
struct Foo {
    #[diesel(column_name = "type")]
    ty: String,
}

```

generates

```
error: proc-macro derive panicked
 --> src/main.rs:9:10
  |
9 | #[derive(Insertable)]
  |          ^^^^^^^^^^
  |
  = help: message: expected identifier
```

the problem is likely this line of code: https://github.com/diesel-rs/diesel/blob/8d64a4011bed57851e3cd747df6d855d44ab9993/diesel_derives/src/attrs.rs#L99

**Comment by pksunkara** [comment] 2023-02-20 12:57
Oh, I was trying out the deprecated derive format. IIRC a different error message came up.


```rust
use diesel::prelude::*;

table! {
    foos {
        id -> Integer,
    }
}

#[derive(Insertable)]
struct Foo {
    #[column_name = "type"]
    ty: String,
}
```

```
warning: #[column_name] attribute form is deprecated
  = help: use `#[diesel(column_name = type)]` instead

error: expected string literal
  --> src/main.rs:11:21
   |
11 |     #[column_name = "type"]
   |                     ^^^^^^
```

**Comment by msrd0** [comment] 2023-02-21 11:51
@pksunkara That error message is even worse: "type" is most certainly a string literal.

**Closed** 2023-03-01 08:40 UTC
Labels: bug, enhancement, help wanted, good first issue
