### ISSUE TITLE
Diesel only supports tables with primary keys. Table posts has no primary key

### ISSUE THREAD

**Issue by ypli0629** [diesel-rs/diesel#2915] opened 2021-10-02 04:44 UTC
### Versions

- **Rust:** 1.54.0
- **Diesel:** 1.4.4
- **Database:** mysql@8.0.26
- **Operating System** OSX11.6

### Feature Flags

- **diesel:** mysql

## Problem Description
I just follow the guides on the office website,But when I run `diesel migration run`, the following error occurred 
![image](https://user-images.githubusercontent.com/22133189/135703931-ecbed3fa-4fb3-4b69-982c-5c9fec88cf08.png)

![image](https://user-images.githubusercontent.com/22133189/135703911-6d4b86c8-a156-42d7-8a8b-3d0d1e0387e2.png)

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-10-02 06:15
Duplicate of #2786. This seems to bee a breaking change in mysqls information schema implementation.

**Closed by weiznich** 2021-10-02 06:15 UTC
Labels: bug
