### ISSUE TITLE
Bug, SQLite wrong integer size for rowid

### ISSUE THREAD

**Issue by sidju** [diesel-rs/diesel#2226] opened 2019-11-25 13:34 UTC
## Problem Description
Since SQLite doesn't really care about typing columns INTEGER in SQLite can be any number up to i64 (or a float, if you do weird things). Mostly you can be proper and write BIGINTEGER like usual, but if you wish to create an alias to rowid you must write INTEGER even though rowid is a 64bit signed integer. This results in an incrementing 64 bit integer being interpreted as 32 bit by diesel, an eventual guaranteed error.

( I am running rust stable and diesel_cli 1.4.0. The rest is irrelevant, since this is an issue in the schema.rs generation )

## Expected solution
Since SQLite is strange about typing reading all integer types from SQLite as 64 bit would be reasonable. The obvious problem with that being that you now need to know what type the database is at schema generation... Perhaps some environment variable only needed when the database_url doesn't imply the database (127.0.0.1:3306 | /tmp/test.db etc.)?

Alternatively, just don't fix. If you need more than 64 bit keys with good performance you shouldn't be using SQLite.

**Comment by weiznich** [comment] 2019-11-25 14:55
Duplicate of #852

**Closed by weiznich** 2019-11-25 14:55 UTC
