### ISSUE TITLE
These compiler error messages are so hideous

### ISSUE THREAD

**Issue by Randall-Coding** [diesel-rs/diesel#2659] opened 2021-02-28 20:00 UTC
### Versions
Diesel 1.4.5, features: sqlite
Rust 2018
Ubuntu 18.04

### Feature Flags
sqlite

## Problem Description
These compiler errors I see for diesel are some of the most confusing and difficult to solve.  Here is an example. 

> the trait bound `Sqlite: SupportsReturningClause` is not satisfied
> required because of the requirements on the impl of `QueryFragment<Sqlite>` for `diesel::query_builder::returning_clause::ReturningClause<(columns::id, columns::title, columns::published, columns::description, columns::name, columns::lbry_url)>`
> 1 redundant requirements hidden
> required because of the requirements on the impl of `QueryFragment<Sqlite>` for `InsertStatement<table, ValuesClause<(ColumnInsertValue<columns::title, diesel::expression::bound::Bound<diesel::sql_types::Text, &&str>>, ColumnInsertValue<columns::description, diesel::expression::bound::Bound<diesel::sql_types::Text, &&str>>, ColumnInsertValue<columns::name, diesel::expression::bound::Bound<diesel::sql_types::Nullable<diesel::sql_types::Text>, &&str>>), table>, diesel::query_builder::insert_statement::Insert, diesel::query_builder::returning_clause::ReturningClause<(columns::id, columns::title, columns::published, columns::description, columns::name, columns::lbry_url)>>`
> required because of the requirements on the impl of `LoadQuery<diesel::SqliteConnection, _>` for `InsertStatement<table, ValuesClause<(ColumnInsertValue<columns::title, diesel::expression::bound::Bound<diesel::sql_types::Text, &&str>>, ColumnInsertValue<columns::description, diesel::expression::bound::Bound<diesel::sql_types::Text, &&str>>, ColumnInsertValue<columns::name, diesel::expression::bound::Bound<diesel::sql_types::Nullable<diesel::sql_types::Text>, &&str>>), table>>

Errors like this pop up on the dsl function calls like load() and save_changes() and get_result().  This last one was on get_result, I fixed the issue with the other two.  

On the error on load() the issue had to do with my model having the wrong type, whereas on save_changes() the error was actually with my return type of my function.  The confusing thing is these messages all look the same and they all don't tell me the problem in a way I can understand.  Maybe this is something within your control to make better in future releases?

NOTE: I'm not asking to have this specific error solved, I'm just making a request / suggestion to somehow find a way to play nicer with the compiler and make the error messages make more sense.  Thanks for reading, carry on.

**Comment by Randall-Coding** [comment] 2021-02-28 20:38
I figured out this particular issue, appears to be Sqlite causing the problem.  But just thought I'd make a note that these long errors messages just confuse the heck out of me.

**Comment by henryboisdequin** [comment] 2021-03-01 00:46
Yes, it would be great if Diesel had better error messages. This is something that I will look into.

**Comment by weiznich** [comment] 2021-03-01 10:03
I believe this is a duplicate of #151.

Additionally I do not see what could be done here, as the only thing we can control in this error messages are the type names, not the exact text of the error message. You can see that as limitation of the rust language, but then you should have filled this issue against there bug tracker. Fundamentally changing the situation would likely require designing and submitting a RFC for rust-lang itself to add some kind of diagnostic API, implement that API in the compiler and get it released. At least for me that's out of scope for doing it myself.

I should also add that I personally find that this is one of our better error messages, as it states quite direct what's wrong there. In it's core it says `the trait bound Sqlite: SupportsReturningClause is not satisfied`, which can be read as "Sqlite does not support ReturningClauses", which is the underlying issue with your query here. 
@Randall-Coding As you opened this issue, could you clarify what you would like to have seen in that error messages exactly. Can you provide some concrete suggestions how to make them better? (This also applies to the other two errors you mentioned).

**Closed by weiznich** 2021-03-01 10:03 UTC
Labels: enhancement, help wanted
