### ISSUE TITLE
AsExpression not implemented for &Option<T>

### ISSUE THREAD

**Issue by jafioti** [diesel-rs/diesel#3356] opened 2022-10-02 02:03 UTC
### Versions

- **Diesel:**
2.0.0
- **Database:**
Sqlite

## Problem Description
I have a struct containing a &Option<i32>, which should be applicable to a Nullable<Integer>, but Expression isn't implemented which means AsExpression isn't implemented either.

### What are you trying to accomplish?
Use &Option<i32> for Nullable<Integer> the same way I use &i32 for Integer.

### Steps to reproduce

Simply make a table with a nullable integer column, and try to make a cooresponding struct with that column being a &Option<T>

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2022-10-02 06:32
Please provide a reproducible example including the complete error message as generated by the compiler. Otherwise I need to close this bug report as incomplete.

**Comment by weiznich** [comment] 2022-10-10 15:07
Closed due to a missing reproducible example

**Closed by weiznich** 2022-10-10 15:07 UTC
Labels: bug
