### ISSUE TITLE
`table!` macro expansion doesn't include imports

### ISSUE THREAD

**Issue by happycoder97** [diesel-rs/diesel#2558] opened 2020-11-09 06:56 UTC
### Versions

- **Rust:**  `rustc 1.47.0 (18bf6b4f0 2020-10-07)`
- **Diesel:** v1.4.5
- **Database:** Postgres, but not relevant I guess.
- **Operating System** Arch Linux

### Feature Flags

- **diesel:** postgres, chrono

## Minimal repro
https://github.com/happycoder97/diesel-repro

## Problem Description
`table!` macro expansion doesn't include imports.

Compiler gives this error:
![image](https://user-images.githubusercontent.com/40014472/98507659-0e8bc300-2284-11eb-85dd-a9731baa859f.png)

But it is imported inside `table!{..}`:
![image](https://user-images.githubusercontent.com/40014472/98507724-2d8a5500-2284-11eb-869c-f3a963dc37ac.png)

Relevant parts of source of `table!` macro:
![image](https://user-images.githubusercontent.com/40014472/98507806-59a5d600-2284-11eb-8df0-7c8c915fa1f2.png)

Relevant parts of `cargo expand` output:
![image](https://user-images.githubusercontent.com/40014472/98508714-fa48c580-2285-11eb-9ff1-2c583349d100.png)

Interesting bits:
This used to compile till yesterday (in another codebase). I was working on a completely different part of my code and it started giving me this error. 
I had done a few `cargo clean`s in between to see if changing codegen units affected link time. That might have triggered this.
I had faced the same issue last month. But iirc it went away on its own when I renamed the types or re-ordered the imports or did something like that.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2020-11-09 07:43
I cannot reproduce this error. While trying to built your "reproducible" example I hit the following unrelated error messages:
```
/tmp/diesel-repro ξ cargo +stable run                                                                                                                                         
   Compiling libc v0.2.80
   Compiling pq-sys v0.4.6
   Compiling byteorder v1.3.4
   Compiling bitflags v1.2.1
   Compiling num-traits v0.2.14
   Compiling time v0.1.44
   Compiling num-integer v0.1.44
   Compiling chrono v0.4.19
   Compiling diesel v1.4.5
   Compiling diesel-repro v0.1.0 (/tmp/diesel-repro)
warning: private type `Foo` in public interface (error E0446)
  --> src/main.rs:6:1
   |
6  | / table! {
7  | |     use diesel::sql_types::*;
8  | |     use super::Foo;
9  | |
...  |
13 | |     }
14 | | }
   | |_^
   |
   = note: `#[warn(private_in_public)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #34537 <https://github.com/rust-lang/rust/issues/34537>
   = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: private type `Foo` in public interface (error E0446)
  --> src/main.rs:6:1
   |
6  | / table! {
7  | |     use diesel::sql_types::*;
8  | |     use super::Foo;
9  | |
...  |
13 | |     }
14 | | }
   | |_^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #34537 <https://github.com/rust-lang/rust/issues/34537>
   = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0446]: private type `Foo` in public interface
  --> src/main.rs:6:1
   |
4  |   struct Foo;
   |   - `Foo` declared as private
5  |
6  | / table! {
7  | |     use diesel::sql_types::*;
8  | |     use super::Foo;
9  | |
...  |
13 | |     }
14 | | }
   | |_^ can't leak private type
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0446]: private type `Foo` in public interface
  --> src/main.rs:6:1
   |
4  |   struct Foo;
   |   - `Foo` declared as private
5  |
6  | / table! {
7  | |     use diesel::sql_types::*;
8  | |     use super::Foo;
9  | |
...  |
13 | |     }
14 | | }
   | |_^ can't leak private type
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0446]: private type `Foo` in public interface
  --> src/main.rs:6:1
   |
4  |   struct Foo;
   |   - `Foo` declared as private
5  |
6  | / table! {
7  | |     use diesel::sql_types::*;
8  | |     use super::Foo;
9  | |
...  |
13 | |     }
14 | | }
   | |_^ can't leak private type
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors; 2 warnings emitted

For more information about this error, try `rustc --explain E0446`.
error: could not compile `diesel-repro`.

To learn more, run the command again with --verbose.
/tmp/diesel-repro ξ rustc +stable --version                                                                                                                                    
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```

Otherwise: We do have a test case for this behavior [here](https://github.com/diesel-rs/diesel/blob/a2996ee4f7f399e7b66449afa98c910ab23867fb/diesel/src/macros/mod.rs#L1311-L1335) + our CI tests passed for this test for at least the last few month without issue, therefore I do not see why this should suddenly change somewhere. 
Closed this issue as cannot reproduce. If you still feel that this is a diesel issue (and not some rustc/cargo caching artifact or whatever), just comment here and provide something that is actually reproducible for us maintainers.

**Closed by weiznich** 2020-11-09 07:43 UTC

**Comment by happycoder97** [comment] 2020-11-09 07:55
Nuking `~/.cargo` fixed the issue.

PS: backup ~/.cargo/bin and ~/.cargo/config before nuking.

**Comment by weiznich** [comment] 2020-11-09 12:08
Sounds like a corrupted/modified source clone then.

**Comment by olibearo** [comment] 2020-11-15 17:12
I ran into this same issue. The enum module which is imported at the top of the `table!` macros by the output of the `print-schema` is there, but the output of the `table!` macro did not include the imports. Cleaning up the `~/.cargo` directory and running `cargo clean` got rid of the error. I'm unsure how I got to this state though, this has been working and then it was not.

**Comment by happycoder97** [comment] 2020-12-05 03:55
This happened again today after I did `rustup update`.

**Comment by weiznich** [comment] 2020-12-05 13:14
@happycoder97 Can you provide information about which rustc versions and which commands are exactly required to reproduce this?

**Comment by happycoder97** [comment] 2020-12-05 13:22
`rustc 1.50.0-nightly (3ff10e74a 2020-12-04)`
This is the version I got after I did `rustup update`. I don't remember the previous version. I think it was about a month ago I last updated. 
I am not sure if this is related, I had also added musl target to rustup about at the same time. 
But the project was using gnu target when the error showed up.
