### ISSUE TITLE
diesel_cli: joinable not reproduced with `diesel migration redo`

### ISSUE THREAD

**Issue by najtin** [diesel-rs/diesel#3200] opened 2022-06-10 12:11 UTC
### Versions

- **Rust: 1.60.0**
- **Diesel CLI: 2.0.0-rc.0**
- **Diesel: not needed**
- **Database: postgres 14.3 (docker)**
- **Operating System: Manjaro**

## Problem Description

`diesel migration redo` does produce a different `schema.rs` compared to reverting all migrations (or starting with a fresh database) and running `diesel migration run`. Running `diesel migration revert && diesel migration run` yields the same faulty result as `diesel migration redo`.

### What are you trying to accomplish?
I just wanted to get partitions to work with Diesel. As stated in https://github.com/diesel-rs/diesel/issues/2817 adding partitions will result in an empty schema.rs on diesel_cli 1.4.1, so i updated to diesel_cli 2.0.0-rc.0. If i run the migration on a fresh database everything works fine, but redos do not produce all joinables. I would like to get the same `schema.rs` when running `diesel migration redo` as when reverting everything (or starting with a fresh database) and then running `diesel migration run`.

### What is the expected output?
The expected output of `diesel migration redo` is to be the same `schema.rs` as when reverting everything (or starting with a fresh database) and then running `diesel migration run`.

### What is the actual output?
Some joinables are missing in the output.

### Are you seeing any additional errors?
No

### Steps to reproduce
This is the project before any migrations: https://github.com/najtin/diesel_redo_vs_run/tree/d299c7e4a1e7bc8d9702315393db5ed3657af625
Here you can see the differences in the schema.rs https://github.com/najtin/diesel_redo_vs_run/commit/26869f263e529bec1ef786bebfc725bd1c001070

```bash
git clone https://github.com/najtin/diesel_redo_vs_run
git checkout d299c7e4a1e7bc8d9702315393db5ed3657af625
# change .env to your needs
nano .env
diesel migration run
# take a look at the joinables from schema.rs
less src/schema.rs
# redo the last migration
diesel migration redo
# notice the missing joinables
less src/schema.rs
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

Thank you very much for this awesome crate!

**Comment by weiznich** [comment] 2022-06-10 13:14
Basically the same as written for #3201 also applies here. I assume that the information is just not there so that would be, so we cannot do much about that.

**Comment by najtin** [comment] 2022-06-10 18:04
This is the unformated output of the query referred to in https://github.com/diesel-rs/diesel/issues/3201#issuecomment-1152347553 on a fresh database. 

```
[ForeignKeyConstraint { child_table: TableName { sql_name: "course_user", rust_name: "course_user", schema: None }, parent_table: TableName { sql_name: "course", rust_name: "course", schema: None }, foreign_key: "course_id", foreign_key_rust_name: "course_id", primary_key: "id" }, ForeignKeyConstraint { child_table: TableName { sql_name: "course_user", rust_name: "course_user", schema: None }, parent_table: TableName { sql_name: "course_partiton_22_ss", rust_name: "course_partiton_22_ss", schema: None }, foreign_key: "course_id", foreign_key_rust_name: "course_id", primary_key: "id" }, ForeignKeyConstraint { child_table: TableName { sql_name: "course_user", rust_name: "course_user", schema: None }, parent_table: TableName { sql_name: "user", rust_name: "user", schema: None }, foreign_key: "member_user_id", foreign_key_rust_name: "member_user_id", primary_key: "id" }]
```

This is the output after a redo:
```
[ForeignKeyConstraint { child_table: TableName { sql_name: "course_user", rust_name: "course_user", schema: None }, parent_table: TableName { sql_name: "user", rust_name: "user", schema: None }, foreign_key: "member_user_id", foreign_key_rust_name: "member_user_id", primary_key: "id" }]
```

Keep in mind this bug does only surface if we redo a migration. Not if we apply them all at once on a fresh database. This makes we wonder how this bug can possibly happen. After a faulty redo, as soon as the other partitioned table gets a partition, the query has the correct output again. 
```sql
CREATE TABLE course_user_partiton_22_ss PARTITION OF course_user FOR VALUES FROM (2210000000000000000) TO (2220000000000000000);
```
```
[ForeignKeyConstraint { child_table: TableName { sql_name: "course_user", rust_name: "course_user", schema: None }, parent_table: TableName { sql_name: "user", rust_name: "user", schema: None }, foreign_key: "member_user_id", foreign_key_rust_name: "member_user_id", primary_key: "id" }, ForeignKeyConstraint { child_table: TableName { sql_name: "course_user", rust_name: "course_user", schema: None }, parent_table: TableName { sql_name: "user", rust_name: "user", schema: None }, foreign_key: "member_user_id", foreign_key_rust_name: "member_user_id", primary_key: "id" }, ForeignKeyConstraint { child_table: TableName { sql_name: "course_user", rust_name: "course_user", schema: None }, parent_table: TableName { sql_name: "user", rust_name: "user", schema: None }, foreign_key: "member_user_id", foreign_key_rust_name: "member_user_id", primary_key: "id" }, ForeignKeyConstraint { child_table: TableName { sql_name: "course_user", rust_name: "course_user", schema: None }, parent_table: TableName { sql_name: "user", rust_name: "user", schema: None }, foreign_key: "member_user_id", foreign_key_rust_name: "member_user_id", primary_key: "id" }]
```
So this seems to be some weird postgres behavior.

**Comment by weiznich** [comment] 2022-06-16 07:11
As your migrations contain a partition as well I will close this as duplicate of #3201.

**Closed by weiznich** 2022-06-16 07:11 UTC
Labels: bug
