### ISSUE TITLE
Diesel only supports tables with primary keys. Table spatial_ref_sys has no primary key

### ISSUE THREAD

**Issue by chilimatic** [diesel-rs/diesel#2113] opened 2019-07-09 13:32 UTC
## Setup
Arch linux + rustup + diesel + pgsql

### Versions

- **Rust:** rustc 1.34.1 (fc50f328b 2019-04-24)
- **Diesel:** 1.4.2
- **Database:** psql (PostgreSQL) 11.4
- **Operating System** it's arch, a rolling release

### Feature Flags

- **diesel:** ["postgres", "r2d2",  "chrono"]

## Problem Description
For a geo spatial search system I need the geography type. For which I used https://github.com/Boscop/diesel-geography and followed the instructions.

However within the schema generation I get an error

### What are you trying to accomplish?
I want to have the option not to use manual cartesian transformations to calculate radial searches.

### What is the expected output?
A finished working schema for this: 

```SQL
CREATE TABLE resource (
  id            SERIAL PRIMARY KEY,
  url           VARCHAR(500) NOT NULL,
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE resource_detail (
    resource_id INTEGER NOT NULL PRIMARY KEY REFERENCES resource(id) ON DELETE CASCADE ON UPDATE CASCADE,
    street_name VARCHAR(255) NOT NULL,
    street_number VARCHAR(10) NOT NULL,
    zip_code VARCHAR(10) NOT NULL,
    location Geography NULL,
    pricing INTEGER NULL,
    currently_used BOOL DEFAULT false,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```

### What is the actual output?
Diesel only supports tables with primary keys. Table spatial_ref_sys has no primary key

Just to clarify the table spatial_ref_sys is system generated and has a primary key.

```sql
create table spatial_ref_sys
(
	srid integer not null
		constraint spatial_ref_sys_pkey
			primary key
		constraint spatial_ref_sys_srid_check
			check ((srid > 0) AND (srid <= 998999)),
	auth_name varchar(256),
	auth_srid integer,
	srtext varchar(2048),
	proj4text varchar(2048)
);
```

### Steps to reproduce
* use diesel + diesel-geography to get the needed types 
* install the postgis extension on your operation system
* create the postgis extension in your database 

```sql
\c databasename;
CREATE EXTENSION Postgis;
```
try to run the schema generation.

I guess I am missing something obvious. To me the guess would be that the way the srid primary key is constructed isn't fully supported in diesel? But I am just formulating arbitrary guesses here.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment] 2019-07-19 17:52
I'm attempting to reproduce with the extension now (I couldn't reproduce by copy/pasting the schema for that table you provided). However, while I do that I just want to clarify:

Do you actually need the schema for that table? Based on your "expected output" given, I'd assume not. If that's the case, you can tell Diesel to ignore that table. http://diesel.rs/guides/configuring-diesel-cli/#the-filter-field

**Comment by sgrif** [comment] 2019-07-19 18:04
I was unable to reproduce this issue with the steps provided. I attempted to create the problematic schema both by copy pasting the provided table, and by running `create extension Postgis;`. In both cases, I saw the following output from `diesel print-schema`:

```
table! {
    spatial_ref_sys (srid) {
        srid -> Int4,
        auth_name -> Nullable<Varchar>,
        auth_srid -> Nullable<Int4>,
        srtext -> Nullable<Varchar>,
        proj4text -> Nullable<Varchar>,
    }
}
```

You may want to confirm that the table does in fact have a primary key on your database. It may have been modified or created with a different query than the one you referenced here. Alternatively, you can ignore the table using the docs linked in my previous comment.

Since there doesn't appear to be a bug here, I'm going to close this. If you still believe this to be a bug in Diesel, please provide steps we can use to reproduce the issue, and I'll reopen it.

**Closed by sgrif** 2019-07-19 18:04 UTC

**Comment by chilimatic** [comment] 2019-07-20 16:59
@sgrif you're right, I don't need a schema for the table it's generated automatically from the systemside. 

So I will go for the ignore :) thx for you help :) I will try it asap.
