### ISSUE TITLE
Re-export the `sqlite3-bundled` feature of libsqlite3-sys

### ISSUE THREAD

**Issue by udoprog** [diesel-rs/diesel#3587] opened 2023-04-07 20:19 UTC
This elaborates on the discussion in https://github.com/diesel-rs/diesel/discussions/3255

Without bundling, sqlite3 fails to link at least on Windows if there's no `sqlite3.lib` static lib available (which there usually isn't by default):

```
= note: LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'
```

These are my dependencies:

```toml
libsqlite3-sys = { version = "0.25.2", features = ["bundled", "unlock_notify"] }
diesel = { version = "2.0.3", features = ["sqlite", "chrono"] }
diesel_migrations = "2.0.0"
```

I explicitly add `libsqlite3-sys` because I need the `bundled` feature, but this leads to complicated version requirements in my project. This has frequently lead to a local `cargo upgrade` causing the build to break. In this instance, `cargo upgrade` bumped `libsqlite3-sys` to `0.26.0`:

```
    Updating crates.io index
error: failed to select a version for `libsqlite3-sys`.
    ... required by package `diesel v2.0.3`
    ... which satisfies dependency `diesel = "~2.0.0"` of package `diesel_migrations v2.0.0`
    ... which satisfies dependency `diesel_migrations = "^2.0.0"` of package `oxidize v0.0.0 (D:\Repo\projects\repos\OxidizeBot\bot)`
versions that meet the requirements `>=0.17.2, <0.26.0` are: 0.25.2, 0.25.1, 0.25.0, 0.24.2, 0.24.1, 0.24.0, 0.23.2, 0.23.1, 0.23.0, 0.22.2, 0.22.1, 0.22.0, 0.20.1, 0.20.0, 0.18.0, 0.17.3, 0.17.2

the package `libsqlite3-sys` links to the native library `sqlite3`, but it conflicts with a previous package which links to `sqlite3` as well:
package `libsqlite3-sys v0.26.0`
    ... which satisfies dependency `libsqlite3-sys = "^0.26.0"` of package `oxidize v0.0.0 (D:\Repo\projects\repos\OxidizeBot\bot)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='libsqlite3-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `libsqlite3-sys` which could resolve this conflict
```

By using a re-exported `sqlite3-bundled` feature instead, a local `cargo upgrade` wouldn't update the `libsqlite3-sys` version until `diesel` specifically is ready for it:

```toml
# don't really care what the feature is called :)
diesel = { version = "2.0.3", features = ["sqlite", "chrono", "sqlite3-bundled"] }
diesel_migrations = "2.0.0"
```

### Versions

- **Rust: rustc 1.68.2 (9eb3afe9e 2023-03-27)**
- **Diesel: 2.0.3**
- **Database: sqlite3**
- **Operating System: Windows**

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-04-08 11:57
That's not a bug report, so it shouldn't be opened in our issue tracker. As there is already an open feature request discussion for this I'm closing that issue in favor of the existing discussion. Feel free to add your arguments there.

**Closed by weiznich** 2023-04-08 11:57 UTC
Labels: bug

**Comment by udoprog** [comment] 2023-04-08 13:02
The issue here is the build error you get when depending on `diesel` and using cargo to update your dependencies. It should be treated as any dependency issues causing build failures. Alternatively I could go and file an issue with `cargo upgrade`, but it would be harder for them to fix it since this is a local dependency which transitively breaks because of `diesel` and they can't be sure whether or not it's appropriate to upgrade it.

**Comment by weiznich** [comment] 2023-04-09 16:36
`cargo update` shouldn't update your `libsqlite3-sys` version automatically, as long as you don't put a `*` version selection there. In the later case you explicitly opt in into getting any potentially incompatible version, so it's expected that things break. If you put a version there that's initially compatible with your diesel version it will not break as long as you don't update diesel itself. And if you update diesel itself, it will not break as long as you don't perform a major version update, although newer diesel versions might support newer libsqlite3-sys versions.

It's different for `cargo upgrade`:
The second build error (that one with cannot find a matching version) is  how `-sys` dependencies are threaded by rustc. They can only appear once in the whole dependency tree. So it's arguably a bug in `cargo upgrade` if they update such an dependency without being able to update all appearances of such an dependency. 

> The local dependency is also only in place to activate features in libsqlite3-sys because it's used through diesel.

Again that's by design. Cargo features are additive for exactly that reasons.

**Comment by udoprog** [comment] 2023-04-09 17:00
So it seems you've acknowledged this is an issue. Can we keep this bug report open then until it's been fixed in cargo or you change your mind and decide to re-export the feature?

**Comment by udoprog** [comment] 2023-04-09 17:10
Reported upstream, see linked issue.

I would also note that the reason re-exporting would address this issue is because there would be no *local* dependency for `cargo upgrade` to touch. However, my preferred solution is still that it's fixed upstream in `cargo`.

**Comment by weiznich** [comment] 2023-04-14 15:23
Thanks for reporting this issue upstream. 

> So it seems you've acknowledged this is an issue. Can we keep this bug report open then until it's been fixed in cargo or you change your mind and decide to re-export the feature?

Open issues in our issue tracker generally represent something that's actionable. That's not the case here.

> But the simplest solution right now is still undeniably for diesel to re-export the feature.

That's simplifies things as that only represents your perspective. From the perspective of the maintainer this solution does not really scale. We cannot reexport all features form all dependencies. Even if we could do that we would run into issues as soon as we want to test all that features. That's just not possible, therefore we need to carefully select which features to expose. With the current feature set we are already at a point where adding new features is hard due to the testing issues. If you have a solution for that I'm happy to hear that.
