### ISSUE TITLE
Diesel does not compile on Mac M1

### ISSUE THREAD

**Issue by solidiquis** [diesel-rs/diesel#2897] opened 2021-09-12 20:38 UTC
## Setup

`cargo.tml`
```
[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
```

`main.rs`
```rust
#[macro_use]
extern crate diesel;

use diesel::prelude::*;
use diesel::pg::PgConnection;

pub fn establish_connection() -> PgConnection {

    let database_url = "postgres://cthulhu@localhost/cthulhu_development";

    PgConnection::establish(&database_url)
        .expect(&format!("Error connecting to {}", database_url))
}

fn main() {
    let conn = establish_connection();
}

```

### Versions

- **Rust:** 1.54
- **Diesel:** 1.4.7
- **Database:** Postgres 13.4
- **Operating System** MacOS Big Sur M1

### Feature Flags

- **diesel:**

## Problem Description

Diesel is failing to compile because of the following warning: 
` ld: warning: ignoring file /usr/local/opt/postgresql/lib/libpq.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64`

### What are you trying to accomplish?
Trying to install Diesel and Diesel-Cli.

### What is the expected output?
Simply trying to establish a connection to PG.

### What is the actual output?
```
...
  = note: ld: warning: ignoring file /usr/local/opt/postgresql/lib/libpq.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
...
```
  
### Steps to reproduce

`$ cargo run` with the code above,

## Checklist

- [ x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-09-13 07:07
Duplicate of https://github.com/diesel-rs/diesel/issues/2605 + That's a linker issue which should not be filled in the issue tracker at all as this is an issue with our specific enviroment

**Closed by weiznich** 2021-09-13 07:07 UTC
Labels: bug
