### ISSUE TITLE
Timestamp columns in Postgres create 'trait bound is not satisfied' errors in Rust

### ISSUE THREAD

**Issue by jakerieger** [diesel-rs/diesel#3487] opened 2023-01-19 04:31 UTC
### Versions

- **Rust:** 1.62.1
- **Diesel:** 2.0.1
- **Database:** Postgres
- **Operating System** Ubuntu 22.04

### Feature Flags

- **diesel:** postgres, r2d2

## Problem Description
Attempting to query against tables with `timestamp` or `timestamp no timezone` types results in a `trait bound is not satisfied` compiler error. Any table that doesn't include a `timestamp` column type works fine.

### What are you trying to accomplish?
Simply getting the first row of a table.

### What is the expected output?
Store the query result in a variable of the desired db model type.

### What is the actual output?
None. Compiler error

This is the schema for a test table in PG:
|id|date_created|
|--|------------|
|[PK] integer|timestamp without time zone|

This maps to the following in `schema.rs`:
```rs
diesel::table! {
    TestTable (id) {
        id -> Int4,
        date_created -> Timestamp,
    }
}
```

and my model looks like this:
```rs
#[derive(Queryable, Debug)]
pub struct TestTable {
    pub id: i32,
    pub date_created: NaiveDateTime,
}
```

Now, when attempting to do the following, I get the compiler error:
```rs
use crate::models::{TestTable as TT};
use crate::schema::TestTable::dsl::*;
use diesel::prelude::*;

...
// the method called on TestTable doesn't matter, I'm just using .first() since it doesn't require any other methods to return the result
// The only exception is that .find() works but that's the only method I've found that doesn't return an error
let first_res: TT = TestTable.first(connection).expect("");
```

This is the full compiler error output:
```
the trait bound `(i32, NaiveDateTime): FromStaticSqlRow<(Integer, diesel::sql_types::Timestamp), Pg>` is not satisfied
the following other types implement trait `FromStaticSqlRow<ST, DB>`:
  <(T0,) as FromStaticSqlRow<(ST0,), __DB>>
  <(T1, T0) as FromStaticSqlRow<(ST1, ST0), __DB>>
  <(T1, T2, T0) as FromStaticSqlRow<(ST1, ST2, ST0), __DB>>
  <(T1, T2, T3, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST0), __DB>>
  <(T1, T2, T3, T4, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST4, ST0), __DB>>
  <(T1, T2, T3, T4, T5, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST4, ST5, ST0), __DB>>
  <(T1, T2, T3, T4, T5, T6, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, ST0), __DB>>
  <(T1, T2, T3, T4, T5, T6, T7, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, ST7, ST0), __DB>>
and 24 others
required because of the requirements on the impl of `FromSqlRow<(Integer, diesel::sql_types::Timestamp), Pg>` for `models::TestTable`
required because of the requirements on the impl of `load_dsl::private::CompatibleType<models::TestTable, Pg>` for `(Integer, diesel::sql_types::Timestamp)`
required because of the requirements on the impl of `LoadQuery<'_, PooledConnection<ConnectionManager<PgConnection>>, models::TestTable>` for `SelectStatement<FromClause<schema::TestTable::table>, query_builder::select_clause::DefaultSelectClause<FromClause<schema::TestTable::table>>, query_builder::distinct_clause::NoDistinctClause, query_builder::where_clause::NoWhereClause, query_builder::order_clause::NoOrderClause, query_builder::limit_offset_clause::LimitOffsetClause<query_builder::limit_clause::LimitClause<diesel::internal::derives::as_expression::Bound<diesel::sql_types::BigInt, i64>>, query_builder::offset_clause::NoOffsetClause>>`
```

### Things I've tried
- Verifying that `NOT NULL` is enabled in PG for the date column
- Messing with different DateTime types in chrono (DateTime<Utc>, NaiveDate, etc)

It just seems like diesel can't resolve the Timestamp type. I'm not sure how to fix this as I've come across a few other forum posts regarding the issue and they all come down to mismatched types between PG and Rust and I've double-checked all my mappings, even following this table:
https://gist.github.com/steveh/7c7145409a5eed6b698ee8b609b6d1fc#file-postgresql-diesel-rust-types-md

**Comment by Mingun** [comment] 2023-01-19 06:14
It seems you should enable `chrono` feature

**Comment by weiznich** [comment] 2023-01-19 07:14
Yes this is due to a missing `chrono` feature on OP's side.

I'm closing this issue as our issue tracker is no support forum and that's clearly a users error (it's explicitly documentation in quite a lot of places that this feature is required)

@jakerieger For future reports: Please do not remove parts of the issue template, search for duplicates first and prefer to use the discussion forum for questions that are not clearly a bug in diesel. (In anycase: That would have been either a feature request "Support that type mapping" or a question: "What's wrong with my code", but not a bug report).

**Closed by weiznich** 2023-01-19 07:14 UTC
Labels: bug
