### ISSUE TITLE
The sql_query cannot perform a complex SQL

### ISSUE THREAD

**Issue by jiuliyemingzhi** [diesel-rs/diesel#4078] opened 2024-06-20 22:19 UTC
### Versions

- **Rust:**
- **Diesel:**
- **Database:**
- **Operating System**

### Feature Flags

- **diesel:**

## Problem Description
**I don t know how to map the content of the SELECT to the load function**
```sql
WITH top_comments(count, id) AS (SELECT count(1) over (), id
                                 FROM tb_comment
                                 WHERE article_id = ?
                                   AND parent_id IS NULL
                                   AND status IN ('REVIEWED', 'WAIT_R')
                                 LIMIT ? OFFSET ?),
     sub_comments AS (SELECT id
                      FROM (SELECT row_number()
                                   over (PARTITION BY parent_id ORDER BY score DESC, updated_at DESC) as rn,
                                   id
                            FROM tb_comment
                            WHERE parent_id in (SELECT id FROM top_comments)
                              AND status IN ('REVIEWED', 'WAIT_R')) as ri
                      WHERE ri.rn < 3)
SELECT  tc.*, ta.author_name, ta.id, ta.avatar, ta.level, ta.sign, top.count as count,
FROM tb_comment tc
         INNER JOIN tb_author ta ON tc.author_id = ta.id
         LEFT JOIN top_comments top ON top.id = tc.id OR top.id = tc.parent_id
WHERE tc.id in ((SELECT id FROM top_comments) UNION (SELECT id FROM sub_comments));
```
```rust
    let comments = sql_query(ARTICLE_RELATION_COMMENTS_SQL)
        .bind::<BigInt, _>(article_id.0)
        .bind::<SmallInt, _>(limit)
        .bind::<SmallInt, _>(offset)
        .load::<AuthorComment>(&mut get_db_connection()?)?;
    Ok(PageHelper {
        total: comments.first().map(|v| v.1).unwrap_or(0),
        data: comments.into_iter().map(|v| v.0).collect(),
    })
```
## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2024-06-28 12:52
I'm sorry but it's not clear what you exactly want to know. Additionally this is definitely not a bug report that belongs to our issue tracker but a support request that belongs into one of the support channels. 

Closed as this is not a bug report. Feel free to open a new discussion that outlines the problem you are trying to solve with more details. Generally speaking: the more details you actually provide on your problem the easier it is for us to help and the more likely it is that you get the answers you are looking for.

**Closed by weiznich** 2024-06-28 12:52 UTC
Labels: bug
