### ISSUE TITLE
`debug_query` + batch insert with SQLite results in a compilation error

### ISSUE THREAD

**Issue by netvl** [diesel-rs/diesel#2258] opened 2019-12-30 07:48 UTC
### Versions

- **Rust:** rustc 1.40.0 (73528e339 2019-12-16)
- **Diesel:** 1.4.3
- **Database:** SQLite
- **Operating System:** Linux

### Feature Flags

- **diesel:** sqlite

## Problem Description

`debug_query` does not work with batch inserts and SQLite.

### What are you trying to accomplish?

```rust
let mappings: Vec<_> = ...;
let q = diesel::insert_into(analysis_chats::table).values(mappings);
println!("{}", diesel::debug_query::<Sqlite, _>(&q));
```

### What is the expected output?

INSERT being printed to the console. It does not seem that I do anything which requires the `DEFAULT` support from the database, and most definitely it should not affect debug printing - if I remove debug printing, my code works just fine.

### What is the actual output?

Compilation error:

```
error[E0277]: the trait bound `diesel::sqlite::Sqlite: diesel::backend::SupportsDefaultKeyword` is not satisfied
  --> src/db/analyses.rs:72:40
   |
72 |                 debug!(""; "query" => %diesel::debug_query::<Sqlite, _>(&q));
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `diesel::backend::SupportsDefaultKeyword` is not implemented for `diesel::sqlite::Sqlite`
   |
   = note: required because of the requirements on the impl of `diesel::query_builder::QueryFragment<diesel::sqlite::Sqlite>` for `diesel::insertable::OwnedBatchInsert<diesel::query_builder::ValuesClause<(diesel::insertable::ColumnInsertValue<db::schema::analysis_chats::columns::analysis_id, diesel::expression::bound::Bound<diesel::sql_types::BigInt, i64>>, diesel::insertable::ColumnInsertValue<db::schema::analysis_chats::columns::chat_id, diesel::expression::bound::Bound<diesel::sql_types::BigInt, i64>>), db::schema::analysis_chats::table>, db::schema::analysis_chats::table>`
   = note: required because of the requirements on the impl of `diesel::query_builder::QueryFragment<diesel::sqlite::Sqlite>` for `diesel::query_builder::InsertStatement<db::schema::analysis_chats::table, diesel::insertable::OwnedBatchInsert<diesel::query_builder::ValuesClause<(diesel::insertable::ColumnInsertValue<db::schema::analysis_chats::columns::analysis_id, diesel::expression::bound::Bound<diesel::sql_types::BigInt, i64>>, diesel::insertable::ColumnInsertValue<db::schema::analysis_chats::columns::chat_id, diesel::expression::bound::Bound<diesel::sql_types::BigInt, i64>>), db::schema::analysis_chats::table>, db::schema::analysis_chats::table>>`
   = note: required because of the requirements on the impl of `std::fmt::Display` for `diesel::query_builder::DebugQuery<'_, diesel::query_builder::InsertStatement<db::schema::analysis_chats::table, diesel::insertable::OwnedBatchInsert<diesel::query_builder::ValuesClause<(diesel::insertable::ColumnInsertValue<db::schema::analysis_chats::columns::analysis_id, diesel::expression::bound::Bound<diesel::sql_types::BigInt, i64>>, diesel::insertable::ColumnInsertValue<db::schema::analysis_chats::columns::chat_id, diesel::expression::bound::Bound<diesel::sql_types::BigInt, i64>>), db::schema::analysis_chats::table>, db::schema::analysis_chats::table>>, diesel::sqlite::Sqlite>`
   = note: required by `std::fmt::Display::fmt`
```

### Are you seeing any additional errors?

No

### Steps to reproduce

Can be reproduced reliably with the code specified above - any kind of table + INSERT of a vector will result in this error.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment] 2019-12-30 22:04
I'm not sure if I would call that expected behaviour or if that's a bug that should be fixed. It's definitely not surprising for me.
The underlying issue here is: Sqlite does not support batch inserts. Diesel does provide support for this feature, because we think it's something that is used quite often. We do this by just doing an insert per item inside of an transaction. That means we do not have one query but N + 2 queries here. `debug_query` currently only works with `QueryFragment` (so something that is one query at max). It is possible to fix that by adding some manual impls at the right place (See #2260), but I'm not sure if that's desired (cc @diesel-rs/contributors )

**Comment by netvl** [comment] 2019-12-31 07:54
I see, totally makes sense. The important thing, I think, is to have an ability to debug a query in any possible way, and I think that #2260 solves this nicely.

**Closed** 2020-01-06 19:48 UTC
