### ISSUE TITLE
Improve derive functionality (skip and defaults)

### ISSUE THREAD

**Issue by theduke** [diesel-rs/diesel#1574] opened 2018-02-25 19:23 UTC
I often want a few tweaks to the various derivable traits that would improve quality of life quite a bit.

They are mostly inspired by serde_derive, which has similar features.

If this is ok with the maintainers, I'd start working on a PR for this.

### Skip

Allow skipping of fields for `AsChangeset` and `Insertable`.
A plain skip would already be useful.
What would be even more useful is selective skipping eg only for updates.

```rust
#[derive(Insertable, AsChangeset)]
#[table_name....]
struct User {
    id: Uuid,
    username: String,
    #[diesel(skip_on = "update")]
    created_at: DateTime<Utc>,
    
    #[diesel(skip)]
    extra_non_db_field: Vec<_>,
}
```

### Default

```rust
#[derive(Queryable)]
...
struct User {
    ....
     // Will use Default::default()
     #[diesel(default)]
    extra_value: Option<_>,
    // Will use custom function
     #[diesel(default = "::user::whatever_default")]
    extra_value: Whatever,
}
```

## Attribute names

It seems to be an established practice to wrap attributes with the crate name to be more specific, a la `serde(...)`, ...
It's somewhat ok for things like `table_name` and `primary_key`, but 
not really for `default` and `skip`, since they are so generic. 
So i'd propose wrapping for those.

Actually, I'd also propose adding new variants for the existing attributes, and maybe at some point deprecating the old ones, but that's another discussion.

**Comment by sgrif** [comment] 2018-02-26 20:20
Duplicate of #860.

**Closed by sgrif** 2018-02-26 20:20 UTC
