### ISSUE TITLE
failed to compile `diesel_cli v2.0.1`, intermediate artifacts can be found at `/tmp/cargo-installv5uKqO`

### ISSUE THREAD

**Issue by FrankyLee-dev** [diesel-rs/diesel#3602] opened 2023-04-19 07:15 UTC
## Setup
```cargo install diesel_cli --no-default-features --features sqlite```

### Versions

- **Rust:**rustc 1.68.2 (9eb3afe9e 2023-03-27)
- **Diesel:**diesel = { version = "2", features = ["sqlite", "r2d2"] }
- **Database:**3.41.2 2023-03-22 11:56:21 0d1fc92f94cb6b76bffe3ec34d69cffde2924203304e8ffc4155597af0c191da
- **Operating System**CentOS release 6.10 (Final)

### Feature Flags

- **diesel:**

## Problem Description
compile failure

### What are you trying to accomplish?
install diesel_cli

### What is the expected output?
install success

### What is the actual output?
```
   Compiling diesel_cli v2.0.1
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-0.el6_10.x86_64/bin:/root/bin:/usr/local/git/bin:/root/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcLeyAud/symbols.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.0.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.1.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.10.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.11.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.12.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.13.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.14.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.15.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.2.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.3.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.4.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.5.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.6.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.7.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.8.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.diesel.bca00d57-cgu.9.rcgu.o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16.3yze06irdfqy9j1p.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installv5uKqO/release/deps" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installv5uKqO/release/deps/libdiffy-fc9a8ec848d1c8ea.rlib" "/tmp/cargo-installv5uKqO/release/deps/libnu_ansi_term-e4d4388bab01d4e9.rlib" "/tmp/cargo-installv5uKqO/release/deps/liboverload-e8b83785fde20bd3.rlib" "/tmp/cargo-installv5uKqO/release/deps/liburl-a6846204d43c835f.rlib" "/tmp/cargo-installv5uKqO/release/deps/libidna-13ae6d038c638bcc.rlib" "/tmp/cargo-installv5uKqO/release/deps/libunicode_normalization-292805a87a29ef89.rlib" "/tmp/cargo-installv5uKqO/release/deps/libtinyvec-184852ac0c13535c.rlib" "/tmp/cargo-installv5uKqO/release/deps/libtinyvec_macros-7bb7cb433c2201bb.rlib" "/tmp/cargo-installv5uKqO/release/deps/libunicode_bidi-7f9ee104de8564fc.rlib" "/tmp/cargo-installv5uKqO/release/deps/libform_urlencoded-51823256b58fdab2.rlib" "/tmp/cargo-installv5uKqO/release/deps/libpercent_encoding-e2ca8dc84d28439e.rlib" "/tmp/cargo-installv5uKqO/release/deps/libdotenvy-8287176bf81a238b.rlib" "/tmp/cargo-installv5uKqO/release/deps/libchrono-1ef9da0a1e10f911.rlib" "/tmp/cargo-installv5uKqO/release/deps/libiana_time_zone-bb355ecb288521a2.rlib" "/tmp/cargo-installv5uKqO/release/deps/libnum_integer-115151c055b8b928.rlib" "/tmp/cargo-installv5uKqO/release/deps/libnum_traits-c9b0f029bd0d59b1.rlib" "/tmp/cargo-installv5uKqO/release/deps/libserde_regex-86cab6bf852df0d4.rlib" "/tmp/cargo-installv5uKqO/release/deps/libregex-7167774a23191df9.rlib" "/tmp/cargo-installv5uKqO/release/deps/libaho_corasick-4433db8dd5f3d5a1.rlib" "/tmp/cargo-installv5uKqO/release/deps/libmemchr-2cbe141a73b58ecf.rlib" "/tmp/cargo-installv5uKqO/release/deps/libregex_syntax-57c75579a8fceb80.rlib" "/tmp/cargo-installv5uKqO/release/deps/libclap_complete-a8d67de77f15add5.rlib" "/tmp/cargo-installv5uKqO/release/deps/libdiesel_migrations-61abb0c1af4516d4.rlib" "/tmp/cargo-installv5uKqO/release/deps/libmigrations_internals-f8fe892de10f0ad7.rlib" "/tmp/cargo-installv5uKqO/release/deps/libtoml-21ac619555538893.rlib" "/tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib" "/tmp/cargo-installv5uKqO/release/deps/liblibsqlite3_sys-460001830c7f58ba.rlib" "/tmp/cargo-installv5uKqO/release/deps/libclap-fde9329d6e201e28.rlib" "/tmp/cargo-installv5uKqO/release/deps/libatty-02ace1e64a74e4fa.rlib" "/tmp/cargo-installv5uKqO/release/deps/liblibc-078ba7d93201986f.rlib" "/tmp/cargo-installv5uKqO/release/deps/libstrsim-9a43b68493e6bbb3.rlib" "/tmp/cargo-installv5uKqO/release/deps/libtermcolor-54e2058bccb36775.rlib" "/tmp/cargo-installv5uKqO/release/deps/libtextwrap-fe7223d844720eae.rlib" "/tmp/cargo-installv5uKqO/release/deps/libclap_lex-60caaf20c6f96195.rlib" "/tmp/cargo-installv5uKqO/release/deps/libos_str_bytes-5503d28d18575baa.rlib" "/tmp/cargo-installv5uKqO/release/deps/libindexmap-e3168abf5852927d.rlib" "/tmp/cargo-installv5uKqO/release/deps/libhashbrown-676958b935c4a7cc.rlib" "/tmp/cargo-installv5uKqO/release/deps/libbitflags-d708dc7fb6cd55fa.rlib" "/tmp/cargo-installv5uKqO/release/deps/libserde-1c36d95fc920b701.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-bc6b80525d6b1f3b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-dbb416fff97e9855.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-af60be54961a030f.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-1303bc5098cb2f44.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-96ca4807f9d03fdf.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-03b108942351d49a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-b348df34b7d8ac11.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-26a06d9c5ec29d3a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-b5295fdab67e4cf6.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-b257ed099e7f67d0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-c27b5dca54e295d8.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-f6c8245d52afa66d.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-642c68f15c02cc52.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-eecd84150c4ad967.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-123ffa13a38501db.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-2177aff67f4e9999.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2298a66e03bd0fd2.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-f3c3b25345711552.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-10f041ff25bad5f3.rlib" "-Wl,-Bdynamic" "-lsqlite3" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installv5uKqO/release/deps/diesel-58f8d9567b263e16" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.1.rcgu.o): In function `diesel::sqlite::connection::stmt::Statement::prepare::h0f07ab3879227a8d':
          diesel.fd34477e-cgu.1:(.text._ZN6diesel6sqlite10connection4stmt9Statement7prepare17h0f07ab3879227a8dE+0x95): undefined reference to `sqlite3_prepare_v3'
          /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.11.rcgu.o): In function `core::ptr::drop_in_place$LT$diesel..sqlite..connection..row..PrivateSqliteRow$GT$::hcc45ad68c15e21af':
          diesel.fd34477e-cgu.11:(.text._ZN4core3ptr70drop_in_place$LT$diesel..sqlite..connection..row..PrivateSqliteRow$GT$17hcc45ad68c15e21afE+0x34): undefined reference to `sqlite3_value_free'
          /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.14.rcgu.o): In function `_ZN4core3ptr97drop_in_place$LT$core..cell..RefCell$LT$diesel..sqlite..connection..row..PrivateSqliteRow$GT$$GT$17hc0d1c24275a0aa6fE.llvm.2150976919655279612':
          diesel.fd34477e-cgu.14:(.text._ZN4core3ptr97drop_in_place$LT$core..cell..RefCell$LT$diesel..sqlite..connection..row..PrivateSqliteRow$GT$$GT$17hc0d1c24275a0aa6fE.llvm.2150976919655279612+0x3c): undefined reference to `sqlite3_value_free'
          /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.2.rcgu.o): In function `_ZN4core3ptr107drop_in_place$LT$core..option..Option$LT$diesel..sqlite..connection..sqlite_value..OwnedSqliteValue$GT$$GT$17h307f44020d7ae754E.llvm.15466431327026373401':
          diesel.fd34477e-cgu.2:(.text._ZN4core3ptr107drop_in_place$LT$core..option..Option$LT$diesel..sqlite..connection..sqlite_value..OwnedSqliteValue$GT$$GT$17h307f44020d7ae754E.llvm.15466431327026373401+0xa): undefined reference to `sqlite3_value_free'
          /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.2.rcgu.o): In function `_ZN4core3ptr130drop_in_place$LT$alloc..vec..Vec$LT$core..option..Option$LT$diesel..sqlite..connection..sqlite_value..OwnedSqliteValue$GT$$GT$$GT$17h6a0f34b4f344db78E.llvm.15466431327026373401':
          diesel.fd34477e-cgu.2:(.text._ZN4core3ptr130drop_in_place$LT$alloc..vec..Vec$LT$core..option..Option$LT$diesel..sqlite..connection..sqlite_value..OwnedSqliteValue$GT$$GT$$GT$17h6a0f34b4f344db78E.llvm.15466431327026373401+0x28): undefined reference to `sqlite3_value_free'
          /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.2.rcgu.o): In function `_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter..SpecFromIter$LT$T$C$I$GT$$GT$::from_iter::h8dd31b0648f95da3':
          diesel.fd34477e-cgu.2:(.text._ZN98_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter..SpecFromIter$LT$T$C$I$GT$$GT$9from_iter17h8dd31b0648f95da3E+0x8d): undefined reference to `sqlite3_value_dup'
          /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.2.rcgu.o): In function `_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter..SpecFromIter$LT$T$C$I$GT$$GT$::from_iter::ha6689a322e66d7eb':
          diesel.fd34477e-cgu.2:(.text._ZN98_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter..SpecFromIter$LT$T$C$I$GT$$GT$9from_iter17ha6689a322e66d7ebE+0x108): undefined reference to `sqlite3_value_dup'
          /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.5.rcgu.o): In function `_ZN4core3ptr130drop_in_place$LT$alloc..vec..Vec$LT$core..option..Option$LT$diesel..sqlite..connection..sqlite_value..OwnedSqliteValue$GT$$GT$$GT$17h6a0f34b4f344db78E.llvm.9613247669315693833':
          diesel.fd34477e-cgu.5:(.text._ZN4core3ptr130drop_in_place$LT$alloc..vec..Vec$LT$core..option..Option$LT$diesel..sqlite..connection..sqlite_value..OwnedSqliteValue$GT$$GT$$GT$17h6a0f34b4f344db78E.llvm.9613247669315693833+0x28): undefined reference to `sqlite3_value_free'
          /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.6.rcgu.o): In function `diesel::sqlite::connection::raw::RawConnection::register_sql_function::h47ffb60713ab3ead':
          diesel.fd34477e-cgu.6:(.text._ZN6diesel6sqlite10connection3raw13RawConnection21register_sql_function17h47ffb60713ab3eadE+0x123): undefined reference to `sqlite3_create_function_v2'
          /tmp/cargo-installv5uKqO/release/deps/libdiesel-084f9a32f917f686.rlib(diesel-084f9a32f917f686.diesel.fd34477e-cgu.9.rcgu.o): In function `_$LT$diesel..sqlite..connection..sqlite_value..OwnedSqliteValue$u20$as$u20$core..ops..drop..Drop$GT$::drop::h1d59b7f0ced18ad9':
          diesel.fd34477e-cgu.9:(.text._ZN100_$LT$diesel..sqlite..connection..sqlite_value..OwnedSqliteValue$u20$as$u20$core..ops..drop..Drop$GT$4drop17h1d59b7f0ced18ad9E+0x5): undefined reference to `sqlite3_value_free'
          collect2: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `diesel_cli` due to previous error
error: failed to compile `diesel_cli v2.0.1`, intermediate artifacts can be found at `/tmp/cargo-installv5uKqO`
```

### Are you seeing any additional errors?
No

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-04-19 07:18
The error message indicates that this is a duplicate of https://github.com/diesel-rs/diesel/issues/3520

**Closed by weiznich** 2023-04-19 07:18 UTC
Labels: bug
