### ISSUE TITLE
grouped_by doesn't seem to consistently honor foreign keys

### ISSUE THREAD

**Issue by joshuaclayton** [diesel-rs/diesel#2490] opened 2020-08-25 03:44 UTC
### Versions

- **Rust:** stable 1.45.0
- **Diesel:** 1.4.4
- **Database:** sqlite
- **Operating System** macOS

### Feature Flags

- **diesel:** `sqlite`

## Problem Description

Calling `grouped_by` for structs with multiple `belongs_to` doesn't seem to pick up the foreign keys correctly; more specifically, `belonging_to` returns the correct data, but using `grouped_by` when a table has multiple foreign keys doesn't seem to select the correct foreign keys correctly all the time.

I noticed this when creating a domain for some financial transaction tracking software, where a transaction has foreign keys to the account (e.g. checking vs credit card), a merchant (e.g. Chipotle), and a category (e.g. Restaurant). In grouping transactions by merchant, and calculating additional information based, I noticed that the first 11 merchants had data, but none of the remaining did (I've got ~2k merchants). I *did*, however, only have 11 account records. This led me to believe that it was grouping erroneously on the account id rather than merchant ids when organizing transactions.

### What are you trying to accomplish?

I'd like for the results of `grouped_by` to support multiple foreign keys.

### What is the expected output?

The grouped transactions align with the merchants in my system.

### What is the actual output?

The grouped transactions align with a different foreign key (accounts).

### Are you seeing any additional errors?

No

### Steps to reproduce

I've created a fully working repo with corresponding migration and a simple script to run to reliably reproduce failure: https://github.com/joshuaclayton/diesel-grouped-by-bug

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues. The closest is https://github.com/diesel-rs/diesel/issues/2298, but it seems like for a different reason/goal
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case). This occurs in both stable and nightly.

**Comment by joshuaclayton** [comment] 2020-08-26 03:02
As it turns out, I was wrong on a number of counts – firstly, it's not `grouped_by`, and is in fact the `belonging_to` that's not behaving the way I expected.

I also able to get it to work by using an explicit `inner_join` on the appropriate table rather than use `belonging_to`. I'm not sure if *that* is a bug, or if `belonging_to` can only infer if there's a single `belongs_to(Parent)`.

**Comment by weiznich** [comment] 2020-09-15 15:33
As documented in multiple places: The field order for structs deriving `Queryable` is important. (See for example [here](http://docs.diesel.rs/1.4.x/diesel/deserialize/trait.Queryable.html#deriving))

If I fix the `Transaction` struct in your example to the correct order, your test case works fine.

```rust
#[derive(Identifiable, Associations, Clone, Debug, Queryable)]
#[belongs_to(Category)]
#[belongs_to(Merchant)]
#[belongs_to(Account)]
pub struct Transaction {
    pub id: i32,
    pub category_id: i32,
    pub merchant_id: i32,
    pub account_id: i32,
    pub amount: i32,
}
```

Closed as this is not a bug in diesel itself.

**Closed by weiznich** 2020-09-15 15:33 UTC
