### ISSUE TITLE
Encountered unknown type for Mysql: enum

### ISSUE THREAD

**Issue by OverloaderV** [diesel-rs/diesel#3584] opened 2023-04-06 19:55 UTC
### Versions

- **Rust:**  v1.68.2
- **Diesel:** idk. when i try to run `diesel -v` i get this:
```
❯ diesel -v
error: Found argument '-v' which wasn't expected, or isn't valid in this context

	If you tried to supply `-v` as a value rather than a flag, use `-- -v`
```
- **Database:** 10.11.2-MariaDB Arch Linux
- **Operating System** arch linux with the following kernel: `6.2.9-arch1-1-patched` A patch is applied to fix sound drivers, shouldn't influence anything

### What are you trying to accomplish?

I'm trying to run a migration to create a table:
```sql
-- create the users table
CREATE TABLE users (
    id BINARY(16) PRIMARY KEY,
    userName VARCHAR(40) NOT NULL UNIQUE,
    displayName VARCHAR(40) NOT NULL UNIQUE,
    gender ENUM('male', 'female', 'diverse') NOT NULL
);

-- create the users_auto_id trigger to automatically generate the id field
CREATE TRIGGER `users_auto_id` BEFORE INSERT ON `users`
FOR EACH ROW
SET NEW.id =UUID_TO_BIN(UUID());
```

### What is the expected output?

For the migration to run normally

### What is the actual output?

The database and trigger are created
However diesel shows this error:
```
❯ diesel migration redo
Rolling back migration 2023-04-06-190312_users
Running migration 2023-04-06-190312_users
Encountered unknown type for Mysql: enum
thread 'main' panicked at 'internal error: entered unreachable code: Mysql only supports a closed set of types.
                         If you ever see this error message please open an issue at https://github.com/diesel-rs/diesel containing a dump of your schema definition.', /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_cli-2.0.1/src/print_schema.rs:313:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The schema definition is added above

### Steps to reproduce

The migration is the only code i have so far so it should be easy to reproduce

## Checklist

- [x ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-04-07 06:57
Duplicate of #3386
Fixed in #3530, but not released yet.

**Closed** 2023-04-07 06:58 UTC
Labels: bug
