### ISSUE TITLE
The documentation mentions that the format of the migrations is the format of migrations/{current_timestamp}_{migration_name} but they are created differently

### ISSUE THREAD

**Issue by danechitoaie** [diesel-rs/diesel#4082] opened 2024-06-24 22:58 UTC
### Versions

- **Rust:** 1.79.0
- **Diesel:** 2.2.1
- **Database:** Postgres
- **Operating System** MacOS

### Feature Flags

- **diesel:** postgres

## Problem Description
The documentation mentions that the format of the migrations is the format of `migrations/{current_timestamp}_{migration_name}` but they are actually created as:
```
> diesel migration generate create_organizations
Creating migrations/2024-06-24-225518_create_organizations/up.sql
Creating migrations/2024-06-24-225518_create_organizations/down.sql
```

Anyway to set it up to use the format as described in the docs? 

Problem is that the first migration is created like this:
```
00000000000000_diesel_initial_setup
```

So it's weird that they don't have the same format.

**Comment by weiznich** [comment] 2024-06-28 10:12
This is expected. This first migration uses a legacy version format that unfortunately cannot be changed due to backward compatibility reasons. 

Closed as this is not a bug but working as expected.

**Closed by weiznich** 2024-06-28 10:12 UTC
Labels: bug

**Comment by danechitoaie** [comment] 2024-06-28 11:30
>This first migration uses a legacy version format that unfortunately cannot be changed due to backward compatibility reasons.

Maybe for backward compatibility reasons it would make sense to be supported when we run the migrations (existing projects) but when new projects run the setup we could generate the initial migration with the new format? As existing projects won't run setup again, they will just have their already existing migrations and they will just do migrate/undo.

**Comment by weiznich** [comment] 2024-06-28 13:10
We might accept a PR for that, but honestly that is just something nobody cared to do yet.
