### ISSUE TITLE
Schema inference not supported on CockroachDB 

### ISSUE THREAD

**Issue by jethrogb** [diesel-rs/diesel#523] opened 2016-12-05 23:12 UTC
Thanks to CockroachDB's protocol compatibility, it almost works out of the box. There are just some minor things that need fixing:

- In Postgres terms, CockroachDB does not have databases. Only schemas inside a single database. This breaks inference (unless your database is named “public”).
- CockroachDB's `information_schema.columns.data_type` values are different.
  - `INT` is `diesel::types::BigInt`
  - `STRING` is `diesel::types::Text`
  - (others?)

You can detect CockroachDB like so: `SELECT version() LIKE 'CockroachDB%';`

Of course, to make the example code work with BigInt, I also needed to change the Rust datatype in the model and code to `i64`.

**Comment by theduke** [comment] 2018-04-29 07:50
Duplicate of #1134, so can be closed.
(Actually, this issue is older, but the other one has more disussion).

@diesel-rs/diesel

**Comment by awoods187** [comment] 2020-03-19 22:27
PM at Cockroach Labs here. We'd love it if you added support for CockroachDB. Let us know if you run into any problems.

**Comment by weiznich** [comment] 2020-03-20 10:58
@awoods187 We do not have any concrete plans to support CockroachDB. To copy the official comments given in #1134 here:

> I think modifying the existing postgres backend in diesel to workaround the quirks of cockroachdb is the wrong way.
In my opinion the right solution would be to implement a new backend (this can and should be done outside of diesel) and then add support for this backend in diesel_cli.
The main reason for this is that this makes it much easier to support the different features offered by various backends.
For implementing the new backend the existing postgres backend could be used as starting point .Maybe just copy the existing backend to a new crate, get it compiling (== fix all imports and dependencies), and then add the needed modifications to it. 

[From this gitter comment](https://gitter.im/diesel-rs/diesel?at=5ae597c35d7286b43a7ccbbf)

and

> It's important that it's maintained outside of Diesel though. Nobody on the core team uses cockroachdb, the adapter should be maintained by someone who knows what does or doesn't work there, and is more actively using it

[From this gitter comment](https://gitter.im/diesel-rs/diesel?at=5ae5ee9e7c3a01610d32ce40)

That means we are happy to answer question and provide some guidance about how support for CockroachDB could be provided as third party backend, but we won't implement that on our own. If there is any API missing to provide such a third party backend we are also happy to figure out those issues and add the required API.

I'm closing this issue, as this is nothing actionable for as as diesel team.

**Closed by weiznich** 2020-03-20 10:58 UTC
