### ISSUE TITLE
cannot find macro `__diesel_parse_table` in this scope

### ISSUE THREAD

**Issue by vidyli** [diesel-rs/diesel#2703] opened 2021-04-07 09:39 UTC
```
use diesel::table;

table! {
    user (user_id) {
        user_id -> Unsigned<Integer>,
        username -> Nullable<Varchar>,
        password -> Varchar,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        email -> Nullable<Varchar>,
        failures_num -> Nullable<Smallint>,
        first_failed_at -> Nullable<Timestamp>,
        lock_expires_at -> Nullable<Timestamp>,
        enabled -> Smallint,
        salt -> Nullable<Varchar>,
    }
}

```
Got this error
```
error: cannot find macro `__diesel_parse_table` in this scope
  --> src/schema.rs:3:1
   |
3  | / table! {
4  | |     user (user_id) {
5  | |         user_id -> Unsigned<Integer>,
6  | |         username -> Nullable<Varchar>,
...  |
16 | |     }
17 | | }
   | |_^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by vidyli** [comment] 2021-04-07 09:44
the `use diesel::table;` should be changed to `use diesel::prulude::*;`

**Comment by weiznich** [comment] 2021-04-07 10:27
This neither uses our issue template nor searched for duplicated issues. Therefore I will close this bug as invalid. Feel free to update the description with something more in line with our template + explain why this isn't a duplicate of existing issues.

**Closed by weiznich** 2021-04-07 10:27 UTC
Labels: bug
