### ISSUE TITLE
Compile error when compiling to `x86_64-unknown-linux-musl`

### ISSUE THREAD

**Issue by s3pt3mb3r** [diesel-rs/diesel#2908] opened 2021-09-23 04:33 UTC
### Versions

- **Rust:** rustup 1.24.3,   cargo 1.54.0
- **Diesel:** 1.4.4
- **Database:** Mysql
- **Operating System** macOS 10.15.7

### Feature Flags

- **diesel:** mysql

## Problem Description
When I tried to cross compile the code which includes `MysqlConnection::establish(&database_url)` into x86_64-unknown-inux-musl, the compile error occurred.

### What are you trying to accomplish?
I want to extract the data on Amazon RDS(mysql). And compile the code to linux.
### What is the expected output?
nothing.

### What is the actual output?
```
linking with `x86_64-linux-musl-gcc` failed: exit status: 1
note: "x86_64-linux-musl-gcc" "-m64" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/rcrt1.o" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crti.o" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crtbeginS.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.0.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.1.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.10.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.2.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.3.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.4.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.5.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.6.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.7.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.8.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.comperrtest.46e00mlo-cgu.9.rcgu.o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d.4idy8gp0fvly42sg.rcgu.o" "-Wl,--as-needed" "-L" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps" "-L" "/Users/am4ne/comperrtest/target/release/deps" "-L" "/usr/local/Cellar/mysql/8.0.26/lib" "-L" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libserde-25ef45a96525f778.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdotenv-bee9a5f8ac7db773.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/liburl-3654f815a960fa82.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libpercent_encoding-7b935dc9c8c1947c.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libidna-1500b49c9dbe4a76.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libunicode_normalization-aba5bc696f41cb55.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libtinyvec-5570cb87c89bea90.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libtinyvec_macros-7d4aedb18c0d3a0a.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libunicode_bidi-1ba1c5bd600092d2.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libmatches-f23a5361476f5b16.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libmysqlclient_sys-5ed0bca9c0edabae.rlib" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libbyteorder-80ceb08e242c3c47.rlib" "-Wl,--start-group" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd-3cef741c1f23cd93.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libpanic_unwind-5904caeef8e7aa23.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libminiz_oxide-0f5d37d268b96a61.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libadler-1ff87fa6e88a9656.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libobject-f8edfa7653afcf66.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libaddr2line-6d98eb92dbccf787.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libgimli-decc06f51028e61b.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd_detect-5e6b49cc149a60ba.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_demangle-7a66b3aa9e458fc4.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libhashbrown-21fcab01894b7eab.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_alloc-b976dd002d97b145.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libunwind-690c23a0bc1a60cd.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libcfg_if-b5c6753552da2f2e.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/liblibc-859ab3522b9428e1.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/liballoc-52e7a767563a753d.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-1c16b776a1e56741.rlib" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-9190e7d88a759acf.rlib" "-Wl,--end-group" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-3fa3b1d70121d65d.rlib" "-Wl,-Bdynamic" "-lmysqlclient" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-nostartfiles" "-L" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib" "-L" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained" "-o" "/Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/comperrtest-66ef7a410b08c83d" "-Wl,--gc-sections" "-static-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crtendS.o" "/Users/am4ne/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crtn.o"
  = note: /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.10.rcgu.o): in function `_ZN4core3ptr66drop_in_place$LT$diesel..mysql..connection..raw..RawConnection$GT$17h87e398ba37643a80E.llvm.11712507098252010845':
          diesel.5l0d58ra-cgu.10:(.text._ZN4core3ptr66drop_in_place$LT$diesel..mysql..connection..raw..RawConnection$GT$17h87e398ba37643a80E.llvm.11712507098252010845+0x5): undefined reference to `mysql_close'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.10.rcgu.o): in function `diesel::mysql::connection::raw::RawConnection::new':
          diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection3new17hba4ce9f8b1056096E+0x16): undefined reference to `mysql_init'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection3new17hba4ce9f8b1056096E+0x38): undefined reference to `mysql_options'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection3new17hba4ce9f8b1056096E+0x7b): undefined reference to `mysql_init'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.10.rcgu.o): in function `diesel::mysql::connection::raw::RawConnection::connect':
          diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7connect17h8322e743850d96a4E+0x45): undefined reference to `mysql_real_connect'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7connect17h8322e743850d96a4E+0x4e): undefined reference to `mysql_error'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.10.rcgu.o): in function `diesel::mysql::connection::raw::RawConnection::execute':
          diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7execute17h776eb947f4a1ec17E+0x1f): undefined reference to `mysql_real_query'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7execute17h776eb947f4a1ec17E+0x41): undefined reference to `mysql_store_result'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7execute17h776eb947f4a1ec17E+0x4f): undefined reference to `mysql_free_result'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7execute17h776eb947f4a1ec17E+0x71): undefined reference to `mysql_more_results'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7execute17h776eb947f4a1ec17E+0x7c): undefined reference to `mysql_next_result'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7execute17h776eb947f4a1ec17E+0x88): undefined reference to `mysql_store_result'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7execute17h776eb947f4a1ec17E+0x8f): undefined reference to `mysql_more_results'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection7execute17h776eb947f4a1ec17E+0xca): undefined reference to `mysql_free_result'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.10.rcgu.o): in function `_ZN6diesel5mysql10connection3raw13RawConnection18did_an_error_occur17h9d6f9136f854f61dE.llvm.11712507098252010845':
          diesel.5l0d58ra-cgu.10:(.text._ZN6diesel5mysql10connection3raw13RawConnection18did_an_error_occur17h9d6f9136f854f61dE.llvm.11712507098252010845+0x15): undefined reference to `mysql_error'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.10.rcgu.o): in function `<diesel::mysql::connection::raw::RawConnection as core::ops::drop::Drop>::drop':
          diesel.5l0d58ra-cgu.10:(.text._ZN87_$LT$diesel..mysql..connection..raw..RawConnection$u20$as$u20$core..ops..drop..Drop$GT$4drop17h83b9bc37a56c5f76E+0x5): undefined reference to `mysql_close'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.13.rcgu.o): in function `core::ptr::drop_in_place<diesel::mysql::connection::MysqlConnection>':
          diesel.5l0d58ra-cgu.13:(.text._ZN4core3ptr63drop_in_place$LT$diesel..mysql..connection..MysqlConnection$GT$17he9eec9f764ff99fcE+0x9): undefined reference to `mysql_close'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.13.rcgu.o): in function `core::ptr::drop_in_place<diesel::mysql::connection::raw::RawConnection>':
          diesel.5l0d58ra-cgu.13:(.text._ZN4core3ptr66drop_in_place$LT$diesel..mysql..connection..raw..RawConnection$GT$17h87e398ba37643a80E+0x5): undefined reference to `mysql_close'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.13.rcgu.o): in function `<diesel::mysql::connection::MysqlConnection as diesel::connection::Connection>::establish':
          diesel.5l0d58ra-cgu.13:(.text._ZN93_$LT$diesel..mysql..connection..MysqlConnection$u20$as$u20$diesel..connection..Connection$GT$9establish17h62d6a530d089a61bE+0x1a2): undefined reference to `mysql_affected_rows'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.13:(.text._ZN93_$LT$diesel..mysql..connection..MysqlConnection$u20$as$u20$diesel..connection..Connection$GT$9establish17h62d6a530d089a61bE+0x1d9): undefined reference to `mysql_affected_rows'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.13:(.text._ZN93_$LT$diesel..mysql..connection..MysqlConnection$u20$as$u20$diesel..connection..Connection$GT$9establish17h62d6a530d089a61bE+0x210): undefined reference to `mysql_affected_rows'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.13:(.text._ZN93_$LT$diesel..mysql..connection..MysqlConnection$u20$as$u20$diesel..connection..Connection$GT$9establish17h62d6a530d089a61bE+0x243): undefined reference to `mysql_affected_rows'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.13:(.text._ZN93_$LT$diesel..mysql..connection..MysqlConnection$u20$as$u20$diesel..connection..Connection$GT$9establish17h62d6a530d089a61bE+0x276): undefined reference to `mysql_affected_rows'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.13:(.text._ZN93_$LT$diesel..mysql..connection..MysqlConnection$u20$as$u20$diesel..connection..Connection$GT$9establish17h62d6a530d089a61bE+0x425): undefined reference to `mysql_close'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: diesel.5l0d58ra-cgu.13:(.text._ZN93_$LT$diesel..mysql..connection..MysqlConnection$u20$as$u20$diesel..connection..Connection$GT$9establish17h62d6a530d089a61bE+0x4d0): undefined reference to `mysql_close'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.14.rcgu.o): in function `<diesel::mysql::connection::stmt::Statement as core::ops::drop::Drop>::drop':
          diesel.5l0d58ra-cgu.14:(.text._ZN84_$LT$diesel..mysql..connection..stmt..Statement$u20$as$u20$core..ops..drop..Drop$GT$4drop17h7f0943cd48f5b867E+0x5): undefined reference to `mysql_stmt_close'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.6.rcgu.o): in function `_ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17h98bb31b1dfae0312E.llvm.18332410263376938588':
          diesel.5l0d58ra-cgu.6:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17h98bb31b1dfae0312E.llvm.18332410263376938588+0x14): undefined reference to `mysql_server_init'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.6.rcgu.o): in function `_ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h3920b3429f78126aE.llvm.18332410263376938588':
          diesel.5l0d58ra-cgu.6:(.text._ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h3920b3429f78126aE.llvm.18332410263376938588+0x14): undefined reference to `mysql_server_init'
          /usr/local/Cellar/musl-cross/0.9.9_1/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /Users/am4ne/comperrtest/target/x86_64-unknown-linux-musl/release/deps/libdiesel-5a79489c35085cab.rlib(diesel-5a79489c35085cab.diesel.5l0d58ra-cgu.0.rcgu.o): in function `<hashbrown::raw::RawTable<T,A> as core::ops::drop::Drop>::drop':
          diesel.5l0d58ra-cgu.0:(.text._ZN79_$LT$hashbrown..raw..RawTable$LT$T$C$A$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17hab6d4e443320114cE+0x10d): undefined reference to `mysql_stmt_close'
          collect2: error: ld returned 1 exit status
```

### Steps to reproduce
I made a public repo [here](https://github.com/s3pt3mb3r/diesel_musl_issue).
To fully reproduce, please set ENDPOINT.COM to RDS server endpoint.

This repo doesnt include third party crate except serde and dotenv as diesel uses in the example.

## Checklist

- [- ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ -] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [- ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-09-23 07:44
As any linker error this is related to your environment, not to diesel. You need to provide a compatible version of libmysqlclient compiled for the correct target. 
Closed as this is a duplicate of a lot of already existing issues. If you have future questions about this please use any other support channel. Our issue tracker is not the right place to ask this kind of questions.

**Closed by weiznich** 2021-09-23 07:44 UTC
Labels: bug
