### ISSUE TITLE
`diesel migrations redo` doesn't respect `run_in_transaction` migration metadata

### ISSUE THREAD

**Issue by DianaNites** [diesel-rs/diesel#3506] opened 2023-02-04 13:49 UTC
### Versions

- **Rust:** rustc 1.67.0 
- **Diesel:** 2.0.3
- **Database:** sqlite 3.40.1
- **Operating System** Arch Linux

### Feature Flags

- **diesel:** "sqlite", "time"
- **diesel_cli:** "sqlite"

## Problem Description

The `diesel migrations redo` command doesn't respect the `run_in_transaction` migration metadata, while `run` and `revert` separately do.

This seems to be because it is [hard-coded](https://github.com/diesel-rs/diesel/blob/8afb1bb47f31a292c7853f6cb48145231994ee7e/diesel_cli/src/main.rs#L452-L474) to use a transaction for anything except mysql, specifically for the redo command.

### What are you trying to accomplish?

A migration that needs to handle transactions itself

Specifically temporarily turn off an [sqlite specific pragma](https://www.sqlite.org/pragma.html#pragma_foreign_keys) as dictated [here](https://www.sqlite.org/foreignkeys.html#fk_schemacommands), which cannot be done inside a transaction.

### What is the expected output?

```
Rolling back migration <migration>
Running migration <migration>
```

### What is the actual output?

```
Rolling back migration <migration>
Failed to run <migration> with: cannot start a transaction within a transaction
```

### Steps to reproduce

- `diesel migration generate example`
- Add the following

```toml
# example/metadata.toml
run_in_transaction = false
```

```sql
-- example/up.sql
BEGIN TRANSACTION;
COMMIT TRANSACTION;
```

```sql
-- example/down.sql
BEGIN TRANSACTION;
COMMIT TRANSACTION;
```

- Run `diesel migration run` and see it works as expected
- Run `diesel migration revert` and see it works as expected
- Run `diesel migration redo` and see it fail

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-02-06 11:35
Thanks for the report. Yes that's a bug and it should be fixed.

**Comment by JosueMolinaMorales** [comment] 2023-03-03 19:44
> Thanks for the report. Yes that's a bug and it should be fixed. Contributions are welcome.

I can take a look at this if this is still an open issue?

**Comment by weiznich** [comment] 2023-03-03 19:54
This issue is still open. Contributions are welcome. The issue is in these lines of code
  https://github.com/diesel-rs/diesel/blob/master/diesel_cli/src/migrations/mod.rs#L324-L330

**Comment by JosueMolinaMorales** [comment] 2023-03-03 19:55
Awesome, ill take a look at it.

**Closed** 2023-05-15 20:20 UTC
Labels: bug, cli
