### ISSUE TITLE
 macros in diesel-cli generated source don't have "diesel::" prefix

### ISSUE THREAD

**Issue by sify21** [diesel-rs/diesel#2461] opened 2020-07-19 14:10 UTC
In my generated schema.rs, It's not `diesel::table!` like in the examples(https://github.com/diesel-rs/diesel/blob/master/examples/mysql/getting_started_step_1/src/schema.rs), but just `table!` . So I have to `#[macro_use]extern crate diesel` in my lib.rs/main.rs, which is deprecated(https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html)

How do I make the macros in generated schema.rs get the `diesel::` prefix?

diesel-cli version: 1.4.1
database backend: mysql

**Comment by weiznich** [comment] 2020-07-19 16:41
Duplicate of #1764.
(This is expected behaviour for diesel 1.4.x)
Also you are looking at the examples for the master branch, not for the latest release.)

**Closed by weiznich** 2020-07-19 16:41 UTC
