### ISSUE TITLE
duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by esguti** [diesel-rs/diesel#2687] opened 2021-03-18 10:00 UTC
## Setup

Having a Postgres DB, with two elements inserted:

```sql
CREATE TABLE machines (
  id SERIAL PRIMARY KEY,
  enabled BOOLEAN NOT NULL,
);
INSERT INTO machines (id,enabled) VALUES (1,true);
INSERT INTO machines (id,enabled) VALUES (2,false);
```

Diesel with the following features and versions:

### Versions

- **Rust:** 1.50.0
- **Diesel:** 1.4.5
- **Database:** psql (PostgreSQL) 12.6
- **Operating System** Ubuntu 20

### Feature Flags

- **diesel:** "postgres", "r2d2", "network-address", "chrono"

## Problem Description

When I try to insert a "machine" in the table, it fails twice and 3rd time it success in inserting the value.

### What are you trying to accomplish?

Insert a machine in the DB

### What is the expected output?

Success first time

### What is the actual output?

Fails as many times as values are already inserted in the DB

### Steps to reproduce

This is my code:

```rust
#[derive(Serialize, AsChangeset, Deserialize, Insertable)]
#[table_name = "machines"]
pub struct Machine {
    pub enabled: bool,
}
impl Machine {
    fn from(machine: Machine) -> Machine {
        Machine {
            ip: machine.ip,
            enabled: machine.enabled,
        }
    }
}

#[derive(Serialize, Deserialize, Queryable)]
pub struct Machines {
    pub id: i32,
    pub enabled: bool,
}
impl Machines {
    pub fn create(machine: Machine) -> Result<Self, CustomError> {
        let conn = db::connection()?;
        let machine = Machine::from(machine);
        println!(
            "{}",
            debug_query::<Pg, _>(&diesel::insert_into(machines::table).values(&machine))
        );
        let machine = diesel::insert_into(machines::table)
            .values(machine)
            .get_result(&conn)?;
        Ok(machine)
    }
}

```

## Checklist

The query debug output shows the same query executed three times:

```bash
INSERT INTO "machines" ("enabled") VALUES ($1) -- binds: [false]
[2021-03-18T09:25:39Z ERROR blabla_api::error_handler] Response error: duplicate key value violates unique constraint "machines_pkey"
[2021-03-18T09:25:39Z ERROR blabla_api::error_handler] Response error: duplicate key value violates unique constraint "machines_pkey"
INSERT INTO "machines" ("enabled") VALUES ($1) -- binds: [false]
[2021-03-18T09:29:22Z ERROR blabla_api::error_handler] Response error: duplicate key value violates unique constraint "machines_pkey"
[2021-03-18T09:29:22Z ERROR blabla_api::error_handler] Response error: duplicate key value violates unique constraint "machines_pkey"
INSERT INTO "machines" ("enabled") VALUES ($1) -- binds: [false]
```

**Comment by weiznich** [comment] 2021-03-18 10:17
Please add more information or a reduced example. In the current form that's not reproducible for anyone as the actual values to reproduce the problem are missing. If the information are not added in the next days I will close this issue as cannot reproduce.

**Comment by esguti** [comment] 2021-03-18 11:32
@weiznich  you have a functional example in this [repository](https://github.com/esguti/rust-diesel-fail-example)

**Comment by weiznich** [comment] 2021-03-18 12:14
This is not diesel related, but an issue with your migration. The next value of the id sequence will be 1. A entry of this value is already part of your database table because of your explicit insert statements in your migration.
You can alter the sequence by using [`ALTER SEQUENCE`](https://www.postgresql.org/docs/current/sql-altersequence.html)

Closed as this is not an issue in diesel itself.

**Closed by weiznich** 2021-03-18 12:14 UTC
Labels: bug

**Comment by esguti** [comment] 2021-03-18 12:26
Thank you, I have corrected the error in the [example code](https://github.com/esguti/rust-diesel-fail-example/commit/094982927dfd28bb9b9a7e188d4781275cff88e9)
