### ISSUE TITLE
The avg sample code cannot be run on mysql

### ISSUE THREAD

**Issue by januwA** [diesel-rs/diesel#3113] opened 2022-04-04 05:32 UTC
### Versions

- **Rust:**1.59.0
- **Diesel:**1.4.4
- **Database:**mysql
- **Operating System**CentOS Stream 8

### Feature Flags

- **diesel:**

### Steps to reproduce

Aggregate query I wrote following the example code in the documentation

[://docs.diesel.rs/1.4.x/diesel/dsl/fn.avg.html](https://docs.diesel.rs/1.4.x/diesel/dsl/fn.avg.html)

```
        let avg1 = books.select(avg(price)).get_result(&conn)?;
        println!("{}", avg1);
```

but got an error

```
equired because of the requirements on the impl of `LoadQuery<PooledConnection<ConnectionManager<MysqlConnection>>, ()>` for `diesel::query_builder::SelectStatement<schema::books::table, query_builder::select_clause::SelectClause<aggregate_folding::avg::avg<diesel::sql_types::Numeric, schema::books::columns::price>>>`
note: required by a bound in `get_result`
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.8/src/query_dsl/mod.rs:1288:15
```

Since mysql can't use get_result, what method should I use to run the examples in the documentation correctly

**Comment by weiznich** [comment] 2022-04-04 07:01
Please provide a complete bug report. This includes any information requested in the issue template, a complete minimal reproducible example and if available the complete error message as emitted by rustc. Otherwise it's not possible to reproduce your issue.
As a side note: We have multiple test cases covering this. For example the linked doc test. That means you should provide more evidence than just a comment that it does not work for you, at least if you fill a bug report. 
If the requested information are not provided I will close this issue as cannot reproduce.

**Closed** 2022-04-04 07:24 UTC
Labels: bug
