### ISSUE TITLE
Conflicting trait implementations caused by Insertable, Queryable derivations.

### ISSUE THREAD

**Issue by SergioBenitez** [diesel-rs/diesel#498] opened 2016-11-21 21:32 UTC
Starting with the 11/19 nightly (possibly before as well), using Diesel's derive macros results in the following errors:

```rust
error[E0119]: conflicting implementations of trait `std::fmt::Debug` for type `task::Task`:
  --> src/task.rs:16:32
   |
16 | #[derive(Serialize, Queryable, Insertable, Debug, Clone)]
   |                                ^^^^^^^^^^  ----- first implementation here
   |                                |
   |                                conflicting implementation for `task::Task`

error[E0119]: conflicting implementations of trait `std::clone::Clone` for type `task::Task`:
  --> src/task.rs:16:32
   |
16 | #[derive(Serialize, Queryable, Insertable, Debug, Clone)]
   |                                ^^^^^^^^^^         ----- first implementation here
   |                                |
   |                                conflicting implementation for `task::Task`

error[E0119]: conflicting implementations of trait `std::fmt::Debug` for type `task::Task`:
  --> src/task.rs:16:21
   |
16 | #[derive(Serialize, Queryable, Insertable, Debug, Clone)]
   |                     ^^^^^^^^^              ----- first implementation here
   |                     |
   |                     conflicting implementation for `task::Task`

error[E0119]: conflicting implementations of trait `std::clone::Clone` for type `task::Task`:
  --> src/task.rs:16:21
   |
16 | #[derive(Serialize, Queryable, Insertable, Debug, Clone)]
   |                     ^^^^^^^^^                     ----- first implementation here
   |                     |
   |                     conflicting implementation for `task::Task`

error[E0119]: conflicting implementations of trait `std::fmt::Debug` for type `task::Task`:
  --> src/task.rs:16:21
   |
16 | #[derive(Serialize, Queryable, Insertable, Debug, Clone)]
   |                     ^^^^^^^^^              ----- first implementation here
   |                     |
   |                     conflicting implementation for `task::Task`

error[E0119]: conflicting implementations of trait `std::clone::Clone` for type `task::Task`:
  --> src/task.rs:16:21
   |
16 | #[derive(Serialize, Queryable, Insertable, Debug, Clone)]
   |                     ^^^^^^^^^                     ----- first implementation here
   |                     |
   |                     conflicting implementation for `task::Task`

error[E0119]: conflicting implementations of trait `diesel::Insertable<task::schema::tasks::table, _>` for type `&task::Task`:
  --> src/task.rs:16:1
   |
16 | #[derive(Serialize, Queryable, Insertable, Debug, Clone)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | first implementation here
   | conflicting implementation for `&task::Task`
   |
   = note: this error originates in a macro outside of the current crate
```

The struct definition and Diesel imports look like this:

```rust
mod schema {
    infer_schema!("db/db.sql");
}

use diesel;
use diesel::prelude::*;
use self::schema::tasks;
use self::schema::tasks::dsl::{tasks as all_tasks, completed as task_completed};

#[table_name = "tasks"]
#[derive(Serialize, Queryable, Insertable, Debug, Clone)]
pub struct Task {
    id: Option<i32>,
    pub description: String,
    pub completed: Option<bool>
}
```

**Comment by sgrif** [comment] 2016-11-22 14:37
Duplicate of #496

**Closed by sgrif** 2016-11-22 14:37 UTC

**Comment by sgrif** [comment] 2016-11-22 17:51
0.8.2 has been released with a fix
