### ISSUE TITLE
i saw this and is there a way to disable it calling?

### ISSUE THREAD

**Issue by sprappcom** [diesel-rs/diesel#4150] opened 2024-08-06 14:24 UTC
how to disable these? is there a way to disable these messages? else this is a bug. I've already set as default in my mysql config so i dont need these keep on calling the db with the same configuration always. how to disable this?

i've tried setting this below using chatgpt4 suggestion but it's not working.
```
// Define a connection customizer to set configuration options
#[derive(Debug)]
struct ConnectionCustomizer;

impl r2d2::CustomizeConnection<MysqlConnection, diesel::r2d2::Error> for ConnectionCustomizer {
    fn on_acquire(&self, conn: &mut MysqlConnection) -> Result<(), diesel::r2d2::Error> {

```

https://github.com/diesel-rs/diesel/issues/3112

                   124 Prepare  SET character_set_client = 'utf8mb4'
                   124 Execute  SET character_set_client = 'utf8mb4'
                   124 Close stmt
                   124 Prepare  SET character_set_connection = 'utf8mb4'
                   124 Execute  SET character_set_connection = 'utf8mb4'
                   124 Close stmt
                   124 Prepare  SET character_set_results = 'utf8mb4'
                   124 Execute  SET character_set_results = 'utf8mb4'
                   124 Prepare  SET time_zone = '+00:00'
                   124 Execute  SET time_zone = '+00:00'

### Versions

- **Rust:** latest nightly
- **Diesel:** latest
- **Database:** mariadb
- **Operating System** ubuntu 24.04

p.s. : i dont want any set character or set time stuff just because i'm using rustlang diesel

**Comment by weiznich** [comment] 2024-08-06 15:08
This is a duplicate of #3112. Diesel relies on this settings for consistency and correctness reasons. Therefore we don't provide a way to disable this settings for the built-in connection types. You can bring your own connection type with different defaults, check the documentation of the Connection trait for details. 

Closed as duplicate and as does not follow the mandatory issue template

**Closed** 2024-08-06 15:08 UTC
Labels: bug

**Comment by sprappcom** [comment] 2024-08-06 15:58
@weiznich can u pls help out?

https://pastebin.com/B24j1u7J

i've tried plenty ways. costs a lot of openai api money. please help. i can sponsor you some coffees in exchange for not using ai anymore on this issue.
it's extremely annoying.
no matter what i tried, i cant seem to get these not shown:
```
                  2980 Prepare  SET character_set_connection = 'utf8mb4'
                  2980 Execute  SET character_set_connection = 'utf8mb4'
                  2981 Prepare  SET time_zone = '+00:00'
                  2981 Execute  SET time_zone = '+00:00'
                  2980 Close stmt
                  2980 Prepare  SET character_set_results = 'utf8mb4'
                  2980 Execute  SET character_set_results = 'utf8mb4'
                  2981 Close stmt
                  2980 Close stmt
                  2981 Prepare  SET character_set_client = 'utf8mb4' 
                  2981 Execute  SET character_set_client = 'utf8mb4'
```

pls allow me to sponsor you some coffees for resolving this.

i dont understand why diesel needs to call this at all. seemed like a diesel only issue. i've used other mysql client in other programming languages and not once i've come across this kind of queries as mandatory. pls help. thx

**Comment by weiznich** [comment] 2024-08-06 18:32
@sprappcom First of all our issue tracker is no support forum. I don't provide any support here. 

That written: The reasons for that behaviour are explained in the commits and issues linked from the other answer. These are critical for diesel to work in a safe way. We don't support disabled that. If you want to disable them you are outside of what's supported which means you are on your own there.

**Comment by sprappcom** [comment] 2024-08-07 01:50
@weiznich ok thx. i've checked it before. if u see my original post, i've posted the link inside. but as i check, i may understand that utc is needed BUT i cant understand why the charsets are.

but seriously, u can just inform users to force timezone and charset stuff in the config so it's not called all the time.

**Comment by weiznich** [comment] 2024-08-07 06:29
> BUT i cant understand why the charsets are.

The charset is required as rusts strings are UTF-8, so using any other charset would need a lot of complexity for handling them (if that's even possible).

> but seriously, u can just inform users to force timezone and charset stuff in the config so it's not called all the time.

That's not a good solution as these defaults are sane for the vast majority of our users. As already written before: You can opt out of these defaults if you bring your own connection type. 

I'm not interested in continuing this discussion and as already written I do not see anything that can change on diesels side here. That's my last comment on this topic.
