### ISSUE TITLE
Is there a way to use strong types like `UserId`?

### ISSUE THREAD

**Issue by vityafx** [diesel-rs/diesel#1014] opened 2017-07-10 15:31 UTC
For example, I have a table `users` with `id INTEGER PRIMARY KEY`. Is there a way to use `pub struct UserId(pub i32)` instead of `i32` for the user id?

**Comment by killercup** [comment] 2017-07-10 15:40
I don't think this is _easily_ possible right now—you'd need to implement a bunch of traits, like ToSql and FromSql, cf. [this test](https://github.com/diesel-rs/diesel/blob/3509db04c78b3344daa6bce394001423b2386e7b/diesel_tests/tests/types.rs#L635-L673).

It'd be possible to write `derive` macro that makes common newtype case (for wrappers of primitive sql types) a bit more elegant by generating the implementations for you.

**Comment by sgrif** [comment] 2017-07-10 15:53
I think that would be a strong candidate for something that should best live as a third party crate, not as part of Diesel itself. However, I'm happy to assist someone in implementing such a crate.

**Comment by killercup** [comment] 2017-07-10 15:54
Oh yes, I meant as an external proc-macro crate.

(This might copy a bunch of code from the diesel-internal implementations of primitive SQL types, though.)

**Comment by sgrif** [comment] 2017-07-10 16:17
It shouldn't need to. The impls should all be able to look something like:

```rust
pub struct UserId(pub i32);

impl<ST, DB> ToSql<ST, DB> for UserId
where
    i32: ToSql<ST, DB>,
{
    fn to_sql(...) {
        self.0.to_sql(...)
    }
}
````

**Comment by Eijebong** [comment] 2017-07-10 16:20
I think you'd also need the `HasSqlType` trait which is a bit more difficult as it's different for every backend.

**Comment by sgrif** [comment] 2017-07-10 17:01
@Eijebong This isn't implementing a new SQL type.

**Comment by Eijebong** [comment] 2017-07-10 17:08
Oh, right, this is the same trait for every backend... I'm dumb :)

**Comment by quodlibetor** [comment] 2017-07-13 03:14
I've just implemented a `DieselNewType` custom derive which seems to work, although I'm not sure what stress-testing it would look like: https://github.com/quodlibetor/diesel-newtype 

I would appreciate some eyes on it (bug reports/pull requests). If the name seems reasonable and we can get it into good enough shape I'm happy to upload it to crates.io and/or move it into the diesel-rs org.

**Comment by sgrif** [comment] 2017-07-13 03:20
> I've only been using it for about an hour, and before this I hadn't actually tried sticking my newtypes into the DB via Diesel, so there are probably unknown unknowns

Lol I'd probably start with trying that out. ;)

**Comment by sgrif** [comment] 2017-07-13 03:20
> Doesn't try to handle generics at all. I haven't encountered generics on newtypes so I didn't bother. They should be easy to add

This seems reasonable to me.

**Comment by sgrif** [comment] 2017-07-13 03:20
> It seems almost... too... easy...

That's the goal. ;)

**Comment by sgrif** [comment] 2017-07-13 03:23
I've only given it a cursory look, but it looks fine at first glance. You're missing a lot of impls that are required to use the newtype in every context you could use `String`. Particularly, you'll need `AsExpression` impls for every combination of nullable/not and reference/not, along with `FromSqlRow` for nullable/not. You'll want a `Queryable` impl as well so they can query for the newtype directly. [These](https://github.com/diesel-rs/diesel/blob/7235f2ff6162b88a488756a7600fb461f4d4bded/diesel/src/types/impls/mod.rs#L14-L95) are the impls that we have for our primitive types

**Comment by quodlibetor** [comment] 2017-07-13 03:25
I've been _wanting_ to create newtypes, but I've been too lazy to actually do the various From/Tos, so I just created a "ToUnderlying" trait that only my db modules have access to, and have been using that.

With this I've swapped out a couple of my IDs in a couple of structs and, like I said, it _seems_ to do... oh you've responded.

Those all look easy enough, thanks! I'm heading out for the weekend soon, but I should be able to implement them early next week if no one beats me to it.

**Comment by quodlibetor** [comment] 2017-07-13 03:28
I couldn't find any obvious way of verifying that my derive generates something reasonable, is there an example test file that guarantees that everything works without a db, or should I just bite the bullet and copy your db setup code?

**Comment by sgrif** [comment] 2017-07-13 03:29
You'll want to verify against an actual database. Anything else will only be testing your assumptions.

**Comment by quodlibetor** [comment] 2017-07-13 03:34
And here I've been assuming my assumptions were great. That makes my decision making easier.

**Comment by Fiedzia** [comment] 2017-07-13 16:07
Could we have it as an example in the docs and tests?

**Comment by quodlibetor** [comment] 2017-07-13 16:27
Have what as an example in which docs/tests?

**Comment by Fiedzia** [comment] 2017-07-13 17:51
UserId as an example of having custom type, explaining what one needs to do
to achieve that.

**Comment by quodlibetor** [comment] 2017-07-13 17:54
Ah, yeah a "custom types" guide, explaining what each trait enables as you implement it, would be nice to have. I might be able to write something like that as I add tests and discover additional functionality for diesel-newtype.

**Comment by Fiedzia** [comment] 2017-07-14 13:07
Exactly

**Comment by quodlibetor** [comment] 2017-07-29 23:36
I've implemented (thanks entirely to @sgrif's help) auto-queryable and auto-asexpression for diesel-newtype in quodlibetor/diesel-newtype#2. There are even tests that verify that obvious things that should work _do_ work. If anybody wants to try substituting in a newtype using it now might be a reasonable time, although admittedly there's a decent chance that what you'd be doing is helping me debug rather than actually making your code better.

**Comment by quodlibetor** [comment] 2017-08-05 22:13
So I ran into the fact that diesel's query builder operates pretty much entirely on the SQL types of `AsExpression` types, which means that the current implementation of NewTypes aren't type-safe all the way through to the query-builder. Documented [here in this commit](https://github.com/quodlibetor/diesel-newtype/commit/c4896379cac321894176a1c2e32ffce5d071409c). 

I haven't been able to come up with something that would allow strong typing on the rust side of the query builder and still... work... with the rest of diesel. It seems like it is by design that queries operate on SQL types. I mean, it makes sense too, it's not like it's a bad decision.

I'm starting work on a guide around implementing columnar types, and I'm curious if that is an accurate description of the way that diesel treats rust types once they enter the query builder. Additionally, that would affect how I document diesel-newtype.

**Comment by sgrif** [comment] 2017-08-05 22:16
You'd need to create a custom domain type in PG to do what you're describing.

**Comment by quodlibetor** [comment] 2017-08-05 22:31
Okay so that sounds like my understanding is correct but databases may support doing it on their side. I didn't even consider that.

**Comment by sgrif** [comment] 2017-12-16 21:30
Closing as there's nothing actionable here. See https://github.com/diesel-rs/diesel/issues/595#issuecomment-352208313 for more thoughts, and #162 for the tracking issue on ergonomics here.

**Closed by sgrif** 2017-12-16 21:30 UTC
Labels: discussion desired, enhancement
