### ISSUE TITLE
exclusive_transaction and immediate_transaction returning wrong type in callback function

### ISSUE THREAD

**Issue by briancorbin** [diesel-rs/diesel#3576] opened 2023-03-30 18:15 UTC
### Versions

- **Rust:** latest
- **Diesel:** 2.0.3
- **Database:** Sqlite3
- **Operating System** Linux

### Feature Flags

- **diesel:** chrono, sqlite, r2d2

## Problem Description

When using a `PooledConnection` from `r2d2` with `transaction`, the type in the callback function stays the same as expected, but when using `exclusive_transaction` or `immediate_transaction`, the type in the callback function is just `DbConnection`.

Example:

```rust
let manager = ConnectionManager::<SqliteConnection>::new(database_url);
let pool = Pool::builder().build(manager).unwrap();
let mut pooled_conn = pool.get().unwrap();

pooled_conn.transaction(|conn| { // The type here is &mut PooledConnection<ConnectionManager<SqliteConnection>>
...
});

pooled_conn.exclusive_transaction(|conn| { // The type here is &mut SqliteConnection but expecting it to be PooledConnection<ConnectionManager<SqliteConnection>>
...
});

pooled_conn.immediate_transaction(|conn| { // The type here is &mut SqliteConnection but expecting it to be PooledConnection<ConnectionManager<SqliteConnection>>
...
});
```

### What is the expected output?
I would expect that exclusive and immediate transaction behaved similarly to transaction, instead of returning the internal connection.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-03-31 08:17
This is expected behavior because the `transaction` function is provided by the [`Connection` trait](https://docs.diesel.rs/2.0.x/diesel/connection/trait.Connection.html#method.transaction), which is implemented for the [`PooledConnection<>` type](https://docs.diesel.rs/2.0.x/diesel/prelude/trait.Connection.html#impl-Connection-for-PooledConnection%3CM%3E). The `exclusive_transaction` and `immediate_transaction` functions are provided [by `SqliteConnection` itself](https://docs.diesel.rs/2.0.x/diesel/sqlite/struct.SqliteConnection.html#impl-SqliteConnection). You can call these methods on a `PooledConnection` as well as `PooledConnection` implements [`Deref`.](https://docs.diesel.rs/2.0.x/diesel/r2d2/struct.PooledConnection.html#impl-DerefMut-for-PooledConnection%3CM%3E)

I'm closing this issue as that's not a bug, but that's how rusts type system works. If you believe that this behavior needs to be changed in diesel feel free to write a feature request for this. I would expect such an request to include information about how such an change can be done in a backward compatible way and how that should be implemented.

**Closed by weiznich** 2023-03-31 08:17 UTC
Labels: bug
