### ISSUE TITLE
Installation failing on wsl

### ISSUE THREAD

**Issue by makuzaverite** [diesel-rs/diesel#2752] opened 2021-05-02 07:27 UTC
I'm running `cargo install diesel --no-default-features --features postgres` and the installation is failing with error `error: specified package diesel v1.4.6 has no binaries` 

### Versions

- **Rust:1.15.1**
- **Diesel:1.4.6**
- **Database:postgres-12**
- **Operating System:wsl(Ubuntu 20.4)**

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by makuzaverite** [comment] 2021-05-02 07:40
I fixed is by running `sudo apt install libpq-dev` before the command

**Comment by weiznich** [comment] 2021-05-02 07:56
Duplicate of #2264

**Closed** 2021-05-02 07:56 UTC
Labels: bug
