### ISSUE TITLE
losing type information when adding WHERE (filter) clause to query

### ISSUE THREAD

**Issue by is-it-ayush** [diesel-rs/diesel#3900] opened 2024-01-11 04:57 UTC
### Versions

- **Rust:** 1.72.1
- **Diesel:** 2.1.0
- **Database:** 16.1
- **Operating System** Linux  6.1.0-16-amd64

### Feature Flags

- **diesel:** postgres

## Problem Description

Anytime I use a `.filter(some_field.<operator>(some_value))` (ex. `.filter(username.eq("ayush"))`). I loose type information on the returning result. The program still compiles unaffected but the types vanish. Here is an example,

- with `.filter`
![image](https://github.com/diesel-rs/diesel/assets/36449128/1a99aca9-1871-4260-83d6-d792212c80b9)
- without `.filter`
![image](https://github.com/diesel-rs/diesel/assets/36449128/18c74fdc-1456-435a-a201-5ead954d800f)

You'll notice that without filter it's being parsed as `Vec<User>` while with filter it's being parsed as `!` (diverging). I was following the "getting started" guide so I'm not sure what causes this. 

### What are you trying to accomplish?

The type information to be parsed correctly.

### What is the expected output?

The correct type for `results` i.e. `Vec<User>`.

### What is the actual output?

It's `!`. For some reason, rust thinks it's diverging.

### Are you seeing any additional errors?

Nope! The program compiles perfectly fine.

### Steps to reproduce

Unfortunately I don't yet know why this occurs but here is [the link to the above code](https://github.com/is-it-ayush/lune/blob/master/apps/backend/src/main.rs#L110-L115).

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2024-01-11 06:12
Duplicate of https://github.com/diesel-rs/diesel/issues/3876 and https://github.com/rust-lang/rust-analyzer/issues/14607

The code itself is fine as it is accepted by rustc. It's just an IDE issue. There is nothing we can do in diesel to fix this issue. It needs to be fixed in rust-analyzer.

**Closed by weiznich** 2024-01-11 06:12 UTC
Labels: bug

**Comment by opsnull** [comment] 2024-08-02 03:04
same problem here
