### ISSUE TITLE
QueryBuilder for embed

### ISSUE THREAD

**Issue by genofire** [diesel-rs/diesel#2548] opened 2020-10-26 14:48 UTC
- **Diesel:** 1.4.5

It would be nice to use `#[diesel(embed)]` in a normal `Queryable` and to let it fill with `load` it a `inner_join` was used during `QueryBuilder` 

e.g.
```rust
#[derive(Debug, Queryable)]
#[table_name="users"]
pub struct User {
    pub first_name: String,
    pub last_name: String,
}

#[derive(Debug, Queryable)]
#[table_name="posts"]
pub struct PostsWithUser {
    pub title: String,
    pub body: String,
    #[diesel(embed)]
    pub user_name: Option<User>,
}
```

**Comment by weiznich** [comment] 2020-10-26 14:53
Duplicate of #860

**Closed by weiznich** 2020-10-26 14:53 UTC
