### ISSUE TITLE
Issues with PG Named Prepared Statements

### ISSUE THREAD

**Issue by jamatthews** [diesel-rs/diesel#1028] opened 2017-07-16 13:28 UTC
Hello! Really appreciate the work you've been doing so far with Diesel, especially enabling easier untyped SQL statements and typed multi table joins in the recent releases.

The first issue I have is that using named prepared statements causes PG to cache generic query plans. Often this results in horrific performance issues if you have a non-uniform data distribution, if the cached plan is expecting 5 rows and using a loop join, but one row in your table actually joins to 5.7 million rows in the other table. Cached prepared statements also rule out using constraint exclusion on partitioned tables and scan all partitions. I'm working around this by adding `sql::<Bool>("TRUE = TRUE")` to queries which would otherwise be cached. Allegedly this has been fixed in more recent versions of PG, but I'm still experiencing the issue in 9.6.

The second problem is the change in https://github.com/diesel-rs/diesel/pull/686 from using the single statement PQexecParams to PQprepare and PQexecPrepared breaks the ability to use an external connection pool like pgbouncer in "transaction pooling" mode. I think I can work around this issue for now by wrapping each call in an explicit transaction.

Would you consider reverting the change away from using PQexecPrepared? I'm happy to open a PR to optionally disable named prepared statements if you would accept it?

**Comment by sgrif** [comment] 2017-07-16 23:55
There are a lot of deeper issues here which warrant discussion, but the short answer is that yes I would accept a pull request which provides an option to globally disable prepared statement caching.

**Comment by sgrif** [comment] 2017-07-17 13:01
So just to address a few of the specific points here:

> The first issue I have is that using named prepared statements causes PG to cache generic query plans. 

This actually isn't true at all. Generally query planning occurs when the bind parameters are initially passed in. Postgres *may* decide to cache a generic plan, but it will only do so for queries which are frequently executed, and when the generic plan is determined to be roughly as efficient as the plan created with specific values. I'd be surprised if generic plans were being cached in the cases that you've described. Then again, you also sound like you've specifically isolated the issue so ¯\\\_(ツ)\_/¯

> The second problem is the change in #686 from using the single statement PQexecParams to PQprepare and PQexecPrepared breaks the ability to use an external connection pool like pgbouncer in "transaction pooling" mode.

Can you elaborate on this for me? The only difference between using `PQexecParams` and what we're doing now is that one additional `Sync` message is sent between the `Parse` and `Bind`/`Execute` messages. The only way that could cause an issue is if the connection is returned to the pool in between those two round trips, which should not occur even in statement pooling mode. It *certainly* should not occur in transaction pooling mode, since the connection is held for the entire transaction.

Unrelated to the problem you're describing there, I am generally interested in seeing if we can generate deterministic statement names so that they actually can be shared when using pg bouncer (this would require graceful re-preparing behavior since we can no longer guarantee that a statement being in our cache means that it's been prepared on the real connection)

**Comment by sgrif** [comment] 2017-08-05 16:56
Since there isn't any activity on this issue, and there are no actionable items for us to take at this time, I'm going to close this issue.

**Closed by sgrif** 2017-08-05 16:56 UTC

**Comment by DGolubets** [comment] 2022-02-07 11:39
How was this never addressed?
I tried everything, but I just can't use Diesel with PgBouncer. I keep getting either `Error: prepared statement "__diesel_stmt_0" already exists` or `unnamed prepared statement does not exist`.

**Comment by weiznich** [comment] 2022-02-07 12:07
@DGolubets Posting on old issues is discouraged if you cannot add new information, so please don't do that. This issue is explicitly closed as not having any relevant activity for almost 4 years now. If you believe that this issue still exists I suggest that you open a new discussion thread outlining the necessary details. This should include a minimal reproducible example for cases like this.

**Comment by weiznich** [comment] 2023-05-17 05:38
I do generally not answer questions from people that ping me to ask their question. Especially if that happens on an old closed issue that contains already a warning that it is discouraged to post there.
