### ISSUE TITLE
`Nullable<Varchar>` generated instead of `Varchar`

### ISSUE THREAD

**Issue by SamuelMarks** [diesel-rs/diesel#4319] opened 2024-10-21 17:32 UTC
### Versions

- **Rust:** 1.84.0-nightly (662180b34 2024-10-20)
- **Diesel:** 2.2.4
- **Database:** PostgreSQL 17.0
- **Operating System** macOS 15.0.1

### Feature Flags

- **diesel:** postgres, r2d2

### What are you trying to accomplish?
```rs
#[derive(Queryable, Selectable, PartialEq, Debug)]
#[diesel(table_name = crate::schema::users)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct User {
    pub username: String,
    pub password_hash: String,
    pub role: String,
    pub created_at: std::time::SystemTime,
}
```
```sql
CREATE TABLE "users"
(
    username      VARCHAR(50) PRIMARY KEY,
    password_hash VARCHAR(50) NOT NULL,
    role          TEXT        NOT NULL DEFAULT 'regular',
    created_at    TIMESTAMP   NOT NULL DEFAULT current_timestamp
);
```

### What is the expected output?
`schema.rs` of
```
diesel::table! {
    users (username) {
        #[max_length = 50]
        username -> Varchar,
        #[max_length = 50]
        password_hash -> Varchar,
        role -> Text,
        created_at -> Timestamp,
    }
}
```

### What is the actual output?
`schema.rs` of
```
diesel::table! {
    users (username) {
        #[max_length = 50]
        username -> Varchar,
        #[max_length = 50]
        password_hash -> Nullable<Varchar>,
        role -> Nullable<Text>,
        created_at -> Timestamp,
    }
}
```

### Are you seeing any additional errors?
No

### Steps to reproduce

https://github.com/offscale/rust-actix-diesel-auth-scaffold/tree/2f01d2b

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2024-10-22 11:41
I cannot reproduce this locally. Additionally diesel does "only" query the database to get information whether or not a column is nullable. So if your schema.rs file says that the column is nullable the database considers it to be nullable. You should be able to verify this by using the following query:

```sql
SELECT "information_schema"."columns"."column_name", "information_schema"."columns"."udt_name", "information_schema"."columns"."udt_schema", "information_schema"."columns"."is_nullable", "information_schema"."columns"."character_maximum_length", col_description('users'::regclass, "information_schema"."columns"."ordinal_position") FROM "information_schema"."columns" WHERE (("information_schema"."columns"."table_name" = 'users') AND ("information_schema"."columns"."table_schema" = 'public')) ORDER BY "information_schema"."columns"."ordinal_position"
```

Please provide the output of that query for further debugging, otherwise this issue will likely be closed as cannot reproduce.

**Comment by SamuelMarks** [comment] 2024-10-22 14:57
Try deleting the schema.rs file. Then run that diesel command again and you'll see it get regenerated. It has `Nullable`s; it shouldn't.

And to answer your question:
```
  column_name  | udt_name  | udt_schema | is_nullable | character_maximum_length | col_description 
---------------+-----------+------------+-------------+--------------------------+-----------------
 username      | varchar   | pg_catalog | NO          |                       50 | 
 password_hash | varchar   | pg_catalog | YES         |                       50 | 
 role          | text      | pg_catalog | YES         |                          | 
 created_at    | timestamp | pg_catalog | NO          |                          | 
(4 rows)
```

**Comment by weiznich** [comment] 2024-10-22 16:06
Thanks for providing the output of that query. This output clearly shows that the database allows nullable values for these columns. 
At this point it's likely that the provided SQL does not match that SQL what you actually used to create the table. The other possibility is a bug in the database system itself. 

Both variants are not an issue in diesel, so I will close this issue now.

**Closed by weiznich** 2024-10-22 16:06 UTC
Labels: cli, waiting on author
