### ISSUE TITLE
Couldn't compile Diesel CLI

### ISSUE THREAD

**Issue by ErKiran** [diesel-rs/diesel#2465] opened 2020-07-25 08:24 UTC
### Versions

- **Rust: 1.43.1**
- **Diesel: 1.4.5 **
- **Database: Postgres**
- **Operating System: Ubuntu 18.04**

- **diesel:**

### cargo install diesel_cli --no-default-features --features postgres

While I tried to install diesel_cli it doesn't compile

### Error Details 

  = note: /usr/bin/ld: cannot find -lpq
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: failed to compile `diesel_cli v1.4.1`, intermediate artifacts can be found at `/tmp/cargo-installQgoTiD`

Caused by:
  could not compile `diesel_cli`.

Caused by:
  process didn't exit successfully: `rustc --crate-name diesel /home/dell/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_cli-1.4.1/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="postgres"' --cfg 'feature="url"' --cfg 'feature="uses_information_schema"' -C metadata=a376b852c5e09ca0 -C extra-filename=-a376b852c5e09ca0 --out-dir /tmp/cargo-installQgoTiD/release/deps -L dependency=/tmp/cargo-installQgoTiD/release/deps --extern chrono=/tmp/cargo-installQgoTiD/release/deps/libchrono-a58b7f634a5badf2.rlib --extern clap=/tmp/cargo-installQgoTiD/release/deps/libclap-c845efac5415846e.rlib --extern diesel=/tmp/cargo-installQgoTiD/release/deps/libdiesel-f7dea6ee5879810b.rlib --extern dotenv=/tmp/cargo-installQgoTiD/release/deps/libdotenv-0b34d54f785de7cd.rlib --extern migrations_internals=/tmp/cargo-installQgoTiD/release/deps/libmigrations_internals-a22cb50220ae6c34.rlib --extern serde=/tmp/cargo-installQgoTiD/release/deps/libserde-ceeaa00a2f7300d8.rlib --extern tempfile=/tmp/cargo-installQgoTiD/release/deps/libtempfile-de92fb555baf370b.rlib --extern toml=/tmp/cargo-installQgoTiD/release/deps/libtoml-8cb8e81e86646297.rlib --extern url=/tmp/cargo-installQgoTiD/release/deps/liburl-426f8dc9b35a5314.rlib --cap-lints allow` (exit code: 1)

**Comment by weiznich** [comment] 2020-07-25 11:52
Duplicate of #487

**Closed by weiznich** 2020-07-25 11:52 UTC

**Comment by ErKiran** [comment] 2020-07-25 13:45
@weiznich How this issue is Duplicate of #487 .
I am not in Windows and doesn't want to install Sqlite feature.
cargo install diesel_cli --no-default-features --features postgres 
I am trying to install postgres features only.

**Comment by weiznich** [comment] 2020-07-25 13:53
The this is a duplicate of #1592.

**Comment by ErKiran** [comment] 2020-07-25 14:35
@weiznich Thanks for #1592 that works.

**Comment by blcklptn** [comment] 2023-02-08 13:35
Probably someone else will run into this problem. If you have MACOS, then just install the library and postgresql with brew.

```sh
brew install libpg postgresql
cargo install diesel_cli --no-default-features --features postgres
```
