### ISSUE TITLE
`diesel migration run` doesn't rename column name in `joinable!` macro when a Rust keyword is used.

### ISSUE THREAD

**Issue by Krapaince** [diesel-rs/diesel#2809] opened 2021-06-15 20:37 UTC
### Versions

- **Rust:**`1.51.1`
- **Diesel cli:**`1.4.1`
- **Database:**`Postgres
- **Operating System**`Arch Linux`

### Feature Flags

- **diesel:**`postgres`

## Problem Description
I have used the following script as a migration one:
```sql
CREATE TABLE IF NOT EXISTS user_types
(
    id SERIAL NOT NULL
        CONSTRAINT user_types_pk
            PRIMARY KEY,
    type TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id SERIAL NOT NULL
        CONSTRAINT users_pk
            PRIMARY KEY,
    type INT NOT NULL,

    CONSTRAINT users_fk FOREIGN KEY (type) REFERENCES user_types(id)
);
```
which uses the Rust keyword `type` and the outputted `schema.rs` is invalid.

### What are you trying to accomplish?
Have a column named `type` with a `FOREIGN KEY` `CONSTRAINT`.

### What is the expected output?
- Short version
```rust
joinable!(users -> user_types (type_));
```
<details><summary>Complete version</summary>

```rust
table! {
    user_types (id) {
        id -> Int4,
        #[sql_name = "type"]
        type_ -> Text,
    }
}

table! {
    users (id) {
        id -> Int4,
        #[sql_name = "type"]
        type_ -> Int4,
    }
}

joinable!(users -> user_types (type_));

allow_tables_to_appear_in_same_query!(
    user_types,
    users,
);
```

- `cargo check` output:
```
    Checking binary v0.1.0 (/home/krapaince//diesel_test)
error: expected identifier, found keyword `type`
  --> src/schema.rs:17:1
   |
17 | joinable!(users -> user_types (type));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected identifier, found keyword
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can escape reserved keywords to use them as identifiers
   |
17 | joinable!(users -> user_types (r#type));
   |                                ^^^^^^

error: expected identifier, found keyword `type`
  --> src/schema.rs:17:1
   |
17 | joinable!(users -> user_types (type));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected identifier, found keyword
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can escape reserved keywords to use them as identifiers
   |
17 | joinable!(users -> user_types (r#type));
   |                                ^^^^^^

error[E0412]: cannot find type `r#type` in module `users`
  --> src/schema.rs:17:32
   |
9  | / table! {
10 | |     users (id) {
11 | |         id -> Int4,
12 | |         #[sql_name = "type"]
13 | |         type_ -> Int4,
14 | |     }
15 | | }
   | |_- similarly named struct `type_` defined here
16 | 
17 |   joinable!(users -> user_types (type));
   |                                  ^^^^ help: a struct with a similar name exists: `type_`

error[E0425]: cannot find value `r#type` in module `users`
  --> src/schema.rs:17:32
   |
9  | / table! {
10 | |     users (id) {
11 | |         id -> Int4,
12 | |         #[sql_name = "type"]
13 | |         type_ -> Int4,
14 | |     }
15 | | }
   | |_- similarly named unit struct `type_` defined here
16 | 
17 |   joinable!(users -> user_types (type));
   |                                  ^^^^ help: a unit struct with a similar name exists: `type_`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0412, E0425.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `binary`

To learn more, run the command again with --verbose.
```
</details>

### What is the actual output?
- Short version
```rust
joinable!(users -> user_types (type));
```
<details><summary>Complete version</summary>
- `schema.rs`

```rust
table! {
    user_types (id) {
        id -> Int4,
        #[sql_name = "type"]
        type_ -> Text,
    }
}

table! {
    users (id) {
        id -> Int4,
        #[sql_name = "type"]
        type_ -> Int4,
    }
}

joinable!(users -> user_types (type));

allow_tables_to_appear_in_same_query!(
    user_types,
    users,
);
```

</details>

### Are you seeing any additional errors?
Tested with the following keywords:`as`, `break`, `struct` in the migration
script instead of `type` which leads to the same result. Assuming that this is
an issue with the schema generator when it reaches the `joinable!` part.

### Steps to reproduce
```bash
cargo new binary
cd binary
# setup a postgres database see the `Additional files` below.
diesel setup
diesel migration generate type_keyword
# copy the Migration file (`up.sql`) from this issue into `migrations/XXXXXX_type_keyword/up.sql`
diesel migration run
# cppy the `main.rs` from this issue into `src/main.rs`
cargo check
```

- Migration file (`up.sql`):
```sql
CREATE TABLE IF NOT EXISTS user_types
(
    id SERIAL NOT NULL
        CONSTRAINT user_types_pk
            PRIMARY KEY,
    type TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id SERIAL NOT NULL
        CONSTRAINT users_pk
            PRIMARY KEY,
    type INT NOT NULL,

    CONSTRAINT users_fk FOREIGN KEY (type) REFERENCES user_types(id)
);
```

- `main.rs`:
```rust
mod schema;

#[macro_use]
extern crate diesel;

fn main() {
    println!("Hello, world!");
}
```

- `Cargo.toml`:
```
[package]
name = "binary"
version = "0.1.0"
edition = "2018"

[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
```

<details><summary>Additional files:`docker-compose.yaml` & `.env`:</summary>
Those are the files used for the postgres database.
- `docker-compose.yaml`
```yaml
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
```

- `.env`
```
POSTGRES_PASSWORD=password
POSTGRES_USER=postgres
POSTGRES_DB=db

DATABASE_URL=postgres://postgres:password@localhost/db
```
</details>

## Checklist

- [x] I have already looked over the [issue
  tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion
  forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible
  closed issues.

 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2021-06-16 07:22
Thanks for this well written bug report. As far as I can tell this is a duplicate of https://github.com/diesel-rs/diesel/issues/1609 which means this is already fixed by #1897. This fix is not included in any release yet. https://github.com/diesel-rs/diesel/issues/2090 claims that this can even happen with the fixed version, but I haven't been able to reproduce that yet.
Closed as duplicate

**Closed by weiznich** 2021-06-16 07:22 UTC
Labels: bug
