### ISSUE TITLE
`overflow evaluating the requirement` when writing generic diesel code

### ISSUE THREAD

**Issue by vidhanio** [diesel-rs/diesel#3882] opened 2023-12-18 01:22 UTC
i'm trying to write some generic diesel code, and have been unable to get around this trait bound error. am i missing something obvious? my trait bounds seem correct but it just doesn't compile.

## Minimal Reproducible Example

```rust
use std::any::Any;

// diesel = "2.1.4"
use diesel::{
    helper_types::{Eq, FindBy, Select},
    query_dsl::methods::{FilterDsl, SelectDsl},
    Expression,
};

diesel::table! {
    fakes (name) {
        name -> Text,
    }
}

fn foo<S>(s: S)
where
    S: Expression,

    fakes::table: SelectDsl<S>,
    Select<fakes::table, S>: FilterDsl<Eq<fakes::name, String>>,
    FindBy<Select<fakes::table, S>, fakes::name, String>: Any, // some other bound
{
}
```

## Build Error

```rust
error[E0277]: the trait bound `<table as SelectDsl<S>>::Output: Table` is not satisfied
  --> src/lib.rs:16:1
   |
16 | / fn foo<S>(s: S)
17 | | where
18 | |     S: Expression,
19 | |
20 | |     fakes::table: SelectDsl<S>,
21 | |     Select<fakes::table, S>: FilterDsl<Eq<fakes::name, String>>,
22 | |     FindBy<Select<fakes::table, S>, fakes::name, String>: Any, // some other bound
   | |______________________________________________________________^ the trait `Table` is not implemented for `<table as SelectDsl<S>>::Output`
   |
   = help: the trait `Table` is implemented for `table`
   = note: required for `<table as SelectDsl<S>>::Output` to implement `FilterDsl<expression::grouped::Grouped<expression::operators::Eq<columns::name, expression::bound::Bound<diesel::sql_types::Text, String>>>>`

error[E0277]: the trait bound `<table as SelectDsl<S>>::Output: Query` is not satisfied
  --> src/lib.rs:16:1
   |
16 | / fn foo<S>(s: S)
17 | | where
18 | |     S: Expression,
19 | |
20 | |     fakes::table: SelectDsl<S>,
21 | |     Select<fakes::table, S>: FilterDsl<Eq<fakes::name, String>>,
22 | |     FindBy<Select<fakes::table, S>, fakes::name, String>: Any, // some other bound
   | |______________________________________________________________^ the trait `Query` is not implemented for `<table as SelectDsl<S>>::Output`
   |
   = help: the following other types implement trait `Query`:
             DeleteStatement<T, U, ReturningClause<Ret>>
             BoxedSqlQuery<'_, DB, Q>
             SqlLiteral<ST, T>
             UncheckedBind<Q, Value>
             query_builder::combination_clause::CombinationClause<Combinator, Rule, Source, Rhs>
             InsertStatement<T, U, Op, ReturningClause<Ret>>
             BoxedSelectStatement<'a, ST, QS, DB, GB>
             SelectStatement<F, S, D, W, O, LOf, G, H, LC>
           and 6 others
   = note: required for `<table as SelectDsl<S>>::Output` to implement `AsQuery`
   = note: required for `<table as SelectDsl<S>>::Output` to implement `FilterDsl<expression::grouped::Grouped<expression::operators::Eq<columns::name, expression::bound::Bound<diesel::sql_types::Text, String>>>>`

error[E0275]: overflow evaluating the requirement `<<table as SelectDsl<S>>::Output as FilterDsl<expression::grouped::Grouped<expression::operators::Eq<columns::name, expression::bound::Bound<..., ...>>>>>::Output == _`
  --> src/lib.rs:16:1
   |
16 | / fn foo<S>(s: S)
17 | | where
18 | |     S: Expression,
19 | |
20 | |     fakes::table: SelectDsl<S>,
21 | |     Select<fakes::table, S>: FilterDsl<Eq<fakes::name, String>>,
22 | |     FindBy<Select<fakes::table, S>, fakes::name, String>: Any, // some other bound
   | |______________________________________________________________^

Some errors have detailed explanations: E0275, E0277.
For more information about an error, try `rustc --explain E0275`.
error: could not compile `rust-playground` (lib) due to 3 previous errors
```

**Comment by weiznich** [comment] 2023-12-18 09:11
Duplicate of #3880. Also that's not a diesel issue (as the compiler error is clearly in your code) + it does not follow the required issue template.

**Closed by weiznich** 2023-12-18 09:11 UTC
