### ISSUE TITLE
he trait `diesel::Expression` is not implemented for `i64`

### ISSUE THREAD

**Issue by puffanddmx** [diesel-rs/diesel#2638] opened 2021-02-03 02:53 UTC
hi!

i am testing rockets for testing web login. when i run build , i got this error.

-my code

https://github.com/puffanddmx/rust_webserver/blob/master/src/model.rs#L3-L15

https://github.com/puffanddmx/rust_webserver/blob/master/Cargo.toml#L13

-error
 src/model.rs:10:10
   |
10 | #[derive(Insertable)]
   |          ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `i64`
   |
   = note: required because of the requirements on the impl of `AsExpression<diesel::sql_types::Unsigned<diesel::sql_types::BigInt>>` for `i64`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `i64: diesel::Expression` is not satisfied
  --> src/model.rs:10:10
   |
10 | #[derive(Insertable)]
   |          ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `i64`
   |
   = note: required because of the requirements on the impl of `diesel::Expression` for `&'insert i64`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `i64: diesel::Expression` is not satisfied
  --> src/model.rs:10:10
   |
10 | #[derive(Insertable)]
   |          ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `i64`
   |
   = note: required because of the requirements on the impl of `diesel::Expression` for `&i64`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `hello-rocket`

-->

**Comment by weiznich** [comment] 2021-02-03 08:07
Closed as this does not use our issue template, which is mandatory. Additionally this is a duplicate of existing "issues".

**Closed by weiznich** 2021-02-03 08:07 UTC
Labels: bug

**Comment by MightyPork** [comment] 2021-03-11 22:29
That's cool, but it's now ranking high on google and I am left with having to ask here how to solve it :/
The feature "numeric" does not help

**Comment by weiznich** [comment] 2021-03-12 08:38
@MightyPork That's not the right place to ask such questions. Our issue tracker is for tracking bugs for our contributors not for providing support for our users. We have other places for such questions, please use them. Otherwise I do not really care if this is ranked high on google or somewhere else. That's no reason to not respect our rules.

**Comment by MightyPork** [comment] 2021-03-12 09:20
@weiznich I don't understand why you are so angry, I just asked a question. You could have gave me a short answer or linked some related issue, instead you told me exactly nothing.

For future users who hit this issue, I found the following:

As I understand it, sqlite supports i64 just fine, but does not support u64. The Sqlite backend in this crate is hard-wired to use `i32` (https://github.com/diesel-rs/diesel/issues/1116) . I believe it can be worked around by using BigInt or a custom type wrapper. For now I switched my tables to use i32, as it was the easiest fix.

from the sqlite documentation (https://www.sqlite.org/datatype3.html):
> INTEGER. The value is a signed integer, stored in 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.
> ... If the TEXT value is a well-formed integer literal that is too large to fit in a 64-bit signed integer, it is converted to REAL.

**Comment by weiznich** [comment] 2021-03-12 09:22
@MightyPork Again: This is not the right place for such comments. Please move them somewhere else.

**Comment by MightyPork** [comment] 2021-03-12 09:24
Jesus, why are you like this? If someone finds this on google, they want to solve their problem, not read your tirade about people not using gitter.

I gave the answer. Please.

**Comment by weiznich** [comment] 2021-03-12 09:28
@MightyPork Again that's not the right place for such discussions. It's up to us maintainers to decide what we accept in our issue tracker and what does not belong here, not to same obscure google algorithm that decided that this shows up high in their results.
Also if you don't want to use gitter there are other options listed in our documentation.

**Comment by biot023** [comment] 2022-05-05 09:58
@MightyPork 
You've saved me a lot of time there, man, cheers.
I'm using MySQL but have hit the same problem -- it really doesn't seem to like converting from `bigint(20)` -> `i64` but is perfectly happy with `int(11)` -> `i32`.
So I'm creating IDs and foreign keys with `i32` for now.
Is this still the best solution?

**Comment by weiznich** [comment] 2022-05-05 10:03
@biot023 Closed stale issues like that one are always the wrong place to ask for help. Please don't do that. Either use our gitter room or the discussion forum to ask for help.

**Comment by jafar75** [comment] 2024-06-01 09:56
@weiznich instead of saying bunch of repeated things again and agian and agian, please provide some links for gitter room, discussion forum!
